### ISSUE TITLE
SearchCode - Errant "[" after code snippet?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#103]
Looks like the parser is adding `[]` around it the "More at" link which is causing problems. We can remove them as the source has rebranded itself anyways: https://searchcode.com/

https://duckduckgo.com/?q=php+implode

![php_implode__php__at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/5074168/d8cf31d6-6e55-11e4-848a-583ca51772a0.png)

**Comment by arush0311** [comment]
Can I take this?

**Comment by moollaza** [comment]
Yes!

**Comment by arush0311** [comment]
Sorry I could not find where the bug is. Can you help me?

**Comment by rasikapohankar** [comment]
Hey @moollaza! Is this done? If not, can I try this?

**Comment by sahildua2305** [comment]
Anyone of you working on this? @rasikapohankar @arush0311

**Comment by moollaza** [comment]
@sahildua2305 you should be good to work on this 👍

**Comment by sahildua2305** [comment]
@moollaza Can you please help me in finding the code for this one? Unable to locate it in `/lib/fathead/` :disappointed:

**Comment by moollaza** [comment]
@sahildua2305 it looks like this IA may actually be internal, meaning it's probably a little outdated. 

@jdorweiler can you confirm if the PHP Fathead still exists internally?

@sahildua2305 would you be interested in created a new open-source, PHP Fathead?

**Comment by sahildua2305** [comment]
@moollaza yes! I'll be interested in creating a new PHP fathead once it's confirmed that the internal one doesn't exist.

**Comment by moollaza** [comment]
> yes! I'll be interested in creating a new PHP fathead once it's confirmed that the internal one doesn't exist.

@sahildua2305 seeing as we can't find it in the repo it almost certainly exists internally, but I doubt we have the original scripts used. It's likely just the data so an updated/improved open source PHP Instant Answer would only be an improvement. Ideally all the Programming Language Fatheads should be open source!

**Comment by sahildua2305** [comment]
@moollaza Ok. So I will start working on it.

> Ideally all the Programming Language Fatheads should be open source!
Yes I could see Fatheads for almost all major languages except for PHP.

Also, as I can see for other fatheads, we can use any of the languages (Go, JS or Python) for downloading and parsing?

**Comment by jdorweiler** [comment]
The old fathead is opensource but doesn't work anymore. I think this is the one https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/UNCLEAN/parse_phpfunction.py

I'd just start over from scratch though.

**Comment by sahildua2305** [comment]
@jdorweiler I think I will be good to take this up. What do you think?
cc @moollaza

**Comment by jdorweiler** [comment]
@sahildua2305 sounds good. Ping me on a pull request if you need any help.

**Comment by sahildua2305** [comment]
Sure! @jdorweiler

**Comment by moollaza** [comment]
Will be fixed in #399
