### ISSUE TITLE
Add more docs from MDN

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-fathead#110]
MDN fathead currently only pulls docs on global JS objects. Would be very useful if we could cover more of the other sections too.

https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
https://developer.mozilla.org/en-US/docs/Web/HTML/Element
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
https://developer.mozilla.org/en-US/docs/Web/API

cc @mrshu @jdorweiler

**Comment by jdorweiler** [comment]
I added Web/API but we could still use the others.

**Comment by moollaza** [comment]
I believe all of this will be addressed when the new JavaScript Fathead goes live.

The new MDN CSS Fathead takes care of the CSS Reference 👍

**Comment by moollaza** [comment]
HTML is also being taken care of by the new HTML Fathead 👍
