### ISSUE TITLE
Inconsistent title on query: suitable | PyPI

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/zeroclickinfo-fathead#113]
The Definition (wordnik) IA is triggered, however the title is changed as the [PyPI.pm](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/DDG/Fathead/PyPI.pm) flathead is also triggered, this is incorrect.

**Reproduce Issue:** 
https://duckduckgo.com/?q=suitable

**Expected result:** 

``` html
<title>suitable at DuckDuckGo</title>
```

**Actual result**

``` html
<title>suitable (Python) at DuckDuckGo</title>
```

**Comment by Hestben** [comment]
This issue seems to be fixed (The example works for me).
