### ISSUE TITLE
unix_man missing a lot

### ISSUE THREAD

**Issue by dermusikman** [duckduckgo/zeroclickinfo-fathead#118]
[Unix man](http://duck.co/ia/view/unix_man) seems to be missing a lot. I've tried `man bash`, `man dd`, `man sh`... these are not obscure, but they're not getting picked up.  If it's an issue with the source, I wonder if this may need to be revised. I might also recommend the man pages from [die.net](http://linux.die.net/man/).

I'm happy to contribute, if that's what it would take. Wanted to bring up the issue, though, before getting into the code.

**Comment by jdorweiler** [comment]
@dermusikman Running an update right now, thanks!
I like die.net too.  Feel free to switch the code over to use that site if you want.

**Comment by jdorweiler** [comment]
@dermusikman should be live in the next few days :cake: 
![selection_374](https://cloud.githubusercontent.com/assets/1882892/6451072/03082efc-c0fa-11e4-88e9-9c7e4f56863f.png)
