### ISSUE TITLE
airport code parse error

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#123]
I get the following error when running the airport code parser.  https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/share/fathead/airports/parse.py
```
DEBUG:root:Index: A
Traceback (most recent call last):
  File "parse.py", line 222, in <module>
    parser.get_airports()
  File "parse.py", line 153, in get_airports
    table = self.soup.find_all('table')[1]
IndexError: list index out of range
```

**Comment by pfirsichbluete** [comment]
The wiki's page structure changed. Pull request https://github.com/duckduckgo/zeroclickinfo-fathead/pull/124
adapts the fathead to those changes.
