### ISSUE TITLE
Wikipedia French: Meanings subheading has typo

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-fathead#128]
Searching for [Notre Dame](https://duckduckgo.com/?q=Notre+Dame&kad=fr_FR&ia=meanings) returns the IA subheading "Affichage 186 ÉLéments". This should be "Affichage 186 Éléments" (lower case L).

-- http://duck.co/ia/view/wikipedia_french

**Comment by b1ake** [comment]
@moollaza It looks like a typo in the translation token for the word 'Items', which lives in the community platform I think. Maybe @jbarrett or @zekiel can fix it or show us how to do ourselves?

Screenshot of the issue:
![2015-04-04_1329](https://cloud.githubusercontent.com/assets/8975/6993802/a46b9b7e-dace-11e4-9bfb-c716b38151bb.png)

**Comment by b1ake** [comment]
@moollaza Scratch that, I just saw that it's correct here: https://duck.co/translate/tokenlanguage/117190 (as @mrshu has noted).

We'll look into it internally, it might be something with how our capitalize string code works on the frontend. Maybe the accented first letter is throwing it off. cc @bsstoner

**Comment by tagawa** [comment]
Thanks @b1ake. And when you consider adding a Japanese Wikipedia IA please count me in for QA/dev/whatever.

**Comment by b1ake** [comment]
@tagawa Okay great! I'm ccing @mrshu, as he'll be involved with that too when we get to it.

**Comment by zekiel** [comment]
just caught this in my old notifications -- please let me know if anything else is still needed

**Comment by tagawa** [comment]
Thanks @zekiel. The problem's still there even though the translation token is correct so it must be the frontend's capitalization logic, as @b1ake mentioned.

**Comment by mrshu** [comment]
I am not sure if this was intentional or not, but it turns out that I can no longer see ÉLéments on the page (https://duckduckgo.com/?q=Notre+Dame&kad=fr_FR&ia=meanings).

@tagawa would you mind confirming that and then perhaps closing this issue?

Thanks!

**Comment by tagawa** [comment]
Yes, looks like that term is not used now so all good.
