### ISSUE TITLE
Add wink to emoticon meanings

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-fathead#129]
Both these emoticons:
;)
;-)
can be used to mean "winking".

http://duck.co/ia/view/emoticon

**Comment by pjhampton** [comment]
Hey @tagawa!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.

**Comment by tagawa** [comment]
Thanks for letting me know @pjhampton ;-)
Ah well, I'll try again another time.
