### ISSUE TITLE
File Formats: IA is outdated, does not work with latest data

### ISSUE THREAD

**Issue by smola** [duckduckgo/zeroclickinfo-fathead#133]
File Formats IA relies on all extensions being present in this URL:
https://en.wikipedia.org/wiki/List_of_filename_extensions_(alphabetical)

But this list has been splitted into different pages, so it does not work anymore.

---

IA Page:  http://duck.co/ia/view/file_formats

**Comment by moollaza** [comment]
The code for this one can be found here:
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/share/fathead/file_formats/parse.go

Looks like it needs some updates!

**Comment by sahildua2305** [comment]
Looks like it's not there anymore, @moollaza

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Yeah - it got moved https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/file_formats/parse.go! I wonder if any docs are outdated...
