### ISSUE TITLE
IOS:  bad result for "ios devices"

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#134]
![selection_084](https://cloud.githubusercontent.com/assets/1882892/8216306/b028e150-1503-11e5-8800-118b501a02ca.png)
---

IA Page:  http://duck.co/ia/view/ios

**Comment by moollaza** [comment]
@jdorweiler any idea how we can fix? I take it, this isn't an internal fix?

**Comment by jdorweiler** [comment]
Looks like the code is here https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/share/fathead/UNCLEAN/parse_appleosx.py

Reprocessing the data is probably best.  I'm sure it's been a long time since that was done anyway.

**Comment by moollaza** [comment]
Looks to be fixed: https://duckduckgo.com/?q=ios+devices&t=opera&ia=web
