### ISSUE TITLE
Perl6Doc: Documented example "perl 6 str" does not work.

### ISSUE THREAD

**Issue by Juerd** [duckduckgo/zeroclickinfo-fathead#136]
There's no instant answer box when you search for "perl 6 str". The first regular hit is great, but it's probably better if the first documented example worked as expected :-)

The examples "Str.rindex" and "Int.div perl6" work fine.

------
IA Page:  http://duck.co/ia/view/perl6doc

**Comment by moollaza** [comment]
@jdorweiler could it be that the Fathead is out of date and needs to be re-run?

**Comment by xfix** [comment]
Seems to for me.

**Comment by moollaza** [comment]
@xfix looks to be working for me too now :+1:
