### ISSUE TITLE
PyPi: module info out of date

### ISSUE THREAD

**Issue by mbeijen** [duckduckgo/zeroclickinfo-fathead#137]
The module information for the pypi instant answer is out of date. The Latest Version is incorrect and also the 'More at Python Package Index'  points at the location of the old package.

In case of [certifi](https://duckduckgo.com/?q=python+certifi&ia=about) the package points to version https://pypi.python.org/pypi/certifi/14.05.14 while the latest version is a year newer. This is not only with the _certify_ module but I tried other modules as well. Try [python requests](https://duckduckgo.com/?q=python+requests&ia=about) or [python panda](https://duckduckgo.com/?q=python+panda&ia=about)

![ddg-pypi-certifi](https://cloud.githubusercontent.com/assets/659504/8385369/18953496-1c48-11e5-80bf-f40f5b5c4281.png)

------
IA Page:  http://duck.co/ia/view/py_pi

**Comment by moollaza** [comment]
@jdorweiler shall we re-run the fathead?

**Comment by jdorweiler** [comment]
@mbeijen @moollaza thanks! I'll make a task to update the data.

**Comment by jdorweiler** [comment]
I update it today.  Thanks @mbeijen
