### ISSUE TITLE
MDNJS: [ and ] for optional parameters are not shown

### ISSUE THREAD

**Issue by stelt** [duckduckgo/zeroclickinfo-fathead#140]
------
IA Page:  http://duck.co/ia/view/mdnjs

**Comment by moollaza** [comment]
@stelt thanks a lot for reporting this!

Can you please explain in a little more detail what the problem is? Do you have an example link that demonstrates the problem?

**Comment by stelt** [comment]
https://duckduckgo.com/?q=mdn+substr&t=ffsb&ia=about&iax=1
gives
String.prototype.substr (start, length)
and via "More at Mozilla Developer Network"
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
gives
str.substr(start[, length])

Only in 1 of the 2 cases it's clear LENGTH is an optional parameter
