### ISSUE TITLE
Subversion: use version 1.7 of the svn book

### ISSUE THREAD

**Issue by AnthonyMastrean** [duckduckgo/zeroclickinfo-fathead#141]
The svn "fathead" links to out-of-date docs (1.5). The latest is 1.7 and 1.8 is in draft now.

https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/share/fathead/UNCLEAN/parse_svn.py#L38

---

IA Page:  http://duck.co/ia/view/subversion

**Comment by moollaza** [comment]
@AnthonyMastrean thanks a lot for reporting this!

The linked file isn't actually the code that's being used in production, it's code from a developer who wrote a scraper for SVN that he's "donated" to use in case any devs out there feel like adapting it for a Fathead Instant Answer.

This is actually a "legacy", internal IA which will need to be fixed internally.

**Comment by pjhampton** [comment]
Hey @AnthonyMastrean 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
