### ISSUE TITLE
MySQL: linebreaks `__NEWLINE__` and prefix 'mysql>' shown in example view

### ISSUE THREAD

**Issue by ghost** [duckduckgo/zeroclickinfo-fathead#142]
When DDG-ing for [`mysql substring`](https://duckduckgo.com/?q=mysql+substring), the example view contains:

``` sql
SUBSTRING(str,pos), SUBSTRING(str FROM pos), SUBSTRING(str,pos,len), SUBSTRING(str FROM pos FOR len):
mysql> SELECT SUBSTRING('Quadratically',5); -> 'ratically' __NEWLINE__mysql> SELECT SUBSTRING('foobarbar' FROM 4); -> 'barbar' __NEWLINE__mysql> SELECT SUBSTRING('Quadratically',5,6); -> 'ratica' __NEWLINE__mysql> SELECT SUBSTRING('Sakila', -3); -> 'ila' __NEWLINE__mysql> SELECT SUBSTRING('Sakila', -5, 3); -> 'aki' __NEWLINE__mysql> SELECT SUBSTRING('Sakila' FROM -4 FOR 2); -> 'ki'
```

It contains linebreaks `__NEWLINE__` and prefix `mysql>`.

Instead, this would be much more readable:

``` sql
SUBSTRING(str,pos), SUBSTRING(str FROM pos), SUBSTRING(str,pos,len), SUBSTRING(str FROM pos FOR len):

SELECT SUBSTRING('Quadratically',5); -> 'ratically'
SELECT SUBSTRING('foobarbar' FROM 4); -> 'barbar'
SELECT SUBSTRING('Quadratically',5,6); -> 'ratica'
SELECT SUBSTRING('Sakila', -3); -> 'ila'
SELECT SUBSTRING('Sakila', -5, 3); -> 'aki'
SELECT SUBSTRING('Sakila' FROM -4 FOR 2); -> 'ki'
```

---

IA Page:  http://duck.co/ia/view/my_sql

**Comment by moollaza** [comment]
@fcturner thanks for reporting!

**Comment by moollaza** [comment]
Crap, looks like this is an internal IA. We'll have to do it ourselves I guess.

@jdorweiler do you have any idea if we can open source this IA? Should we ask the community to re-implement it themselves?

**Comment by jdorweiler** [comment]
I think this is it.  Unfortunatly, I don't think it's working. https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/UNCLEAN/parse_mysqlfunction.py

**Comment by pjhampton** [comment]
Passing comments to internal team.
