### ISSUE TITLE
HelloWorld: fullstop required after certain "hello world" searches

### ISSUE THREAD

**Issue by JamyGolden** [duckduckgo/zeroclickinfo-fathead#143]
While going through the [Basic Fathead Tutorial](https://duck.co/duckduckhack/fathead_basic_tutorial) I noticed it has an example link of the "hello world" [Instant Answer](https://duckduckgo.com/?q=hello+world+scala.). That link has a fullstop in search. I tried removing it and the instant answer stopped working entirely.

Doesn't Work:
`hello world scala` [link](https://duckduckgo.com/?q=hello+world+scala)
`hello world javascript` [link](https://duckduckgo.com/?q=hello+world+javascript)

However this does work (added fullstop at the end):
`hello world scala.` [link](https://duckduckgo.com/?q=hello+world+scala.)
`hello world javascript.` [link](https://duckduckgo.com/?q=hello+world+javascript.)

`python` and `ruby` both work [with](https://duckduckgo.com/?q=hello+world+python) and [without](https://duckduckgo.com/?q=hello+world+python.) the fullstops so this doesn't seem to be consistent.

------
IA Page:  http://duck.co/ia/view/hello_world

**Comment by moollaza** [comment]
@JamyGolden thanks for reporting!

I'm able to recreate this for the JavaScript example, however it works as expected for the "hello world scala" query.

I suspect another Instant Answer may have taken priority in these cases.

@jdorweiler any ideas why the JavaScript link doesn't pop the IA at all? Can the Q/A tab be blocking this IA?

**Comment by jdorweiler** [comment]
Looks like it's been fixed.
