### ISSUE TITLE
Plural: weird result for moose

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#145]
Maybe something with the extra parentheses?
![selection_041](https://cloud.githubusercontent.com/assets/1882892/9509286/baa29888-4c2b-11e5-9122-325de228d22a.png)
![selection_042](https://cloud.githubusercontent.com/assets/1882892/9509289/bf0b2b88-4c2b-11e5-809f-0d46e829ffb5.png)
https://duckduckgo.com/?q=plural+moose&ia=about

------
IA Page:  http://duck.co/ia/view/plural

**Comment by jdorweiler** [comment]
@wilkox any interest in looking at this bug?

**Comment by wilkox** [comment]
I'll take a look at it.

**Comment by jdorweiler** [comment]
@wilkox thanks!
