### ISSUE TITLE
GitManual: Source seems to have been taken down

### ISSUE THREAD

**Issue by andrey-p** [duckduckgo/zeroclickinfo-fathead#147]
Just tried clicking the MoreAt link when searching for e.g. `git push` and got a 404. Maybe we need a new source?

------
IA Page:  http://duck.co/ia/view/git_manual

**Comment by tuxd00d** [comment]
I noticed that as well ...

[http://csurs.csr.uky.edu/](http://csurs.csr.uky.edu/) no longer provides a man2html service.

[http://linux.die.net/man/](http://linux.die.net/man/) is one that has been around since ... forever.

**Comment by runical** [comment]
Is anybody working on this at all?

**Comment by moollaza** [comment]
@runical no one has mentioned any plans to fix this -- if you're interested in updating this Instant Answer, we'd really appreciate it!

**Comment by runical** [comment]
I'll take a look, but I'm a complete noob when it comes to this kind of thing. Any documentation you can point me to?

**Comment by runical** [comment]
I'm probably blind, but I can't for the life of me find the GitManual plugin. Where is it hidden?

I did find a file in UNCLEAN (parse_git), but I can't make heads or tails out of that one.

**Comment by rugk** [comment]
I think https://git-scm.com/docs/... is the best choice as i8t is the official git documentation/website AFAIK.

**Comment by samskeller** [comment]
Hey @runical,  if you're not still working on this I'd like to take a stab at it.

@moollaza I too am having a tough time figuring out where this answer is currently populated from... can you point me in the right direction?

**Comment by runical** [comment]
@samskeller Go right ahead. I still haven't found out how it is supposed to work.

**Comment by moollaza** [comment]
@andrey-p @samskeller @runical 

apologies -- I didn't realize this was an internal Fathead. You're correct that the source isn't here. We'll have to update internally or open-source this one if the code is still around.

@jdorweiler can we easily update the link? Or open source this one?

**Comment by jdorweiler** [comment]
@samskeller do you want to make a new parser for https://git-scm.com/docs/?

**Comment by samskeller** [comment]
@jdorweiler sure! would that just involve creating the "share/fathead/fathead_name/parse.xx" that's mentioned in [this Fathead tutorial](http://docs.duckduckhack.com/resources/fathead-overview.html) or would i just write a whole new Fathead that would replace the internal one?

**Comment by jdorweiler** [comment]
@samskeller yep you could just replace the current source since it's gone. 
You will need a new fetch script to download the data and a parse script to generate the output file.

**Comment by samskeller** [comment]
@jdorweiler great, I'll get started on this. thanks!

**Comment by samskeller** [comment]
@jdorweiler not sure if you have seen this yet, but just letting you know I submitted a pull request for the new git manual Fathead
