### ISSUE TITLE
ThePokemonEncyclopedia: Multiple "Read More" Sources

### ISSUE THREAD

**Issue by Geo1088** [duckduckgo/zeroclickinfo-fathead#150]
Hello!

First, I'd like to say thanks for this add-on. It's really useful, especially for quickly looking up a pokémon's type in battle. I would like to suggest that there be more options for the "Read More"/"More Info" links. For example, Umbreon's card only shows a link to the Pokémon Wikia, but it could link to other sources as well, such as Bulbapedia. (I'm not sure if it already does this for other pokémon or if different sources already show up, sorry about that if I'm wrong.) It's not a major issue, but it would be nice for people who prefer a certain source (like me :stuck_out_tongue:)
## Thanks a ton!

IA Page:  http://duck.co/ia/view/the_pokemon_encyclopedia

**Comment by moollaza** [comment]
@Geo1088 Fatheads only link to the original source that was used to produce the answer. What you're asking for isn't currently possible given the way Fatheads build their "More at" link.

Regardless, DuckDuckHack is now in maintenance mode and during this time we are only accepting issues for critical bug reports.

This will be marked as tolerated and closed.

**Comment by Geo1088** [comment]
I see, thanks for the explanation.
