### ISSUE TITLE
GitHub: Zeroclick seems to prioritise repositories strangely

### ISSUE THREAD

**Issue by lucideer** [duckduckgo/zeroclickinfo-fathead#158]
Example: Zeroclick for https://duckduckgo.com/?q=github+ranger should really point to https://github.com/hut/ranger rather than https://github.com/ralesi/ranger.el

(I'm sure ralesi's repo is good, but I would imagine ZeroClick should try to present somewhat "canonical" results based on notability, etc.?)

Note: the DDG search results has hut's repo at the top.

------
IA Page:  http://duck.co/ia/view/git_hub

**Comment by moollaza** [comment]
@jdorweiler seems like this may be due to the Fathead going stale? Can we re-build the info?

**Comment by jdorweiler** [comment]
@moollaza this is the spice.

**Comment by moollaza** [comment]
@jdorweiler I believe @lucideer is referring to the `About` tab pointing to `ralesi/ranger` instead of the more popular `hut/ranger` -- the Spice orders `hut` as the first because they're ordered by # of stars (which hut has many more of)

**Comment by moollaza** [comment]
![github_ranger__software__at_duckduckgo](https://cloud.githubusercontent.com/assets/873785/11316237/96a134fc-8fcf-11e5-95fa-c94cb06f9961.png)

**Comment by jdorweiler** [comment]
@moollaza ok, thanks.  @mrshu knows more about how the github fathead works.

**Comment by lucideer** [comment]
Thanks @moolaza - I would've clarified myself but I didn't quite understand that the spice was a different : this is the `Software` tab yeah?

Another thing to note, the `Software` tab shows ralesi (in third) with a different more up-to-date title: "ranger.el" instead of just "ranger" so I guess this could indicate the info in the `About` tab is stale as suggested

**Comment by moollaza** [comment]
@lucideer yes the "Software" tab is powered by the GitHub Spice which uses the GitHub API (so it's always up to date)

The "About" is powered by the Fathead, which is a DB, in this case, containing the names of all (or most) GH repos, and the descriptions. The Fathead is more prone to being outdated though, but can detect exact matches on existing repo names.

**Comment by mrshu** [comment]
Hi @lucideer,

I am sorry for the late reply and your confusion. What @moollaza wrote above is correct, the "About" tab is powered by an internal Fathead that desperately needed an update.

The query you mentioned above currently shows the GitHub repository you suggested it should.

**Comment by moollaza** [comment]
Sounds like we can close this then! 

@mrshu thanks for updating the Fathead :+1:
