### ISSUE TITLE
Perl6Doc: Ignore inheritance for method search

### ISSUE THREAD

**Issue by xfix** [duckduckgo/zeroclickinfo-fathead#161]
This is a reminder to myself.

Query like `Str.clone` should point to `Mu.clone`. Query like `perl6 clone` shouldn't show a `clone` method for every single object in a language, but just `Mu.clone` and possibly objects that override it (if there are any).

https://duck.co/ia/view/perl6doc

**Comment by pjhampton** [comment]
Hey @xfix. I've assigned this to based on your first statement. Let me know if you aren't working on this so I can open it back up. 👍
