### ISSUE TITLE
Country languages: Doesn't trigger for some languages

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-fathead#163]
Sometimes this IA is triggered but sometimes the standard Wikipedia fathead is triggered instead, or even no IA at all. For example...

Works (triggers country languages IA):
https://duckduckgo.com/?q=afghanistan+language

Triggers Wikipedia fathead IA:
https://duckduckgo.com/?q=language+in+brazil
https://duckduckgo.com/?q=mexico+language
https://duckduckgo.com/?q=language+in+mexico

Doesn't trigger any IA:
https://duckduckgo.com/?q=brazil+language

---

IA Page: https://duck.co/ia/view/country_languages

**Comment by MrTimscampi** [comment]
Belgium triggers the Wikipedia entry instead of the country language: https://duckduckgo.com/?q=belgium+language

**Comment by tagawa** [comment]
Sri Lanka is another example of no triggering:
https://duckduckgo.com/?q=language+of+sri+lanka&t=ffab
although the data is in the source CIA page:
https://www.cia.gov/library/publications/the-world-factbook/geos/ce.html

**Comment by borisov87** [comment]
Bulgarian is other example. Triggers the Wikipedia.
https://duckduckgo.com/?q=bulgarian+language&ia=web
