### ISSUE TITLE
HelloWorld: 

### ISSUE THREAD

**Issue by CristianoNicolaFerreira** [duckduckgo/zeroclickinfo-fathead#164]
@jperla 

------
IA Page:  http://duck.co/ia/view/hello_world

**Comment by moollaza** [comment]
Hey @CristianoNicolaFerreira welcome to DuckDuckHack!

Are you interested in contributing?

**Comment by CristianoNicolaFerreira** [comment]
Thank you @moollaza!
Yes, I'm interested in contributing
