### ISSUE TITLE
GitHub: markdown cheat sheet

### ISSUE THREAD

**Issue by mischk** [duckduckgo/zeroclickinfo-fathead#167]
If you ask ddg for markdown cheat sheet, instant answer provides a link to a github page with a markdown cheat sheet. Think it should provide the cheat sheet instead.

------
IA Page:  http://duck.co/ia/view/git_hub

**Comment by moollaza** [comment]
@mischk thanks for this! I'll move this to the Goodies Repo where Cheat Sheets live
