### ISSUE TITLE
Can I Use: Update to add Edge Browser

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#169]
For example, Edge now supports partial support for CSS Filter Effects, but it doesn't say that in our IA: https://duckduckgo.com/?q=can+i+use+CSS+Filter+Effects&t=ffab&ia=about&iax=1

This might need an update.

**Comment by jagtalon** [comment]
+ @jdorweiler @moollaza

**Comment by moollaza** [comment]
There was a developer the was interested in updating it...

The data is now hosted on GitHub in a JSON file, which would make it very easy to re-implement a FatHead using that as the source, instead of scraping the site.
