### ISSUE TITLE
Can I Use: Add other aliases for CSS filters

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#171]
It triggers on "can i use css filters" and "can i use css filter effects" but not on "can i use css filter" or "can i use css filter effect"

See https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/share/fathead/caniuse/output.txt#L370...L372

https://duck.co/ia/view/caniuse

**Comment by alexnewmannn** [comment]
Hey, I've picked this up. The code should be done, I have a test failing but just reset to master branch and appears it's failing there too, not even sure if the module has tests. It's late now so will be checking this tomorrow and will have a PR then too. 👍

**Comment by pjhampton** [comment]
Hey @alexnewmannn, sorry for the delayed response. what is the failing test? Is it regarding coverage?

**Comment by alexnewmannn** [comment]
no worries mate, yeh it is. looks like there isn't any tests for this
particular module at all at the minute.

**Comment by pjhampton** [comment]
That's ok, don't worry about the coverage. We can add that at another stage. Push it up and we can review 😄

**Comment by alexnewmannn** [comment]
Ill try do it tonight, havent been able to get on my personal computer the last week! :)

**Comment by alexnewmannn** [comment]
@pjhampton there we go https://github.com/duckduckgo/zeroclickinfo-fathead/pull/807, better late than never 😅

**Comment by pjhampton** [comment]
haha no problem! Thanks so much @alexnewmannn 
You rock 🤘
