### ISSUE TITLE
Abbreviations: shouldn't trigger on "."

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-fathead#181]
@stands4 

<img width="977" alt="screen shot 2016-02-27 at 9 49 08 am" src="https://cloud.githubusercontent.com/assets/126358/13373501/6d1bbb10-dd37-11e5-9115-7daec0d617e5.png">

---

IA Page:  http://duck.co/ia/view/abbreviations

**Comment by GuiltyDolphin** [comment]
@bsstoner Why not? There's no other results and it is definitely an interesting surprise!

**Comment by bsstoner** [comment]
I agree it is a cool surprise for technical users. I think it's confusing for mainstream users that have no idea what UNIX or DOS are. Most searches for this query are probably a typo and if we're going to show something for this query it should be more broadly applicable.

**Comment by GuiltyDolphin** [comment]
@bsstoner Humm... Having a look at https://duckduckgo.com/?q=..&t=ffab perhaps we should remove it. If that doesn't trigger it there may be disappointment for excited users trying other queries after having done `.`.

**Comment by bsstoner** [comment]
Yea, good point, there seems to be an internal bug here, I will open a task to look into it. If you switch to Germany region it returns organic links.

![screen shot 2016-03-04 at 2 38 33 pm](https://cloud.githubusercontent.com/assets/126358/13538149/cfb6bc96-e216-11e5-9795-5fc5ad10e0d6.png)

**Comment by stands4** [comment]
Hmm... looks like when you're adding the keyword 'abbreviation' after the
two dots (..) it does return a result back:

https://duckduckgo.com/?q=..+abbreviation&t=ffab&ia=about

Not sure why it's not required for '.' though...

[image: Inline image 1]

**Comment by GuiltyDolphin** [comment]
@stands4 Yeah, I'd expect the explicit query to trigger - but I think something weird is just going on with `.`.

**Comment by GuiltyDolphin** [comment]
@bsstoner Any update on this? I'm still getting no results from `.` (unless I have a region active).
