### ISSUE TITLE
Wikipedia: Omitting text in summary.

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#183]
The summary looks like this for https://duckduckgo.com/?q=2010+JL88&t=ffab&ia=about

![screenshot from 2016-03-02 17 08 55](https://cloud.githubusercontent.com/assets/8598426/13468277/cd056caa-e099-11e5-8cf9-4d2cae94b32f.png)

But on the Wikipedia page it has:

![screenshot from 2016-03-02 17 09 07](https://cloud.githubusercontent.com/assets/8598426/13468315/edb87726-e099-11e5-94ef-39db3c30feee.png)

So it is just saying `passed from Earth` instead of giving the distance - which doesn't read very well!

**Comment by tagawa** [comment]
Thanks for reporting @GuiltyDolphin. Looks like it's just ignoring the distance units (although it's fine with time units, e.g. seconds).

**Comment by mrshu** [comment]
Thanks @GuiltyDolphin and @tagawa, I'll take a look but from the first glance this seems to be related to strange Wikipedia processing constructs (a template called `convert` which converts `{{convert|0.00257|AU|km mi|abbr=on|lk=on}}` to `0.00257 AU (384,000 km; 239,000 mi)`) so I am not sure if I can materially fix anything here.

Will keep you (and this issue) posted for sure.

**Comment by pjhampton** [comment]
I believe this IA has changed quite a bit since this issue was created. Closing for now 👍
