### ISSUE TITLE
Python: Uses Python 2 docs by default, should use Python 3 instead

### ISSUE THREAD

**Issue by chdsbd** [duckduckgo/zeroclickinfo-fathead#184]
I was thinking that since Python 3.5 is the most current stable version of Python, Python 3.5 docs should be returned instead of the archaic Python 2 docs.

------
IA Page:  http://duck.co/ia/view/python

**Comment by ChristianBagley** [comment]
This is tough. Although Python 3.5 is the most current and stable release, Python 2.7 still dominates much of the Python code out there, and 2.7 seems to be version most [searched](http://jmp.sh/dbN34nu) for, compared to 3.4 and 3.5.

**Comment by jdorweiler** [comment]
We could have both.  Someone would need to create a Python 3 docs fathead though.

**Comment by chdsbd** [comment]
Why was this closed? This is still an unresolved issue.

**Comment by jdorweiler** [comment]
Can you suggest a source for Python 3 docs?

**Comment by chdsbd** [comment]
I can't seem to find the fathead for Python, but if you use the Python docs website, changing from Python 2 to Python 3 docs is a matter of changing a number in the url. 
https://docs.python.org/2/library/functions.html to https://docs.python.org/3/library/functions.html

I figure that it would likely be pretty easy to change the fathead, wherever that is stored, so that it would return the Python 3 docs.

**Comment by jdorweiler** [comment]
@chdsbd thanks, I was just thinking that

The old parser for the Python 2 docs is here
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/UNCLEAN/parse_python.py

It looks like it may have even been set up to parse both Python 2 and Python 3 docs. 
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/UNCLEAN/parse_python.py

**Comment by jdorweiler** [comment]
It might be easier to just write a new parser from scratch though.

**Comment by jdorweiler** [comment]
@chdsbd we switched over to python3 as the default now. 

@gerlachry added an infobox in #285 linking the the python2 version in the case that it differs from the python3 version. 
https://duckduckgo.com/35/eval?iax=1&ia=about
