### ISSUE TITLE
Use HTTPS for international Wikipedias

### ISSUE THREAD

**Issue by splewako** [duckduckgo/zeroclickinfo-fathead#185]
When other then en.wikipedia.org result is showed as instant answer, HTTP instead of HTTPS is used for article title and more at Wikipedia (ab) links.

**Comment by tagawa** [comment]
Thanks for reporting @splewako - looks like something we can address internally.

**Comment by mrshu** [comment]
Thanks @splewako and @tagawa, I'll take a look.

**Comment by mrshu** [comment]
@splewako @tagawa Wikipedia now uses HTTPS by default, it is no longer possible to get a HTTP site. This also means that international Wikipedias will use HTTPS by default now.

I am therefore closing this. Thanks again for reporting!

**Comment by splewako** [comment]
@mrshu: wrong, DDG users are directed to HTTP site that redirects… so not fixed at all.

**Comment by mrshu** [comment]
@splewako Ok, can you please elaborate how is that wrong?

**Comment by edgesince84** [comment]
Can you give us an example query @splewako?

**Comment by splewako** [comment]
@edgesince84 like https://duckduckgo.com/?q=warszawa&t=h_&ia=about?

> can you please elaborate how is that wrong?

Seriously? Ignoring speed, security, integrity and other things, [301 redirect means that one should use different URL](https://en.wikipedia.org/wiki/HTTP_301).

Besides that, I don't see the reason to use fake (now) URLs for Wikipedia (non en-US) articles and HTTPS for en.wikipedia.org.

**Comment by pjhampton** [comment]
I believe this is now the case 👍
