### ISSUE TITLE
Testing...

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#186]
Just a test...

...aand now I'm mentioning @zachthompson

**Comment by GuiltyDolphin** [comment]
@moollaza Did you do this remotely?

**Comment by moollaza** [comment]
@GuiltyDolphin did it on GH. Testing if modifying a message with an @mention sends a notification to the user -- and it does :)

**Comment by GuiltyDolphin** [comment]
@moollaza Ah, alrighty! It also works for issue/PR references as well :smile:
