### ISSUE TITLE
HTTP Status Codes: link to direct http code

### ISSUE THREAD

**Issue by nobe4** [duckduckgo/zeroclickinfo-fathead#193]
Hi,
Is there a way to add a direct link to the HTTP status on the fathead ?
On Wikipedia, each status has an id on the HTML element, so I think this can be as simple as adding `#200` at the end of the link url.

(also, I would like to contribute, maybe even starting with this, how can I ?)

Thanks,

---

IA Page:  http://duck.co/ia/view/httpstatus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by gsquire** [comment]
Is there an existing fathead for HTTP status codes? I also want to add this to DDG as an instant answer. I tried looking through old issues but couldn't find any indication of a PR or other links. I would be happy to help write it too.

**Comment by nobe4** [comment]
Yup: https://duckduckgo.com/?q=http+code+406&ia=about

As you can see on the screenshot, the **406** does not link back to the specific 406 element in the wikipedia page.
<img width="567" alt="screen shot 2016-04-11 at 18 19 08" src="https://cloud.githubusercontent.com/assets/2452791/14435889/eac33bd6-0011-11e6-9b25-960918ea5506.png">

**Comment by jdorweiler** [comment]
@nobe4 I'm not sure if the code to generate this data still works but this is where it is https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/UNCLEAN/parse_httpcode.py

You could start with that or do your own fathead from scratch if you want.

**Comment by jdorweiler** [comment]
Here is the section on fatheads from our docs. http://docs.duckduckhack.com/resources/fathead-overview.html

Let me know if you have any questions.

**Comment by nobe4** [comment]
@jdorweiler: thanks, I'll have a look tonight. 👍
