### ISSUE TITLE
Java: Doesn't trigger on some terms

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-fathead#201]
For example, `java threadlocal` doesn't trigger the instant answer (but `java accessmode` does).

Reported in the [Java subreddit](https://www.reddit.com/r/java/comments/4gqudt/improving_duckduckgos_javarelated_searches/d2k1awc).   

------
IA Page:  http://duck.co/ia/view/java 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html):

**Comment by jonk1993** [comment]
It seems there are a bunch of terms that do not trigger the IA, `java ArrayList`, `java PriorityQueue`, `java HashMap` to name a few obvious ones. I'd like to help with this but what do you think is a good scope for addressing this issue? In addition to triggers, I think it'd also be handy to include some sample methods in the IA box under the description. What are your thoughts @tagawa?

**Comment by tagawa** [comment]
Thanks for the offer @jonk1993. I'm not really familiar with our "Fathead" type of Instant Answers so I'll have to ask my colleague.
@moollaza - what's the easiest way to add more triggers for this Fathead? The code is here by the way: https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/java

**Comment by moollaza** [comment]
@tagawa @jonk1993 if the source contains results for those, then it may be as simple as us re-running the parsing script to regenerate the output.txt file.

However if the current parser isn't picking those up, then the Fathead code needs updating.

If the source doesn't have that data available, then a new source needs to be chosen and a new Fathead written to build the desired output.txt

**Comment by jonk1993** [comment]
Ok, I'll do some investigation on the Fathead source/parsing.

**Comment by lernae** [comment]
I'm looking into this.
