### ISSUE TITLE
C++   Reference Docs:

### ISSUE THREAD

**Issue by cquike** [duckduckgo/zeroclickinfo-fathead#203]
I would like  the following query to be part of IA for C++:

cpp begin valarray

---

IA Page:  http://duck.co/ia/view/cppreference_doc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mylainos

**Comment by Mylainos** [comment]
Hi @cquike!
Sorry for the delay, I will look at this tomorrow.

**Comment by Mylainos** [comment]
I've found why it don't work. In the archive file downloaded from http://upload.cppreference.com the file index-functions-cpp.xml have this:
```
<class name="std::valarray" link="cpp/numeric/valarray">
    <!-- todo -->
</class>
```
But should have something like this:
```
<class name="std::valarray" link="cpp/numeric/valarray">
...
        <function name="begin"/>
...
</class>
```
I've contacted them.

**Comment by tagawa** [comment]
Thanks for doing that @Mylainos. Hopefully they'll update the file.

**Comment by alohaas** [comment]
Hey @Mylainos any updates from cppreference?

**Comment by edgesince84** [comment]
hey @Mylainos I wanted to see if you still planned on finishing this up - we really appreciate your contribution and want to see this go live. We're closing up old PRs and issues in the next week, so let me know if I should leave this open for you!

If you'd rather work on something new, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by p12tic** [comment]
I've opened an issue https://github.com/p12tic/cppreference-doc/issues/45 to track the progress of the problem on cppreference-doc repo. I think this issue should be closed as there's nothing to be done on duckduckgo side.

**Comment by sahildua2305** [comment]
Thanks @p12tic for moving issue there.
