### ISSUE TITLE
New IA: POSIX   Reference Docs

### ISSUE THREAD

**Issue by cquike** [duckduckgo/zeroclickinfo-fathead#204]
It would be great of DDG would give IA for POSIX interfaces.
 Querying something like "posix fork" could get some IA from the opengroup (for this call it would be http://pubs.opengroup.org/onlinepubs/000095399/functions/fork.html).

 Thank you!

**Comment by Mylainos** [comment]
This is not related to the cpp reference IA. Maybe someone in @duckduckgo/duckduckhack-contributors would like to create a new IA.

**Comment by zachthompson** [comment]
Like the suggestion @cquike. Thanks for checking it out @Mylainos.

**Comment by kimthomas109** [comment]
I'm a first-time contributor, I would love to help out with this IA!

**Comment by hchienjo** [comment]
I am interested in helping out in making this.

**Comment by jdorweiler** [comment]
Here's the relevant part of our docs 
http://docs.duckduckhack.com/resources/fathead-overview.html
