### ISSUE TITLE
Wikipedia: Omits part of chemical formulas in paranthesis

### ISSUE THREAD

**Issue by leftshift** [duckduckgo/zeroclickinfo-fathead#205]
A good example for this is a search for Acetone:
![Screenshot](https://cloud.githubusercontent.com/assets/1733162/15097698/7467dea6-1524-11e6-8af2-29dec2eafa00.png)
The ![bildschirmfoto vom 2016-05-08 13 58 01](https://cloud.githubusercontent.com/assets/1733162/15097715/f0de41c8-1524-11e6-934b-30fd2a85b48f.png) from Wikipedia becomes "2CO" which clearly isn't correct and completely changes the meaning.

I'm unsure about the best way to handle this, looking for subscript numbers might be a possible way of identifying chemical formulas, but it's a bit of a hack…

---

IA Page:  http://duck.co/ia/view/wikipedia_fathead 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by edgesince84** [comment]
thanks for bringing this to our attention @leftshift.

This is something we're going to address internally, so hopefully it'll be fixed soon.

In the meantime, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by pjhampton** [comment]
Passing comments to internal team.
