### ISSUE TITLE
Wikipedia: Inconsistent triggering for regional indicator symbol pairs

### ISSUE THREAD

**Issue by scribblemaniac** [duckduckgo/zeroclickinfo-fathead#206]
When searching for unicode [regional indicator pairs](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol), sometimes the corresponding wikipedia page comes up and sometimes it doesn't. For example, the Flag of Spain wikipedia page shows up when you [search for 🇪🇸](https://duckduckgo.com/?q=🇪🇸), but the Flag of Canada page will not show up when you [search for 🇨🇦](https://duckduckgo.com/?q=%F0%9F%87%A8%F0%9F%87%A6), despite both being redirected by Wikipedia:
- https://en.wikipedia.org/wiki/🇪🇸
- https://en.wikipedia.org/wiki/🇨🇦

**Comment by mrshu** [comment]
@scribblemaniac interesting issue. 

For me personally its peculiarity is amplified by the fact that GitHub also seems to replace 🇪🇸 with the flag of Spain but ignores 🇨🇦.

Thanks for reporting it, will look into this a bit more closely and get back to you.
