### ISSUE TITLE
C++ reference: Missing parentheses in code snippets on some queries

### ISSUE THREAD

**Issue by p12tic** [duckduckgo/zeroclickinfo-fathead#208]
The code snippets returned by e.g. https://duckduckgo.com/?q=std%3A%3Avector%3A%3Abegin lack parentheses.
Current output:
`iterator begin;`
`const_iterator begin const;`

Expected output:
`iterator begin();`
`const_iterator begin() const;`

According to https://github.com/duckduckgo/zeroclickinfo-fathead/pull/177#issuecomment-187383835 the issue is not related with the cppreference plugin itself.

**Comment by pjhampton** [comment]
Hey! Thanks for reporting! This is an internal issue that is being solved I believe 👍
