### ISSUE TITLE
IOS: No content for IA query

### ISSUE THREAD

**Issue by stevenmg** [duckduckgo/zeroclickinfo-fathead#211]
When searching for the stringByAppendingPathComponent function the iOS IA correctly appears, but it is empty.

https://duckduckgo.com/?q=stringByAppendingPathComponent&t=ffcm&ia=about

![ios](https://cloud.githubusercontent.com/assets/3642158/15477643/b21ba73a-20e3-11e6-8133-23db774bfa9c.PNG)

------
IA Page:  http://duck.co/ia/view/ios 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by edgesince84** [comment]
Thanks for finding this, Steve.  I'll try to find someone on the staff to address this.

**Comment by edgesince84** [comment]
This seems to be a really old bug, so we are working on a fix to go out in our next release in a week or so.  I'll update here when we do.  Thanks again, Steve!

**Comment by tagawa** [comment]
This seems to be fixed now so closing. Thanks for reporting @stevenmg!

**Comment by stevenmg** [comment]
Awesome! Thanks guys.
