### ISSUE TITLE
WowWiki: Use WowPedia as a source instead

### ISSUE THREAD

**Issue by McIntireEvan** [duckduckgo/zeroclickinfo-fathead#213]
Among the WoW community, WowPedia (http://wow.gamepedia.com/) is generally considered the more up-to-date, more accurate source, and Blizzard has officially linked to it as a community site.

---

IA Page:  http://duck.co/ia/view/wow_wiki 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
@McIntireEvan thanks for the suggestion!

We actually previously tried building a Fathead from a Gamepedia subdomain and were quickly blocked. They have a ton of great content that we'd like to share with our users though so I think it would be good to reach out to them and ask if they can help us out here. Ideally we can use their data for several Fatheads!

As a WowPedia community member, would you be interested in reaching out to WowPedia (or Gamepedia) and asking if we can scrape their data? Or even better could they give us a data dump to scrape, so we're not hitting their servers?

**Comment by 122131** [comment]
@moollaza What about making a Spice based on Gamepedia API (MediaWiki API)? I previously tried it but I gave up because the pages were to much complex for me. 😕

**Comment by moollaza** [comment]
@122131Fatheads are usually the ideal solution for Wiki content. A Spice would require a trigger word (or multiple) whereas a Fathead can trigger on the specific terms we index. Fatheads are also a little faster because they don't need to wait for an API response.

Depending on the API available a Spice could work, if there's a certain subset of queries that contain common trigger words.

**Comment by pjhampton** [comment]
Hey @McIntireEvan!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
