### ISSUE TITLE
NodejsRef: Data URL gives 404

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-fathead#218]
The data URL mentioned here in the `fetch.sh` gives `404`.
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/nodejs_ref/fetch.sh#L4

Mentioned Data URL - http://nodejs.org/api/all.json

**Comment by edgesince84** [comment]
thanks, Sahil

**Comment by moollaza** [comment]
@sahildua2305 looks like it requires `https` -- mind updating?

**Comment by sahildua2305** [comment]
Done at #232
