### ISSUE TITLE
RedisCommands: Parsing code needs update

### ISSUE THREAD

**Issue by sahildua2305** [duckduckgo/zeroclickinfo-fathead#219]
HTML code fetched is of the following format:

```
<li data-group='string' data-name='append'>
  <a href='/commands/append'>
    <span class='command'>
      APPEND
      <span class='args'>
        key
        value
      </span>
    </span>
    <span class='summary'>Append a value to a key</span>
  </a>
</li>
```

And parsing code finds all the elements with class name `command` and then searches for `<a href=""></a>` in all those elements (which of course isn't present). And hence parsing returns empty data and hence empty `output.txt`.

Probably there was some recent update in website's HTML.

**Comment by edgesince84** [comment]
....aaaaaand thank you again!

**Comment by sahildua2305** [comment]
@edgesince84 Can you please confirm this issue so that I can start working on fixing this?

**Comment by moollaza** [comment]
@sahildua2305 it looks like you've already confirmed it?

We don't continuously run the Fathead scripts so it's not currently an issue for us, but if anyone notices the Fathead is out of date, the next time we run the script we're clearly going to have issues. Please go ahead an fix!

**Comment by pjhampton** [comment]
Hey @sahildua2305 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.

**Comment by sahildua2305** [comment]
@pjhampton, this is actually a critical bug. Check comment above

**Comment by moollaza** [comment]
@sahildua2305 the Fathead is currently offline, and is likely going to stay that way (given we're in maintenance mode). Therefore, I agree this should be considered non-essential now.
