### ISSUE TITLE
IOS: fires on keyword "recipient"

### ISSUE THREAD

**Issue by sekhavati** [duckduckgo/zeroclickinfo-fathead#223]
Today I was using DDG and searched for ["recipient"](https://duckduckgo.com/?q=recipient) and was surprised to see this IA pop up. Feels like its relevancy checking could be better. Also the title of the tab ("About") seems rather generic.

---

IA Page:  http://duck.co/ia/view/ios 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
Looks like this is fixed?
