### ISSUE TITLE
Wikipedia: some extracts have numerical information stripped

### ISSUE THREAD

**Issue by ncaunt** [duckduckgo/zeroclickinfo-fathead#224]
Some extracts from Wikipedia articles have numerical (distance) information stripped, and it doesn't look intentional.

One such example I've seen is "Autoroutes of France", as per the screenshots below. The text "11,882 km (7,383 mi)" is stripped.

Original:
![image](https://cloud.githubusercontent.com/assets/4837176/16261711/7a9163e8-3864-11e6-97a9-56f1b5bf6c02.png)
DuckDuckGo:
![image](https://cloud.githubusercontent.com/assets/4837176/16261743/9d0d8596-3864-11e6-8231-cacfb87c76c1.png)

The same happens for "Chambourcy" and the stripped text has the same pattern: a number with a unit followed by another number and unit in parentheses.

---

IA Page:  http://duck.co/ia/view/wikipedia_fathead 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
@mrshu can you please investigate this?
