### ISSUE TITLE
New Instant Answer: MDN CSS Fathead

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#226]
We previously had a CSS Fathead, but it was internal, and eventually become very outdated.

We need a new CSS Fathead and MDN is an excellent data source. It has a [CSS Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference) we can easily crawl to build a Fathead.

Improving our CSS search experience is also directly in-line with our [Programming Mission](https://duck.co/blog/post/297/help-for-programmers), so this would be a big win!

@duckduckgo/duckduckhack-contributors is anyone out there interested in writing a CSS Fathead?

This doesn't need to be written in Perl (though we'd prefer it 😉 ) -- Python, Ruby, and other well-known languages are acceptable.

There is an existing MDN JavaScript Fathead (written in Python) which could server as a starting point for this Instant Answer.

----

As well, it looks like [CSS-Tricks.com](https://css-tricks.com) has coverage of useful [Snippets](https://css-tricks.com/snippets/) and [more](https://css-tricks.com/almanac/). We could very likely create a Fathead for their snippets and other data. It would be good to namespace these Instant Answers  accordingly: `DDG::Fathead::CSS::MDN`, `DDG::Fathead::CSS::CssTricks`

**Comment by pjhampton** [comment]
If there is no uptake on this I can take it forward... put anybody else more keen or more time please feel free 😄

**Comment by hchienjo** [comment]
I am interested.

**Comment by moollaza** [comment]
@pjhampton, @hchienjo thanks for the offering to help!

@hchienjo do you need help getting started?

**Comment by hchienjo** [comment]
Yes I do.

**Comment by hchienjo** [comment]
If you can point out a similar instant answer I would be pretty well off.

**Comment by gaulrobe** [comment]
@hchienjo the document here is really helpful! http://docs.duckduckhack.com/resources/fathead-overview.html

As @moollaza pointed out a good one to start looking through is https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdnjs

Let us know if you have any additional questions! :smile:

**Comment by hchienjo** [comment]
Great. Thanks. Will take a look first thing in the morning. It's 0233 hours right now on my side.

**Comment by hchienjo** [comment]
Am I free to use such modules as Mojo::* especially Mojo::DOM and Mojo::UserAgent during fetching and parsing of html as I am more comfortable with it. Will such modules pose a problem during further deployment into production? @moollaza @pjhampton  @gaulrobe

**Comment by gaulrobe** [comment]
@hchienjo other Fatheads (such as https://github.com/duckduckgo/zeroclickinfo-fathead/blob/85911ef28b2b7c00eeedb2e2219910a7f7e90a62/lib/fathead/duckduckhack/parseDocs.pl) are using `Mojo::DOM` so I don't think that'll be an issue... unless there is an issue that I am not aware of. :)

**Comment by hchienjo** [comment]
Wonderful. Thanks.

**Comment by hchienjo** [comment]
I am designing the extractor and I need a little help. From here [MDN CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference), do I extract only the _KEYWORDS INDEX_ only or I even include data from _SELECTORS_? Thanks.

**Comment by gaulrobe** [comment]
@hchienjo I think there is a lot of value having both of those in this IA!

**Comment by hchienjo** [comment]
I need a little clarification, for instance, the [:article](https://developer.mozilla.org/en-US/docs/Web/CSS/:active] element page, do I extract the Summary as well as the Example code snippets (the CSS and the HTML inclusive)?

**Comment by hchienjo** [comment]
I need a little clarification, for instance, the [:article](https://developer.mozilla.org/en-US/docs/Web/CSS/:active] element page, do I extract the Summary as well as the Example code snippets (the CSS and the HTML inclusive)?

**Comment by hchienjo** [comment]
Meanwhile, I have reached [here](https://github.com/hchienjo/zeroclickinfo-fathead/tree/mdn_css_devel/lib/fathead/mdn_css) in the actual coding.
@moollaza  @pjhampton  @gaulrobe

**Comment by sahildua2305** [comment]
@hchienjo Since you have already started working on it, I think you should submit a PR so that you can ask for help directly there without anyone having to go to your repo:branch for feedback :)

**Comment by hchienjo** [comment]
@sahildua2305  [Done](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/231)
Looking forward to guidance from all you guys.

**Comment by moollaza** [comment]
@hchienjo this is looking awesome! 💯 

Thanks a lot for writing this in Perl and submitting a PR so quickly!

@jdorweiler will deploy this to beta for me and then we can start testing it and give you some feedback 👍

**Comment by hchienjo** [comment]
@moollaza it is still incomplete. Working on the parsing.

**Comment by hchienjo** [comment]
Submitted PR so that in case I run into pronlems I can be guided along.
