### ISSUE TITLE
PHP: Instead of co.de why results are not from PHP manual 

### ISSUE THREAD

**Issue by rosorrentino** [duckduckgo/zeroclickinfo-fathead#229]
I am not sure why results are going to co.de instead of http://php.net/manual (that is the official and therefore preferable) 

------
IA Page:  http://duck.co/ia/view/php 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by sahildua2305** [comment]
@rosorrentino The current results are from an internal fathead that's outdated.

The new one is being developed using http://php.net/manual here - #221

**Comment by edgesince84** [comment]
thanks for answering that one @sahildua2305  - @rosorrentino thanks for the suggestion, source recommendations are always welcome!
