### ISSUE TITLE
GitManual: show short description of subcommands

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-fathead#230]
Could we (also) show short description of **git subcommands** on IA results? This could be more useful as a quick reference. 

---

IA Page:  http://duck.co/ia/view/git_manual 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @samskeller

**Comment by samskeller** [comment]
Sorry I didn't respond to this earlier, @NaveenKarippai! What do you mean by subcommands? Can you give an example of what you'd like to see?

**Comment by pjhampton** [comment]
Hey all

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
