### ISSUE TITLE
Python: Create New NumPy Fathead

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#233]
# Create a new NumPy Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the 
`output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: http://www.numpy.org/

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by karanchahal** [comment]
I'm interested in solving this issue, can someone explain to me what exactly needs to be done ?

**Comment by moollaza** [comment]
> can someone explain to me what exactly needs to be done ?

@karanchahal it looks like we should create a [Fathead Instant Answer](https://docs.duckduckhack.com/resources/fathead-overview.html) for the Numpy documentation.

This means we'll need to write a parser for the Numpy docs. It looks like the ideal entry point would be the [index](http://docs.scipy.org/doc/numpy/genindex.html)

We can iterate over all the entries there and produce a Fathead that provides information for all the numpy methods. 

That way a search like https://duckduckgo.com/?q=numpy+vsplit would show the information here http://docs.scipy.org/doc/numpy/reference/generated/numpy.vsplit.html 

Are you familiar with Python and Numpy?

**Comment by karanchahal** [comment]
Yes,let me try to work on this issue.

**Comment by mr-karan** [comment]
Are you still working on this @karanchahal ?

**Comment by karanchahal** [comment]
No , I am presently pretty busy. You are more than welcome to try to tackle this issue. :)

**Comment by ashishbhate** [comment]
Quick update - I'm still working on this. I've made quite a bit of progress. I can only work on this issue a couple hours every weekend, but I think I'll be done by next weekend.
