### ISSUE TITLE
Python: Create new Matplotlib Fathead

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#235]
# Create a new Matplotlib Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: http://matplotlib.org/examples/index.html 

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @{Language Leader Handle} for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by pbronez** [comment]
I'll take a look at this!

**Comment by moollaza** [comment]
@pbronez I've updated the task description with some steps to take.

If you're still interested please get started by creating an IA Page and leaving the link here 👍 

Thanks!

**Comment by pbronez** [comment]
@moollaza I created an [IA page](https://duck.co/ia/view/matplotlib) when I first looked at it a few weeks ago. During that process I accidentally created a [duplicate IA page](https://duck.co/ia/view/matplotlib_acorr_matplotlib_filled_step) that should be removed.

I got a codio environment up and started working on this, but ran into a few issues.

First, it's not clear to me that the [Examples](http://matplotlib.org/examples/index.html) are the best content to supply via a fathead. The [matplotlib documentation](http://matplotlib.org/1.5.3/contents.html) has a number of more explicit resources that might be more useful (e.g. the [API reference](http://matplotlib.org/1.5.3/api/index.html)).

Second, the fathead examples generally work with sources where you can download the HTML docs as a single file. With Matplotlib, it looks like you have to scrape matplotlib.org or build the documentation from [source](https://github.com/matplotlib/matplotlib). I decided to build the docs to satisfy the monolithic download requirement. Unfortunately I wasn't able to build the docs successfully during the time I had allotted to working on this.

If I get time to take another crack at it I'll post an update here.

**Comment by pjhampton** [comment]
Hey @pbronez!

Just checking in. Are you still interested on working on this Fathead?

**Comment by rahulxxarora** [comment]
@pjhampton I would like to work on it if nobody else is currently active.

**Comment by pjhampton** [comment]
Hey @rahulxxarora, 

I will give @pbronez some more time to respond. Sometimes life can get in the way of open source 😄

**Comment by pbronez** [comment]
@rahulxxarora go for it!

**Comment by pjhampton** [comment]
I will open this back up for claiming. You can take it on after the npm fathead @rahulxxarora if you're up for it?

**Comment by rahulxxarora** [comment]
@pjhampton Okay

**Comment by jaredwelsh** [comment]
read the thread but noticed this still has the needs a dev tag, still up for grabs or does @rahulxxarora have it?

**Comment by pjhampton** [comment]
Hey @jaredwelsh! No, @rahulxxarora is working on a couple of high priority things. You can take it if you want? 😄

**Comment by jaredwelsh** [comment]
Awesome, will do!

**Comment by pjhampton** [comment]
Hey @jaredwelsh! How are you getting on? Do you have any questions I can help with? 😄
