### ISSUE TITLE
Create New Python unit testing Fathead

### ISSUE THREAD

**Issue by gaulrobe** [duckduckgo/zeroclickinfo-fathead#236]
Looks like the current python fathead doesn't support unittest-y queries. https://duckduckgo.com/?q=python+assertIsNotNone&ia=web

We could leverage https://docs.python.org/3.4/library/unittest.html for this.

**Comment by edgesince84** [comment]
Thanks, @gaulrobe - keep the Python improvements coming!

**Comment by vidhan13j07** [comment]
@edgesince84, 
Can I implement this Fathead?

**Comment by alohaas** [comment]
Hey @vidhan13j07, you'll want to speak to @jdorweiler about that :) He is in charge of improving the Python search space.

**Comment by jdorweiler** [comment]
@vidhan13j07 this was actually fixed in https://github.com/duckduckgo/zeroclickinfo-fathead/pull/270#event-751442364. 

Are you interested in building a fathead for something else?
https://forum.duckduckhack.com/t/coverage-for-popular-packages/433
