### ISSUE TITLE
Emoticon: Add more emoticons

### ISSUE THREAD

**Issue by NaveenKarippai** [duckduckgo/zeroclickinfo-fathead#238]
could we add more emoticons to the list. For example, checkout [this](http://www.lovethispic.com/image/152303/facebook-emoticons-cheat-sheet).

---

IA Page:  http://duck.co/ia/view/emoticon 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
@NaveenKarippai would you like to build a new Fathead for emoticons? The current is closed-sourced but there's no real need. It should scrape the Emoticons page in Wikipedia that you've linked 👍

**Comment by NaveenKarippai** [comment]
@moollaza yes, I'd love to!

**Comment by pjhampton** [comment]
Hey @NaveenKarippai 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
