### ISSUE TITLE
MDN JavaScript: make it a Longtail

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#239]
Currently, [MDN JavaScript](https://duck.co/ia/view/mdnjs) doesn't trigger nearly enough; it could cover a lot more JS reference queries, but the strict query - article title matching prevents it from doing that.
##### To Do
- Converting the [output file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdnjs/output.txt) either to JSON or XML.

From there we'll be able to test and see if anything else needs to be done.

Read the docs to learn more about [Fatheads](http://docs.duckduckhack.com/resources/fathead-overview.html) and [Longtails](http://docs.duckduckhack.com/resources/longtail-overview.html).

Please see the forum topic [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155) for more details, and leave a reply before starting to work on this.
Thanks!

---

IA Page: https://duck.co/ia/view/mdnjs
Maintainer: @ericedens 

Forum topic: [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

**Comment by bfmags** [comment]
Started work around converting the output file to XML (JSON will be the same).
Creating a bash script to parse the file (WIP https://github.com/bfmags/output2xml), considering switching to  python since there's already some parser code

**Comment by bfmags** [comment]
* got first xml output from output.txt
https://github.com/bfmags/zeroclickinfo-longtail/blob/master/lib/longtail/mdnjs/output.xml 
* based on the existing code to generate the xml (some cleanup/rewrite still to be done) https://github.com/bfmags/zeroclickinfo-longtail/blob/master/lib/longtail/mdnjs/toxml.py
* the xml in the docs page http://docs.duckduckhack.com/resources/longtail-overview.html  doesn’t seem to be valid?
* missing instant_answer_id
* already have the json writer in place, missing some tweaks, will commit soon

**Comment by MariagraziaAlastra** [comment]
> the xml in the docs page http://docs.duckduckhack.com/resources/longtail-overview.html doesn’t seem to be valid?

Yeah, missing an `</add>` at the end...

Thanks @bfmags, you're doing great!

**Comment by moollaza** [comment]
Closing as this isn't currently an option for us. We're going to continue with the Fathead approach for now. If this comes up again we can reopen.
