### ISSUE TITLE
Improve CanIUse Fathead

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#245]
### Objective

Improve the display of the results, and triggering for the CanIUse Fathead

### Background

CanIUse currently addresses most of the CSS queries (1.7%) but the Instant Answer also addressed various HTML and JavaScript queries.

Visually, it's not the most appealing Instant Answer, and it also has room for triggering improvements.

### ToDo

1. Queries containing "compatibility" don't trigger this Instant Answer and they should:

 - [css3 colors compatibility](https://duckduckgo.com/?q=css3+colors+compatibility&ia=web)
 - [flexbox css browser compatibility](https://duckduckgo.com/?q=flexbox+css+browser+compatibility&ia=web)

2. Add the **notes** to the result, or at least provide a link to them
3. Create an InfoBox with external links to the **resources** to provide quick access to more information

### What to do: 

1. Comment here if you'd like to handle this task. 
2. Review any Related Discussions, Issues, and Pull Requests (below).
3. [Setup your Dev Environment](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) (first-timers only)
4. Refer to the [Fathead documentation](http://docs.duckduckhack.com/resources/fathead-overview.html) and [other Fatheads](https://duck.co/ia?repo=fathead) as examples
5. [Submit a Pull Request](http://docs.duckduckhack.com/submitting/pull-request.html) with your completed changes

### Who to contact for help: 
Please contact @moollaza  or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html).

----

**Related Discussions, Issues, and Pull Requests:** 

Forum Topic: https://forum.duckduckhack.com/t/improve-ia-caniuse-fathead/228/1

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone be interested in improving the CanIUse Fathead?

Seeing as the current [parser](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/caniuse/parse.py) is written in Python, it will require Python skills to improve it. If necessary, it could be re-written in another language, as long as the end result is a better Instant Answer :)

**Comment by moollaza** [comment]
@samskeller Awesome! Thanks for volunteering 👍 

Are you familiar with the CanIUse website and how it's used? Have you used the CanIUse Fathead much?

If not, I'd suggest you familiarize yourself with it. Happy to discuss things further on the forum, or even on Slack 😃

**Comment by moollaza** [comment]
@samskeller As well, please be sure to signup on the [Forum](https://forum.duckduckhack.com) and join in on the [CSS discussions](https://forum.duckduckhack.com/c/programming/css)!

**Comment by samskeller** [comment]
@moollaza thanks! I haven't used this Fathead or the website much but I'll take a look and post on the forum if I have questions

**Comment by souravbadami** [comment]
@moollaza -- I want to work on this.

**Comment by samskeller** [comment]
@souravbadami thanks for the interest, but sorry I'm actually almost finished with this (I've just been very behind and haven't done one last thing)

**Comment by souravbadami** [comment]
@samskeller -- Sounds good. Thanks!
