### ISSUE TITLE
multiple "o" s in 'Procedural programming languages' query

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/zeroclickinfo-fathead#249]
Querying about _Procedural programming languages_ displays multiple "o"'s:
![screenshot 79](https://cloud.githubusercontent.com/assets/8397274/16851628/05028646-4a22-11e6-8c77-e8423faaeaea.png)

**Comment by jdorweiler** [comment]
Nice find. 

@andrey-p should be able to help

**Comment by andrey-p** [comment]
Thanks for reporting this, @gautamkrishnar! I've created an internal task for it.

**Comment by gautamkrishnar** [comment]
Looks like this issue is not relevant anymore. closing this.
