### ISSUE TITLE
MDN JavaScript: update parser to use Wget results

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#257]
Depends on #256 
After updating MDN JS to use Wget, we'll probably need to update the parser as well, to maintain the functionality.

Read the docs to learn more about [Fatheads](http://docs.duckduckhack.com/resources/fathead-overview.html).

Please see the forum topic [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155) for more details.
Thanks!

-----------------------------------------------
IA Page: https://duck.co/ia/view/mdnjs
Maintainer: @ericedens 

Forum topic: [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

**Comment by bfmags** [comment]
_started working on this one_

**Comment by tagawa** [comment]
Thank you very much @bfmags! Please shout if you need assistance or want to share any of the work.

**Comment by MariagraziaAlastra** [comment]
Hey @bfmags!
As I said on #256 as well, can you open a PR? Even if it's still a work in progress it's totally fine, and it'll be easier to follow along and provide feedback.

Thanks a lot for all the work you're doing!

**Comment by moollaza** [comment]
Fixed in #268
