### ISSUE TITLE
Fathead Repo should have Util libraries for Python, Perl, Ruby, etc 

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#263]
All Fatheads have their own parsers and many of these scripts define similar functions used to create articles, redirects, code blocks, define an image, etc.

To make writing Fatheads easier, I think we should have a Util library for each of the popular languages used (Perl, Python, Ruby, Node, etc.) which implement a common set of utility functions.

**Comment by gaulrobe** [comment]
How many thumbs up's can I give this? :+1:

**Comment by jrasanen** [comment]
I was wondering the exact same thing while creating my first fathead. Should we start thinking of common operations and drafting a spec for the util library?

**Comment by jdorweiler** [comment]
Great idea! When I started on the Perl docs parser I made a few separate util functions. 
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/6f360519fd58aae371136717127a73a12fce7d03/lib/fathead/perl_doc/Parsers/Util.pm

**Comment by jdorweiler** [comment]
I don't see any reason not to do this so lets go for it. I'd just put them in a new dir `/util/<language>/`.

**Comment by GuiltyDolphin** [comment]
@moollaza My only concern is keeping all the util files in-sync; perhaps we can avoid this issue by perhaps 'assigning' each file to a few community members who can write good, idiomatic code in that language and keep their respective language file up-to-date?

**Comment by moollaza** [comment]
> My only concern is keeping all the util files in-sync;

Hopefully once we have an idea of what functionality we want/need there won't be many changes necessary after, but I agree it's still a potential issue.

> perhaps we can avoid this issue by 'assigning' each file to a few community members who can write good, idiomatic code in that language

This sounds like an ideal solution. Similarly we can make an issue to update each codebase whenever a new feature is added to any other, that we think belongs in all of them 👍 

> Alternatively we could just write in a meta-language and translate to the required languages

We can have a spec written in english to describe the functions we expect along with their inputs, outputs and maybe tests too?

**Comment by GuiltyDolphin** [comment]
> We can have a spec written in english to describe the functions we expect along with their inputs, outputs and maybe tests too?

Perhaps a clear description of each function in the docs? Then we'd expect them all to behave in exactly the same way for each language, eg.,

```markdown

`parse_header(title)`

Parse an `<h1>` block with a `name` attribute matching `title`.
```

**Comment by GuiltyDolphin** [comment]
@moollaza I've created a branch over on the docs (https://github.com/duckduckgo/duckduckhack-docs/tree/fathead-spec) that we can ping ideas off and get a rough idea of what the spec might look like. Might it also be worth creating a forum topic for this so we can have more community involvement?

cc @duckduckgo/community-leaders

**Comment by moollaza** [comment]
> Might it also be worth creating a forum topic for this so we can have more community involvement?

Sure, let's discuss on the Forum. No need to discuss this on GitHub
