### ISSUE TITLE
MDN JavaScript: use keywords in the OpenSearch description documents for Categories

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#269]
Depends on #256 and #257 
This is an idea @bfmags had!

> MDN supports [OpenSearch](http://www.opensearch.org/Home), meaning that every page has an [OpenSearch description document](http://www.opensearch.org/Specifications/OpenSearch/1.1#Examples) with keywords, etc.

This means we can use the keywords contained in there to programmatically generate categories for this Fathead.

Read the docs to learn more about [Fatheads](http://docs.duckduckhack.com/resources/fathead-overview.html).

Please see the forum topic [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155) for more details.
Thanks!

---

IA Page: https://duck.co/ia/view/mdnjs
maintainer: @ericedens 

Forum topic: [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

**Comment by bfmags** [comment]
_@MariagraziaAlastra  actually have to thank @ericedens for the initial idea about using a provided API_

### OpenSearch API and MDN

**Syntax**

`https://developer.mozilla.org/en-US/search?q={}`
`https://developer.mozilla.org/en-US/search?q=%22js%20array%22`

**Wget**

`wget -S -q --header "Accept: application/json" https://developer.mozilla.org/en-US/search?q=%22js%20array%22 --output-document=result.json`

**Result**

https://gist.github.com/bfmags/955a1448156e738d19104f15a5ec864f

____

{WIP}
