### ISSUE TITLE
Python: unify python2 and python3 docs

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#272]
**Background**

We have coverage of docs.python.org for Python3 but none for Python2. Even though Python2 is considered a legacy version, it still has a lot of use. 

**Objective**

Unify our python docs fathead to cover both Python3 and Python2. 

The exact implementation is up to whoever develops this but I think the general idea is to:

- Default to python3 docs in cases where both python3 & 2 are identical
- In cases where they're different show the Python3 docs but include an infobox link to the Python2 docs. 

How I think this could work technically:

- update parse.py to parse both Python3 and Python2 docs 
- Generate separate output.txt files for each
- Go through both output files comparing keys and abstracts
- If the Python3 version is identical to the Python2 just keep the Python3 entry
- If they're different we can default that search to Python3 but show an infobox that links to the Python2 version.

---

IA Page: https://duck.co/ia/view/python

**Comment by jdorweiler** [comment]
@duckduckgo/duckduckhack-contributors would anyone be interested in improving the Python Fathead?

Seeing as the current parser is written in Python, it will require Python skills to improve it. I'm happy to help out as much as anyone needs.

**Comment by gerlachry** [comment]
@jdorweiler I would be interested in giving this one a shot, I started taking a look at it this afternoon.

**Comment by jdorweiler** [comment]
Forgot to include a link to the forum post. https://forum.duckduckhack.com/t/python-docs-fathead/176/6

**Comment by gerlachry** [comment]
@jdorweiler I think I have a first draft of creating a second file, output_py2.txt w/ just the keys that have python2 abstracts different from those in the python3 output.txt.  Any docs on how fathead instant answers work and how to load both output files?  How to go about implementing your last bullet point:

> - If they're different we can default that search to Python3 but show an infobox that links to the Python2 version.

**Comment by jdorweiler** [comment]
@gerlachry 
Here's the fathead docs. http://docs.duckduckhack.com/resources/fathead-overview.html
I think we can use the category field for this. 

As an example, let's say that `array.append()` is different in python2 vs python3. The entries in the output file for this might look like:

```
array.append    A    [[array.append]]    Some description for the python3 array.append
python2 array.append    A [[array.append]]    the python2 description for array.append
```

The first entry is our default python3 version and the second is the python2 version.  Since both entries belong to the same category (array.append) we will see an infobox linking to the other.
