### ISSUE TITLE
Create SwiftDocs Instant Answer

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#275]
## Background

[http://swiftdoc.org/](http://swiftdoc.org/) has some excellent documentation on Swift types and protocols. We can absolutely use this data to answer queries like "swift array".

<img width="345" alt="eb96761b2088e9392921006e2d154e5cd7206f1f_1_690x359" src="https://cloud.githubusercontent.com/assets/81969/17191313/6791dc18-5417-11e6-96bd-91af7494b313.png">
### Objective

For it to answer queries pertaining to protocols and types in Swift.
#### Example Queries
- [swift foreach](https://duckduckgo.com/?q=swift+foreach)
### What to do:
1. Comment here if you'd like to handle this task. 
2. Review any Related Discussions, Issues, and Pull Requests (below).
3. [Setup your Dev Environment](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) (first-timers only)
4. Refer to the [Fathead documentation](http://docs.duckduckhack.com/resources/fathead-overview.html) and [other Fatheads](https://duck.co/ia?repo=fathead) as examples
5. [Submit a Pull Request](http://docs.duckduckhack.com/submitting/pull-request.html) with your completed changes
### Who to contact for help:

Please contact @jagtalon  or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html).

---

**Related Discussions, Issues, and Pull Requests:** 

Forum Topic: https://forum.duckduckhack.com/t/create-swiftdoc-instant-answer/242

**Comment by jagtalon** [comment]
I'm currently working on this in #271, but feel free to take it from me! Lots of improvement things that we can do in there.

**Comment by pjhampton** [comment]
Looks like this has been sorted? Closing for now 👍
