### ISSUE TITLE
MDN JavaScript: fetch the errors reference articles and parse them

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#280]
## Background
Right now we're only showing the articles from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects and from https://developer.mozilla.org/en-US/docs/Web/API, but there are a ton of useful articles we could surface.
Ultimately I think we should fetch all the categories, but let's start with the errors: a lot of people search for copypasted console errors, so I think if this is handled the right way, it could cover a good portion of the JS search space.

## To Do
- fetch articles from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors
- when parsing them, include as an abstract at least the first sentence in the "What went wrong?" section (the ID is `#what_went_wrong`)
- also include the first invalid (`.example-bad`) and valid examples (`.example-good`), if available, with their description; otherwise just include the first example.
- generate redirects based on the URLs (eg for the article [TypeError: "x" is not a function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function) the URL is "not a function", and that could be added as a redirect. We can discuss about other good ways to generate redirects as well.

## Forum
For more info read the forum topic [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155).

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

------------------------------------------------------------------------------
IA Page: duck.co/ia/view/mdnjs
Maintainer: @ericedens

**Comment by bfmags** [comment]
I'll soon resume work on this issue

**Comment by MariagraziaAlastra** [comment]
Done in #323 - thanks!
