### ISSUE TITLE
Proposal for improving SwiftDocs: Add disambiguations to the output file

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#281]
Attention @duckduckgo/duckduckhack-contributors 

**The proposal:** 

Create a disambiguation entry in `output.txt` (check out http://docs.duckduckhack.com/resources/fathead-overview.html to learn how that's done) to disambiguate (separate) properties and functions that have the same name. 

We need this so that people are not throwing out any information when people search for similarly-named things. For example, if someone searched for `swift flatMap`, we should be able to give people a list of articles where that entry exists. The functionality should be similar to the one found on their website:

<img width="1076" alt="screen shot 2016-08-01 at 11 55 37 am" src="https://cloud.githubusercontent.com/assets/81969/17300219/72a7d668-57df-11e6-961d-47d79555fa67.png">

**What to do:**
1. Familiarize yourself with the code in https://github.com/duckduckgo/zeroclickinfo-fathead/pull/271. This is a Fathead--you can learn more about Fatheads in http://docs.duckduckhack.com/resources/fathead-overview.html.
2. As the parser iterates through all the classes, methods, and properties, make sure to record the duplicate titles that we run into.

**Who to contact for help:**

Please contact @jagtalon or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html). 

**Related Discussions, Issues, and Pull Requests (if available):** 
- https://forum.duckduckhack.com/t/create-swiftdoc-instant-answer/242
- https://github.com/duckduckgo/zeroclickinfo-fathead/pull/271
- https://duck.co/ia/view/swiftdocs

**Comment by soleo** [comment]
I think this issue can be closed after https://github.com/duckduckgo/zeroclickinfo-spice/pull/2958 is merged. 

It would show a list of related functions in different classes.

<img width="1280" alt="screen shot 2016-08-13 at 9 14 52 pm" src="https://cloud.githubusercontent.com/assets/635858/17646712/187ab348-619b-11e6-98ed-5ef44f75f94c.png">
<img width="1280" alt="screen shot 2016-08-13 at 9 13 53 pm" src="https://cloud.githubusercontent.com/assets/635858/17646711/18787574-619b-11e6-80a8-74530205274a.png">

**Comment by soleo** [comment]
@jagtalon
