### ISSUE TITLE
Proposal for improving Apple Docs: Add disambiguations to the output file

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#282]
Attention @duckduckgo/duckduckhack-contributors 

**The proposal:** 

Create a disambiguation entry in `output.txt` (check out http://docs.duckduckhack.com/resources/fathead-overview.html to learn how that's done) to disambiguate (separate) properties and functions that have the same name. 

For example, if someone searched for `swift compare`, we should be able to give people a list of articles where that entry exists. The functionality should be similar to the one seen on [Dash](https://kapeli.com/dash):

<img width="865" alt="screen shot 2016-08-01 at 12 06 36 pm 1" src="https://cloud.githubusercontent.com/assets/81969/17300516/b65f1960-57e0-11e6-98bb-2b95caa6029b.png">

**What to do:**

1. Familiarize yourself with https://github.com/duckduckgo/zeroclickinfo-fathead/pull/278. This is a Fathead--you can learn more about Fatheads in http://docs.duckduckhack.com/resources/fathead-overview.html.

2. As the parser iterates through all the classes, methods, and properties, make sure to record the duplicate titles that we run into.

**Who to contact for help:**

Please contact @jagtalon or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html). 

**Related Discussions, Issues, and Pull Requests (if available):**

- https://forum.duckduckhack.com/t/improve-apple-os-x-macos-documentation/240
- https://github.com/duckduckgo/zeroclickinfo-fathead/pull/278
- https://duck.co/ia/view/appledocs

**Comment by jagtalon** [comment]
Hello, @duckduckgo/duckduckhack-contributors! If you know Python, help us make searching for Apple documentation a breeze. This task is one of the more important ones that I think will really make a big impact.

Like what you see? Head on over to https://forum.duckduckhack.com/t/swift-search-overview/98 to get started!

**Comment by sahildua2305** [comment]
@jagtalon I can help here. I have been writing Python for a while now.

**Comment by jagtalon** [comment]
@sahildua2305 yusss! Hit me up on Slack if you need any help! The only caveat that I forgot to mention is that the code depends on a Mac. Other than that, you should be good to go!

**Comment by sahildua2305** [comment]
@jagtalon what does that mean? Code depends upon a Mac?

**Comment by jagtalon** [comment]
@sahildua2305 So currently we use the docsets that come installed in XCode. But now that I think about it, I think I could just send you the docsets. :)

**Comment by jagtalon** [comment]
@sahildua2305 I've got some docsets available for you (my laptop is fried so all thanks should actually go to @moollaza!).

I can send it to you over Slack if you need it (http://docs.duckduckhack.com/resources/get-in-touch.html if you haven't signed up yet!)

**Comment by sahildua2305** [comment]
Already there. Please send them over Slack :smile @jagtalon

**Comment by sahildua2305** [comment]
@jagtalon I need help in starting with this. Pinging you on Slack!

**Comment by moollaza** [comment]
Commenting to update https://forum.duckduckhack.com/t/swift-search-overview/98
