### ISSUE TITLE
Improve Apple Docs macOS: Add redirects to the output file

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#283]
Attention @duckduckgo/duckduckhack-contributors 

**The proposal:** 

Create redirect entries in output.txt (check out http://docs.duckduckhack.com/resources/fathead-overview.html to learn how that's done) so that searches like `NSDate.compare` and `compare` would link to the same article. Similar to how [Dash](https://kapeli.com/dash) works:

<img width="845" alt="screen shot 2016-08-01 at 12 15 45 pm" src="https://cloud.githubusercontent.com/assets/81969/17300774/c65c7104-57e1-11e6-810a-78bd2b4c44e7.png">

**What to do:**

1. Familiarize yourself with https://github.com/duckduckgo/zeroclickinfo-fathead/pull/278. This is a Fathead--you can learn more about Fatheads in http://docs.duckduckhack.com/resources/fathead-overview.html.

2. As the parser iterates through all the methods, and properties, make sure to create entries for `Class.method`.

**Who to contact for help:**

Please contact @jagtalon or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html). 

**Related Discussions, Issues, and Pull Requests (if available):**

- https://forum.duckduckhack.com/t/improve-apple-os-x-macos-documentation/240
- https://github.com/duckduckgo/zeroclickinfo-fathead/pull/278
- https://duck.co/ia/view/apple_docs_macos

**Comment by jagtalon** [comment]
I got this, fam.

**Comment by jagtalon** [comment]
CC @sahildua2305 I'll be working along side you!

**Comment by moollaza** [comment]
Commenting to update https://forum.duckduckhack.com/t/swift-search-overview/98

**Comment by sahildua2305** [comment]
@moollaza This is done here - https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/apple_docs_macos/parse.py#L114

**Comment by moollaza** [comment]
@sahildua2305 thanks for pointing that out!
