### ISSUE TITLE
Ruby Fathead: some Instant Answer related topic links show the wrong IA

### ISSUE THREAD

**Issue by kotoshenya** [duckduckgo/zeroclickinfo-fathead#290]
Some linked queries on [Ruby Instant Answers](https://duck.co/ia/view/ruby) relate to topics wider than Ruby, meaning that they do not return the intended Instant Answer.

It’s useful to get Instant Answers for unprefixed by searching for “[enumerable grep](https://duckduckgo.com/?q=enumerable+grep&ia=about)”, but inter-IA links should have enough context to always be able to include the “ruby” keyword, as in “[ruby enumerable grep](https://duckduckgo.com/?q=ruby+enumerable+grep&ia=about)”, or use some other mechanism to ensure that the intended IA is shown.

I’m raising this as an issue as the only fix I can see is to add a “ruby” keyword to all related categories in [output.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/ruby/output.txt), which I believe will stop the list appearing for category searches without the keyword.

#### Class query

[![“ruby array” IA](https://cloud.githubusercontent.com/assets/6856120/17509592/a52cb228-5e12-11e6-8a75-cba1732a19f5.png)](https://duckduckgo.com/?q=ruby+array&ia=about)

The linked query in the **Related Topics** box is “[Classes](https://duckduckgo.com/184/c/Classes)”, which is too broad.  “[Ruby Classes](https://duckduckgo.com/?q=ruby+classes&ia=list)” triggers the Ruby IA.

#### Method query

[![“ruby method ==”](https://cloud.githubusercontent.com/assets/6856120/17509593/a6717466-5e12-11e6-89ac-88e4fb35eb3e.png)](https://duckduckgo.com/?q=ruby+method+%3D%3D&ia=about)

This IA links to “[Method methods](https://duckduckgo.com/184/c/Method_methods)”, which includes the **List** IA but defaults to **Definition**:

[![method-methods-ia](https://cloud.githubusercontent.com/assets/6856120/17509810/d73659a8-5e13-11e6-8001-9af42c120a43.png)](https://duckduckgo.com/184/c/Method_methods)

“[ruby method methods](https://duckduckgo.com/?q=ruby+method+methods&ia=list)” shows only the intended IA.

***

IA: [Ruby](https://duck.co/ia/view/ruby)

**Comment by jdorweiler** [comment]
@kotoshenya you're right. Adding the "Ruby" keyword to all categories should fix this.
