### ISSUE TITLE
MDN CSS: More Improvements

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#293]
The MDN CSS IA is live and is now the biggest CSS Instant Answer, accounting for 8% of CSS Related Queries.

There is lots of room for improvement though to make it's results more useful and to also further increase its coverage:
## Improvements
- [x] ~~Simplify new External Links to just grab the "Browser Compatibilty" link as only the first External Link is displayed on the result~~
  - After more reasearch it turn out we can't use External Links as I had expected. We'll need to skip this for now too
- [x] Parse out "Initial Value" where applicable, add it to the abstract, above the Syntax example
- [x] Create redirects for each property by appending property type to name. For example:
  - "background-color property" should redirect to "background-color"
  - "after psuedo element" should redirect to "after"
  - "first-of-type selector" should redirect to "first-of-type"
  - "px unit" should redirect to "px"
  - etc.
- [ ] The "See Also" section should be parsed to create "Related Topics" for each article, this will create an infobox with links
- [x] We should also categorize each article based on it's type and add the category as a related topic so we provide links to the elements CSS Category Page
  - I've collected some info and built a mapping of potential category pages we can use. I imagine we'll want to build a reverse mapping of articles -> categories from this, and then use that to add the appropriate categories to each page as we process it:
    - https://gist.github.com/moollaza/cb47c57d4a6eee0b254a887e9edccf73
  - The Ruby Fathead does a great job of this: https://duckduckgo.com/?q=array+bsearch&ia=about
- [x] Add support for `-moz` and `-webkit` extensions
  - [Mozilla Extensions](https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions)
  - [WebKit Extensions](https://developer.mozilla.org/en-US/docs/Web/CSS/Webkit_Extensions)
  - We may also want to make the values these can be set to, into redirects?
- [x] Add support for `initial value` lists
  - e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/border-top
  - https://beta.duckduckgo.com/?q=css+border-top&t=hh&ia=about
  - /cc @hchienjo
---

/cc @hchienjo

**Comment by hchienjo** [comment]
Great ideas. Looking forward to working on them with everyone.

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would anyone out there be interested to dive and help us improve the CSS Fathead?

The code here is all Perl, so it will require someone with Perl experience!

**Comment by mjgardner** [comment]
I'll pitch in.

**Comment by moollaza** [comment]
> I'll pitch in.

@mjgardner thanks a lot! Which of the above tasks are you interested in?

**Comment by mjgardner** [comment]
> Which of the above tasks are you interested in?

@moollaza I suppose I'll start with the first one (Simplify new External Links) and after I finish that grab whatever's next available.

**Comment by moollaza** [comment]
> I suppose I'll start with the first one (Simplify new External Links) and after I finish that grab whatever's next available.

Perfect! Thanks a lot  🙇

**Comment by hchienjo** [comment]
About the "Related Topics", from the  [documentation](http://docs.duckduckhack.com/resources/fathead-overview.html) 

> Related topics. These will be turned into links in the Zero-click Info box. Examples: [[Perl Data Language]]. If the link name is different, [[Perl Data Language|PDL]]

it is not apparently clear how exactly the links are supposed to be organized.

Take for instance [active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active), we have a [see also](https://developer.mozilla.org/en-US/docs/Web/CSS/:active#See_also) at the bottom, so, how should the "Related topics" looks like for such a case?

Is it
`[[:link https://developer.mozilla.org/en-US/docs/Web/CSS/:link] [:visited https://developer.mozilla.org/en-US/docs/Web/CSS/:visited] [:hover https://developer.mozilla.org/en-US/docs/Web/CSS/:hover]]`?

**Comment by moollaza** [comment]
@hchienjo they should be separated with `\\n` like the External links.

The links themselves should be of the format `[[Article Name]]`  or `[[Title | Article Name]]`

e.g. `[[link]]\\n[[visited]]\\n[[hover]]`

OR

`[[Link Pseudo-Class | link]]\\n[[Visited Pseudo-Class | visited]]\\n[[Hover Pseudo-Class | hover]]`

**Comment by hchienjo** [comment]
Thanks

**Comment by moollaza** [comment]
@hchienjo @mjgardner I've updated this a bit, it turns out my understanding of Related Topics and External Links was wrong and we cannot use them as I had expected. For now I'll remove them. If we adjust Fatheads internally, we may be able to use them as I had expected.

**Comment by moollaza** [comment]
@hchienjo @mjgardner I've updated this a bit more. Adding support for the `-moz` and `-webkit` properties should be a fairly easy way of really increasing the coverage of this Fathead, assuming the pages can all be parsed with our existing code 👍 

Also, I noticed a small bug with our handling of the initial value when it provides a list of values

**Comment by hchienjo** [comment]
@moollaza Great. Will gladly collaborate with more volunteers to get the features implemented.

**Comment by hchienjo** [comment]
@moollaza I think I already have a solution for the list in initial value in this [PR](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/317).

Please review.

**Comment by moollaza** [comment]
@mjgardner would you be interested in updating the fetch script to grab the `-moz` and `-webkit` extensions?

**Comment by hchienjo** [comment]
@moollaza If no one takes it up I am willing to have a go at it.

**Comment by rasikapohankar** [comment]
Hi @hchienjo @mjgardner! Have you started working on it? If not, I would like to try.

**Comment by mjgardner** [comment]
@rasikapohankar Go ahead, I am swamped with work and moving across the country.

**Comment by rasikapohankar** [comment]
Thanks @mjgardner!

**Comment by hchienjo** [comment]
@rasikapohankar Thanks for reaching out. Please checkout the [forum](https://forum.duckduckhack.com/t/css-search-overview/96/17) so as to get up to speed.

**Comment by rasikapohankar** [comment]
Thanks @hchienjo, I'll try to update the script for the extensions then. I might require a longer time to do this since I'm not experienced with Perl and have not worked on a Fathead before either.

**Comment by gautamkrishnar** [comment]
@rasikapohankar :+1:  Take your time...
