### ISSUE TITLE
Python: show built-in functions

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#296]
In #270 we removed some entries to avoid namespace conflicts. We might want to white list the built-in functions. 
https://docs.python.org/3.5/library/functions.html#min

For example, even though there are likely conflicts for `open()` users are most
likely looking for the built-in.
https://duckduckgo.com/?q=python+open&t=canonical&atb=v23&ia=qa
https://docs.python.org/3.5/library/functions.html#open

------
IA Page:  http://duck.co/ia/view/python 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

**Comment by souravbadami** [comment]
I would like to give it a shot.
