### ISSUE TITLE
C++ Reference Docs: Improve triggering (more lenient)

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#298]
The IA triggers on ['cpp std::unordered_set'](https://duckduckgo.com/?q=cpp+std%3A%3Aunordered_set&ia=about), but not on ['cpp unordered_set'](https://duckduckgo.com/?q=cpp+unordered_set&ia=about) or ['cpp unordered set'](https://duckduckgo.com/?q=cpp+unordered+set&ia=about).

We should improve triggering by allowing the `::` header to be omitted, and we should allow whitespace in place of underscores. Anywhere this causes a clash we should just build a disambiguation page with the entries pointing to the full titles.

---

IA Page:  http://duck.co/ia/view/cppreference_doc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ManrajGrover

**Comment by amarlearning** [comment]
@GuiltyDolphin can i take this one. ?

**Comment by sahildua2305** [comment]
@amarlearning Go ahead! It's yours. Let me know if you need any help. 😄

**Comment by amarlearning** [comment]
@sahildua2305 not able to find the trigger_words.txt file. Like perl_doc [trigger_words.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/perl_doc/trigger_words.txt) has one.

**Comment by sahildua2305** [comment]
@amarlearning what do you want to do with the trigger words for the fathead. Is it related to this issue or are you asking about something else?

**Comment by amarlearning** [comment]
@ManrajGrover in which file is the trigger query mentioned for this fathead ?

**Comment by moollaza** [comment]
@amarlearning the trigger words are all defined/managed internally.

The `trigger_words.txt` file isn't actually used internally, yet.

The trigger words aren't required for Fatheads to work, but if you'd like to add some, go ahead and create a trigger_words.txt file. I can update the internal triggers accordingly.

**Comment by amarlearning** [comment]
@moollaza i will do this.

**Comment by MariagraziaAlastra** [comment]
@amarlearning need any help with this?

**Comment by pjhampton** [comment]
@amarlearning Any update? 😄

**Comment by amarlearning** [comment]
@pjhampton I didn't get time to do that :disappointed:

**Comment by pjhampton** [comment]
Closing due to https://github.com/duckduckgo/zeroclickinfo-fathead/issues/781 👍
