### ISSUE TITLE
Apple Docs macOS: Overtriggering on 'lenient'

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#299]
See https://duckduckgo.com/?q=lenient&ia=about (`about` was the default tab).

I was rather expecting the Worknik IA to appear - I doubt many people will be searching for that particular definition (perhaps force `apple` to be present).
---

IA Page:  http://duck.co/ia/view/apple_docs_macos
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

**Comment by jagtalon** [comment]
I love how ironic this is! I'll look into it. @GuiltyDolphin would you be interested in helping improve the Swift programming language? https://forum.duckduckhack.com/t/swift-search-overview

**Comment by GuiltyDolphin** [comment]
@jagtalon I'm not really 'in the know' with Swift and I'm currently occupied with Perl/Haskell/Idris so I'm not sure how much I'd be able to contribute. Thanks for the offer though :heart:

**Comment by jagtalon** [comment]
@GuiltyDolphin That's alright! Just thought I'd ask. :)

**Comment by moollaza** [comment]
Commenting to update https://forum.duckduckhack.com/t/swift-search-overview/98

**Comment by MariagraziaAlastra** [comment]
Closing this as it's integrated in #501, thanks!
