### ISSUE TITLE
C++ Reference Docs: Support specific queries

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#300]
E.g., `std::unordered_set iterators` and `std::unordered_set member types`.

---

IA Page:  http://duck.co/ia/view/cppreference_doc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mylainos

**Comment by p12tic** [comment]
I think it does not make sense to add support to cppreference_doc fathead for these C++ identifiers. It's very hard to create a short description for these member types without taking information out of context. See, e.g., the "Member types" table [here](http://en.cppreference.com/w/cpp/container/unordered_map) - this is the only place they are described. For such things, regular search result should be enough.

To make matters worse, even if we wanted this issue to be solved, the solution will require lots of manual work and I think it's not likely that anyone will do it. I personally think that the reward is not worth the effort.

As one of the maintainers of the cppreference.com website and the maintainer of the Fathead output.txt generation code, I vote this issue to be closed :-)

**Comment by tagawa** [comment]
Thank you for sharing your thoughts @p12tic. As we currently have other higher priority issues open, let's follow your advice and close this. We can open it again in future if we decide it's worth implementing.
