### ISSUE TITLE
C++ Reference Docs: Show example code on how to use particular member function

### ISSUE THREAD

**Issue by ManrajGrover** [duckduckgo/zeroclickinfo-fathead#301]
Show example code on how to use particular member function. This is something that [cplusplus.com](http://www.cplusplus.com/reference/) provides under each member function of containers.

This will also help in understanding the use case better.

---

IA Page: https://duck.co/ia/view/cppreference_doc
Maintainer: @mylainos

**Comment by p12tic** [comment]
@ManrajGrover is it possible to do this while still fitting into the size constraints? At the moment most abstracts that cppreference_doc provides are already truncated to save space.

Regardless of that, I think it will be very hard to extract useful short examples out of cppreference.com. Maybe a separate fathead would be useful for this? So, for example, if user types `cpp string find example`, he could be shown full example that is on [this page](http://en.cppreference.com/w/cpp/string/basic_string/find).

**Comment by abijith-ka00** [comment]
c++ is simple,
if we catch it we can made all other programing languages

**Comment by rahulxxarora** [comment]
@tagawa I would like to work on it if it's not assigned to anybody else.

**Comment by tagawa** [comment]
Hi @rahulxxarora, that's very kind of you - thank you! Please feel free to tackle this and if you get stuck, either leave a question here or in our online chat at https://duckduckhack.slack.com (the #ask-anything channel is best). If needed, you can get a Slack invite here: http://quackslack.herokuapp.com/

**Comment by rahulxxarora** [comment]
Since this is my first time so just to make sure what I have thought is right. Here is my plan. I am planning to crawl [this page](http://en.cppreference.com/w/cpp/header) to fetch all the examples of member functions for each header file. I ran a test script on my system, It took around 10 minutes to scrape all the data and process it, is it fine? is anything wrong with this approach?

**Comment by moollaza** [comment]
> is it possible to do this while still fitting into the size constraints?

@p12tic which size restraints are you referring to? We (DuckDuckGo) don't have any constraints on Fathead abstracts as we automatically hide extra content on the front end. The user only needs to click the 'Show More' to see the rest of the content.

I would prefer to have a single Fathead, that shows the example usage alongside the definition of the function/method/algorithm/etc. This is also how all our other Fatheads work as well.

IMO the example code without any description or context looks odd, as if it's missing something.

**Comment by pjhampton** [comment]
Hey @ManrajGrover 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
