### ISSUE TITLE
CSS: "more at" link incorrect

### ISSUE THREAD

**Issue by edgesince84** [duckduckgo/zeroclickinfo-fathead#306]
The link for the "more at Mozilla Developer Network" is actually a free dictionary link for REM sleep - http://www.thefreedictionary.com/rem

cc @moollaza 

------
IA Page:  http://duck.co/ia/view/mdn_css 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hchienjo

**Comment by moollaza** [comment]
Which query are you seeing that for? It looks to be working correctly,  but I think I did see that happen for one query while I was testing...

**Comment by hchienjo** [comment]
Looking into it.

**Comment by edgesince84** [comment]
@moollaza "rem css" brings it up.  https://duckduckgo.com/?q=css+rem&kp=1&kad=wt_WT&kl=wt-wt&ia=about

@hchienjo that's a self-referential link you posted for "here."

**Comment by hchienjo** [comment]
@edgesince84 very sorry. Fixed the link. Posting here again. https://github.com/duckduckgo/zeroclickinfo-fathead/pull/292

**Comment by moollaza** [comment]
commenting here so this task is removed from the IA page...
