### ISSUE TITLE
Apple Docs: NSOperation is not being answered

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#307]
https://duckduckgo.com/?q=NSOperation&t=ffab&ia=web

It should be answered by https://duck.co/ia/view/apple_docs_macos

**Comment by moollaza** [comment]
Should be fixed by #355

**Comment by moollaza** [comment]
This is now being addressed by the Apple Docs MacOS Fathead on Beta https://beta.duckduckgo.com/?q=nsoperation&t=hi&ia=about

**Comment by moollaza** [comment]
Commenting here so this is removed from the IA Page

**Comment by moollaza** [comment]
https://forum.duckduckhack.com/t/swift-search-overview/98
