### ISSUE TITLE
GitManual: Support option queries

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#309]
We should support queries such as `git branch --delete` and display an [appropriate description](https://git-scm.com/docs/git-branch#_options).   

---

IA Page:  http://duck.co/ia/view/git_manual 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @samskeller

**Comment by samskeller** [comment]
@GuiltyDolphin this is an interesting idea -- would that mean creating a line in `output.txt` for each possible option for each git command? Would we just restrict it to one option and not try to handle the case of multiple options being queried?

**Comment by GuiltyDolphin** [comment]
@samskeller Yeah, I was thinking creating entries like `branch --delete` or `git branch --delete` - so one for each option.

I don't think it would be worth doing it for multiple flags - the payoff/effort would likely be too little (and the output might become crowded).

**Comment by samskeller** [comment]
@GuiltyDolphin sounds cool! I'll get to work on it

**Comment by samskeller** [comment]
Hey @GuiltyDolphin, sorry for the delay on this but I've just submitted a PR to support queries of git commands with single options. Take a look and let me know what you think! Thanks
