### ISSUE TITLE
Create a Fathead that shows tvOS APIs

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#314]
**The proposal:** 

Create a new language reference IA for tvOS.

<img width="1512" alt="screen shot 2016-08-18 at 2 15 00 pm" src="https://cloud.githubusercontent.com/assets/81969/17785383/76dd9b1a-654e-11e6-9380-e83e7116ffae.png">

**What to do:**

1. Familiarize yourself with https://github.com/duckduckgo/zeroclickinfo-fathead/pull/278. This is a Fathead--you can learn more about Fatheads in http://docs.duckduckhack.com/resources/fathead-overview.html.

2. Create a Fathead based off of that. You also have the option of creating your own parser.

**Who to contact for help:**

Please contact @jagtalon or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html). 

**Related Discussions, Issues, and Pull Requests (if available):**

- https://github.com/duckduckgo/zeroclickinfo-fathead/pull/278
- https://duck.co/ia/view/apple_docs_tvos

**Comment by moollaza** [comment]
A PR has been received: #388

**Comment by moollaza** [comment]
This Fathead is now live!

https://duckduckgo.com/?q=TVApplicationControllerContext
