### ISSUE TITLE
Wikipedia: Summaries given even when article is deleted.

### ISSUE THREAD

**Issue by JennaMalkin** [duckduckgo/zeroclickinfo-fathead#318]
Does not seem to take into account when a wikipedia article is deleted.

![lesleyroseddg](https://cloud.githubusercontent.com/assets/5298344/17835590/053b8682-67b7-11e6-8680-b04aa72cad43.PNG)

https://en.wikipedia.org/w/index.php?title=Special:Log/delete&page=Lesley_Rose indicates that this page was deleted in November 2014.

---

IA Page:  http://duck.co/ia/view/wikipedia_fathead 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
Thanks for reporting!

Deleted articles are removed when we update our Database. It should go away after a day or two I believe
