### ISSUE TITLE
jQuery Fathead: show examples and args descriptions

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#319]
## Background

the jQuery IA was recently rewritten by @kotoshenya in #294 and it's already showing good progress, but there's more that can be done to improve it!

For instance we could try showing some code examples.
Also, right now for each method we show which args are required, but it would be more useful if we also explained them, specify what they represent and which values are allowed for each of them, etc.
## To Do

For each article:
- If examples are available, choose a short one (maybe remove the HTML part if it's too long) to show. 
- Show args explanations in the infobox (if possible), instead of the jQuery methods link. Eg "jquery fade in" would show in the infobox, among the other args, "duration: (number or string, default 400) - a string or number determining how long the animation will run"
## Docs

[Learn more about Fatheads](http://docs.duckduckhack.com/resources/fathead-overview.html)
## Forum

See the forum topic [Improve JQuery Fathead](https://forum.duckduckhack.com/t/improve-jquery-fathead/180) for more details.

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

---

IA Page: https://duck.co/ia/view/jquery

**Comment by thinker3197** [comment]
If no one is working on this issue, I'm up for it.

**Comment by bfmags** [comment]
Go for it @thinker3197 ! Shout if you need any help 👍

**Comment by thinker3197** [comment]
Reference to working repository for current issue : [zeroclickinfo-fathead](https://github.com/thinker3197/zeroclickinfo-fathead)
