### ISSUE TITLE
Apple Docs: UIPrintInteractionController is not being answered

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#320]
https://duckduckgo.com/?q=UIPrintInteractionController&t=ffab&ia=web

It should be answered by https://duck.co/ia/view/apple_docs_ios

**Comment by moollaza** [comment]
Should be fixed by https://github.com/duckduckgo/zeroclickinfo-fathead/pull/354

**Comment by moollaza** [comment]
The new iOS Fathead has been deployed to Beta. It now addresses this:

https://beta.duckduckgo.com/?q=UIPrintInteractionController&t=ffab&ia=about

**Comment by moollaza** [comment]
Commenting here so this is removed from the IA Page
