### ISSUE TITLE
HTML "h1-h6" should have redirects for "h1", "h2", ...

### ISSUE THREAD

**Issue by rpicard** [duckduckgo/zeroclickinfo-fathead#33]
There is only an item for "h1-h6" (https://duckduckgo.com/?q=html+h1-h6) in html_ref.There should be items for h1, h2, h3, h4, h5, and h6 that redirect to "h1-h6." This should be an easy one to fix.

**Comment by souravbadami** [comment]
@rpicard -- You mean an entry for `html h1` which redirect to `html h1-h6` and similarly for h2, h3, h4, h5 & h6 ?

**Comment by JARIS101** [comment]
claim
