### ISSUE TITLE
MDN JS: Include uncategorized articles in the Instant Answer result

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#334]
## Background

Right now we're only showing the articles from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects and from https://developer.mozilla.org/en-US/docs/Web/API, but there are a ton of useful articles we could surface.

There are some articles, though, that don't have a real root category, and they're indicated as "misc" articles. Here's the list:
- [Lexical grammar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar)
- [JavaScript data structures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)
- [Enumerability and ownership of properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties)
- [Iteration protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)
- [Strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)
- [Transitioning to strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode/Transitioning_to_strict_mode)
- [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
- [Deprecated features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features)

## To Do
- Fetch the above listed articles
- Since they're all different from each other, we'll need to decide how to present each of them singularly. This is what I suggest:
  - Fetch the short description, syntax (when available) and first example for [Strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and[Iteration protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)
  - Instead of one big article, make multiple articles from [Lexical grammar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar) and [JavaScript data structures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures), one for each section starting with an `<h2>` element, making sure to leave out the **Specifications**, **Browser compatibility**, **Firefox-specific notes**, and **See also** sections. Depending on the section type, show the short description (the first sentence) and either the first example, or the first table, or the first list.
  - For [Transitioning to strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode/Transitioning_to_strict_mode) it'd be more useful to show just the first sentence, plus the **Syntax errors** paragraph of the **Differences from non-strict to strict** section
  - [Deprecated features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features) could be divided into two articles: **Deprecated features** and **Obsolete features**, one for each big section. The problem is, the first section especially might be too long to show enough information in a single article. We would probably need to cut it off and it would end up being not really useful. The other option is having an article for each paragraph of each section, eg **Deprecated String methods**, **Obsolete array methods**, etc.
  - For [Enumerability and ownership of properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) we could show the first sentence, plus the first table and/or the Detection table. The example is too long and probably not that useful.
- Generate all-lowercase redirects, removing words like "JavaScript". We'll talk about what other redirects might be good to add.

## Forum

For more info read the forum topic [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155).

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

---

IA Page: duck.co/ia/view/mdnjs
Maintainer: @ericedens

**Comment by pjhampton** [comment]
Closing in favour of https://github.com/duckduckgo/zeroclickinfo-fathead/issues/747. The last issue is referenced there 😄

**Comment by pjhampton** [comment]
Closing as this is no longer high priority 👍
