### ISSUE TITLE
Abbreviations: 

### ISSUE THREAD

**Issue by adityabhushan** [duckduckgo/zeroclickinfo-fathead#337]
On searching for `integrity meaning`, the url defaults to about and shows the abbreviation instead of the definition which seems like the intended query. 

The default behavior in this case is more likely to show the definition or the dictionary meaning of the word.

Current url
`https://duckduckgo.com/?q=integrity+meaning&ia=about`

Proposed url
`https://duckduckgo.com/?q=integrity+meaning&ia=definition`

---

IA Page:  http://duck.co/ia/view/abbreviations 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @stands4

**Comment by pjhampton** [comment]
Sure, we can set a higher signal on the definitions IA 👍
