### ISSUE TITLE
Python: `isdown` triggers `turtle.isdown`

### ISSUE THREAD

**Issue by mrshu** [duckduckgo/zeroclickinfo-fathead#359]
While the fathead answer is not incorrect per se, the organics do not seem to agree with it and I am also personally not sure if `turtle.isdown` is the best Instant Answer for queries which might be looking for services which help to check whether a certain website is online.

---

IA Page:  http://duck.co/ia/view/python 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

**Comment by GuiltyDolphin** [comment]
@mrshu So you were looking for the [IsItUp](https://duck.co/ia/view/is_it_up) Instant Answer? It looks like it could do with a bit of a trigger boost: https://duckduckgo.com/?q=is+python.org+up&ia=answer.

Would you like to raise this issue over on the Spice for this IA?

**Comment by mrshu** [comment]
@GuiltyDolphin honestly, I was not expecting an Instant Answer, the organics would be good enough.

I guess I would not be surprised with being presented this IA when searching for `python isdown` but right now I get quite a surprising Instant Answer when I search for `isdown`.

All in all, I think that no Instant Answer should trigger -- triggering IsItUp would make sense if there was an object in the query for which I would like to check whether it is down or not.

**Comment by GuiltyDolphin** [comment]
~~@mrshu Hmm, it looks like the top organics are all to do with `turtle.isdown`, so I think this triggering is fine.

The point is for the Instant Answer to provide a more useful (immediate) result than just organic links, and hopefully answer the query without the user having to go off searching. In this case it gives the information `Return True if pen is down, False if it’s up.`, which may answer the query.~~

Ah, sorry - I completely misread the title of the issue (I read it as `python isdown`). Yes, this is definitely a revelancy issue (`isdown`).

Hmm, I'm not entirely sure how the triggering works - I believe that the unqualified name (w/o `python`) will only trigger if nothing else does, then the qualified name has higher priority (or is more likely to trigger the FatHead).

I'll have a bit of a mooch and see if we can do anything about this (in general).
