### ISSUE TITLE
Python: `python tutorial` triggers an article on creating Python C plugins

### ISSUE THREAD

**Issue by mrshu** [duckduckgo/zeroclickinfo-fathead#360]
Once again, while the instant answer is certainly not off topic, I do not think many are looking for the tutorial on creating C plugins for Python when they search for `python tutorial`.

https://duckduckgo.com/?q=python+tutorial

------
IA Page:  http://duck.co/ia/view/python 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

**Comment by moollaza** [comment]
@mrshu thanks for pointing this out. I think part of the plan is to eventually have support for Tutorials/How-To's etc, perhaps by way of a Goodie or Cheat Sheet.

I suppose for now we could have the parser ignore this entry or give it a more specific title?
