### ISSUE TITLE
Python: Abstracts missing new line

### ISSUE THREAD

**Issue by mrshu** [duckduckgo/zeroclickinfo-fathead#361]
It seems that in case of `python ast` the abstract is missing a newline.

![selection_005](https://cloud.githubusercontent.com/assets/461491/18243855/7fd3d1c2-735d-11e6-9ef6-8769d5e73293.png)
   

------
IA Page:  http://duck.co/ia/view/python 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

**Comment by moollaza** [comment]
@mrshu good find!

It looks like this is a general parsing error with the way we're handling the first line of the page that mentions the source code file.

We need to update the parser to look for that and handle it better

**Comment by mrshu** [comment]
@moollaza strangely enough, your example does not trigger the Python fathead for me. But I noticed myself that there were multiple occasions when this happened for Python IAs.
