### ISSUE TITLE
PerlDoc: Add more categories to improve regular expression articles

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#366]
### Description

Perl has a bunch of pages on regular expressions (`perlre`, `perlreref`, `perlrebackslash`, to name a few), we should improve regular expression coverage with these pages in the following categories:

- [ ] Modifiers (partially done) - things like `/m`, `/i` etc.
- [ ] Character classes (`[:ascii:]`, `[:digit:]`, `\w` etc.)
- [ ] Metacharacters (e.g., `^`, `.` etc.)
- [ ] Quantifiers (e.g., `*`, `+` etc.)
- [ ] Escape sequences (e.g, `\t`, `\n` etc.) 
- [ ] Assertions (`\B`, `\<` etc.)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/perl_doc

**Comment by jordivador** [comment]
Hi @GuiltyDolphin , I would like to try to help with this improvement, as my first contribution to duckduck :smile:  .

**Comment by GuiltyDolphin** [comment]
@jordivador Please do! Follow the steps outlined and give me a ping if you need any help!

**Comment by pjhampton** [comment]
Hey @GuiltyDolphin!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
