### ISSUE TITLE
Python: Not the right abstract

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#370]
<img width="854" alt="screen shot 2016-09-13 at 12 36 51 pm" src="https://cloud.githubusercontent.com/assets/81969/18482605/cd8698b2-79ae-11e6-9604-4603b06c0002.png">

The right abstract can be found in the first link.

https://duck.co/ia/view/python

**Comment by souravbadami** [comment]
@jagtalon -- Currently, `python re` triggers disambiguations for functions within `re`. I think, it's solved.

**Comment by moollaza** [comment]
https://duckduckgo.com/?q=python+re&ia=meanings

This looks solved to me 👍
