### ISSUE TITLE
Wikipedia: does not refresh

### ISSUE THREAD

**Issue by Rosho123** [duckduckgo/zeroclickinfo-fathead#376]
if a wiki page is changed. the instant answer doesn't display the change.

------
IA Page:  http://duck.co/ia/view/wikipedia_fathead 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by mintsoft** [comment]
@Rosho123 The updates for the wiki answers are updated periodically; they definitely won't update in real-time. Do you know how long ago the updates were made?
