### ISSUE TITLE
MySQL: 

### ISSUE THREAD

**Issue by bibbitybarb1983** [duckduckgo/zeroclickinfo-fathead#382]
------
IA Page:  http://duck.co/ia/view/my_sql 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
@bibbitybarb1983 is there an issue with this Instant Answer you wanted us to know about?

Please update the title/description accordingly, if so.
