### ISSUE TITLE
WikipediaRussian: Text overflows button

### ISSUE THREAD

**Issue by xSOADx** [duckduckgo/zeroclickinfo-fathead#383]
Font doesn't fit right :(
![default](https://cloud.githubusercontent.com/assets/8180837/18809757/ae9ad25c-82ae-11e6-8a90-a928a34e97cb.PNG)
![1](https://cloud.githubusercontent.com/assets/8180837/18809755/8beacf14-82ae-11e6-9c68-10a44796fd8f.PNG)

---

IA Page:  http://duck.co/ia/view/wikipedia_russian 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by mrshu** [comment]
Thanks @xSOADx, we'll take a closer look.
