### ISSUE TITLE
PHP: Switch source to php.net, build new open source FatHead

### ISSUE THREAD

**Issue by VitorVRS** [duckduckgo/zeroclickinfo-fathead#386]
When i search for fopen or fclose on duckduckgo, it show php's function definition.
But there is an "[" (open bracket) "lost" in the end, see on image.

![captura de tela de 2016-09-27 13 35 26](https://cloud.githubusercontent.com/assets/3956573/18882837/48ccd226-84b7-11e6-8dab-391181cfb847.png)
   

------
IA Page:  http://duck.co/ia/view/php 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
@VitorVRS thanks for reporting this.

It looks like this PHP Fathead isn't using the ideal documentation source anymore.

We should really implement a new, open source Fathead for the official PHP documentation. That will solve this and also ensure the Fathead is up to date.

Would you be interested in creating a parser for the PHP docs?

**Comment by VitorVRS** [comment]
Do you mean create an crawler(scrap) for php docs or read from an specific dir?

**Comment by moollaza** [comment]
@VitorVRS yes, a crawler, written in Perl, Python, Ruby, or JavaScript (Node.js)

This repo is full of examples, like perl_doc, python, mdn_css, and ruby fatheads in https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead

**Comment by VitorVRS** [comment]
Ok, i can do it.
I couldn't find on documentation what are the inputs and outputs for this crawler.
Write an parser is easy, my difficult is how to make it work on duckduckgo and how to test.

**Comment by moollaza** [comment]
@VitorVRS documentation is available here: https://docs.duckduckhack.com/resources/fathead-overview.html

If you need any help, feel free to ask questions. I would suggest you [join DDG Slack channel](https://quackslack.herokuapp.com/) where you can ask me, or the community, questions

**Comment by VitorVRS** [comment]
@moollaza Oh thank you! I'll join the slack.
