### ISSUE TITLE
Search `prettyprint json` returns JSON Validator

### ISSUE THREAD

**Issue by meetmangukiya** [duckduckgo/zeroclickinfo-fathead#390]
I'm not sure where it belongs, fathead, IA, move over to wherever it belongs :worried:

**Comment by sahildua2305** [comment]
What were you expecting, @meetmangukiya

**Comment by meetmangukiya** [comment]
JSON validator is not at all what I was expecting. I was looking for pretty printing a JSON file, which should assume it is a valid JSON file :confused:

**Comment by sahildua2305** [comment]
>Enter JSON below, then click the button to get beautified version of JSON if it's valid

I know `JSON Validator` name may be misleading for your use case. I will take it to the Goodies repo to discuss with others. Meanwhile you can use the same `JSON Validator` as it gives you prettyprint version of JSON when it's valid. 😄
