### ISSUE TITLE
Tldr Pages: !tldr bang doesn't work anymore

### ISSUE THREAD

**Issue by apfelchips** [duckduckgo/zeroclickinfo-fathead#392]
The Tldr Pages switched their article base url from https://tldr.ostera.io/#/<command> to just https://tldr.ostera.io/<command>.

So right now the !tldr bang just always ends up at the startpage https://tldr.ostera.io/. 

Should be an easy fix, but the corresponding code isn't public I guess.

------
IA Page:  http://duck.co/ia/view/tldr_pages 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by tagawa** [comment]
Thanks very much for reporting this @apfelchips. I've submitted an update to the URL format with our bang reporting form: https://duckduckgo.com/newbang so will close this issue.
