### ISSUE TITLE
MDN CSS: Improve handling of -moz pseudo element/class redirects

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#394]
MDN has added `-moz` and `-webkit` Pseudo elements and classes, e.g. `::-moz-range-progress` and `:-moz-full-screen`

Some of these article titles contain parentheses in them (e.g. `:-moz-locale-dir(ltr)`) and we're creating redirects for them that aren't correct, e.g. `-moz-locale-dirltr` 

We should add a space between the content in the `()` to create a redirect like `-moz-locale-dir ltr`

---

Similarly, seeing as these are pseudo elements/classes, we should add them to the categories.yml file so that the additional redirects will be created with those keywords and they will be added to the appropriate category pages.

I (@moollaza) have started working on this

/cc @rasikapohankar 

------
IA Page:  http://duck.co/ia/view/mdn_css 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hchienjo

**Comment by rasikapohankar** [comment]
@moollaza I will make changes for the first part
