### ISSUE TITLE
Wikipedia: show latex equation

### ISSUE THREAD

**Issue by luc--** [duckduckgo/zeroclickinfo-fathead#398]
The current version of the wikipedia module can't read the latex equation written between `<math>`. For example with this query : https://duckduckgo.com/?q=Helmholtz+equation.

Why not trying to render it thanks to MathJax ? At least, having a correct render of the LateX form of the formula could be nice...

---

IA Page:  http://duck.co/ia/view/wikipedia_fathead 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
Passing comments to internal team.
