### ISSUE TITLE
C++ Reference Docs: Need a new maintainer

### ISSUE THREAD

**Issue by Mylainos** [duckduckgo/zeroclickinfo-fathead#402]
For now I can't anymore be the maintainer of the C++ Reference Docs fathead, so we need a new maintainer !

@duckduckgo/duckduckhack-contributors would anyone out there be interested ?

Here are the pending issues : #301 #300 and #203.

Good luck !

https://duck.co/ia/view/cppreference_doc

**Comment by sahildua2305** [comment]
Being Language Leader for C++, I'd love to take over this FatHead. @Mylainos 😄

**Comment by Mylainos** [comment]
Great ! Love to see how awesome this FatHead will be ;)

**Comment by ManrajGrover** [comment]
I would like to take this one too. Since, I've been working on multiple Cheat Sheets, I feel I can improve this too.

**Comment by mbad0la** [comment]
@sahildua2305 @Mylainos do let me know if you need some more help. I'd love to be of assistance.

**Comment by sahildua2305** [comment]
@mbad0la sure! Please have a look at the open issues that @Mylainos mentioned. :smile:

**Comment by sahildua2305** [comment]
@ManrajGrover You can improve this fathead without being a maintainer as well 🙂 

However, if you want to be a maintainer to give your inputs, go ahead! It's yours. Thanks for being keen! 😄

**Comment by moollaza** [comment]
I'll give maintainership to @ManrajGrover then 👍 

Thanks everyone 🚀

**Comment by sahildua2305** [comment]
@Mylainos Can you please do some knowledge transfer about this fathead's implementation?

I had a look at the code and it has no parsing logic in the repo. The entire logic for parsing is in the file downloaded from the reference doc link. Am I missing something?

**Comment by sahildua2305** [comment]
@moollaza do you have an idea about this fathead?

**Comment by mintsoft** [comment]
@sahildua2305 https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/c%2B%2B_ref/parse.js

**Comment by sahildua2305** [comment]
Oh! I was looking at [this](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/cppreference_doc/fetch.sh).

Thanks @mintsoft 😄

**Comment by sahildua2305** [comment]
@mintsoft can you confirm whether https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/c%2B%2B_ref is the one which is live?

**Comment by amarlearning** [comment]
@sahildua2305 i think [this](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/c%2B%2B_ref) one is not live!
As far as I checked there is no IA page for this Fathead.

While on the other hand, [this](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/cppreference_doc) one has it's own [IA page](https://duck.co/ia/view/cppreference_doc)

**Comment by moollaza** [comment]
@sahildua2305 @mintsoft it looks like `c++_ref` should be removed. The [cppreference_doc](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/cppreference_doc) is the one that should house the code for this IA, because the dir matches the IA Page ID.

**Comment by sahildua2305** [comment]
@moollaza However, we have to implement the fathead again then. Because `cppreference_doc` isn't hosted in our repo and hence not maintainable. What do you think?

**Comment by moollaza** [comment]
Yes I agree we need to re-implement it. If the original creator is still around (See https://github.com/duckduckgo/zeroclickinfo-fathead/pull/50) then perhaps this can be discussed with him, that we would prefer to maintain the parsing code within our repo moving forward.
