### ISSUE TITLE
HTMLRef: Reverse order of description and code snippet, use Fathead Template, switch source to MDN?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#403]
Programming Fatheads (like CSS and JS) typically provide a description first, and then a code snippet below.

Some of the HTML code snippets are quite large and so the initial view contains to description which looks a little odd.

We should flip the order of the content here to follow suite and make it more clear what the result is about.

Now that we have [Fathead template HTML elements](https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract), we should start using those as well.

---

Finally, seeing as we're using MDN for CSS and JavaScript, I think we should consider using it for the HTML Fathead as well.

Ideally we would parse this page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

---

IA Page:  http://duck.co/ia/view/htmlref 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @lucassmagal

**Comment by akanshgulati** [comment]
@sriranganathan If things are clear to you, you can take the issue. But, we are also thinking to change the source from HTML5Doctor to MDN. Can u do that too? It will be a completely new Fathead then.

**Comment by sriranganathan** [comment]
@akanshgulati I will change the source to MDN. Should I make the changes in the existing fathead or create a new one?

**Comment by akanshgulati** [comment]
@sriranganathan You have to make changes in the existing fathead only so that we can keep the same IA page and as we have to use only one so replacing will be the best way. You can start your work :)
Thanks for volunteering.

**Comment by pjhampton** [comment]
Hey @moollaza!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
