### ISSUE TITLE
YUI3: Switch to use new Fathead Template Elements

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#419]
We now have [Fathead Template Elements](https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract) designed specifically for Programming Fatheads. These are HTML elements that should be added to the output.txt by each Programming Fathead's parsing script(s).

This Fathead should be updated to use the templates:
- The entire abstract should be wrapped in a `<div>` with class `prog__container`
- Any text before/after the code blocks must be wrapped in `<p>` tags
- Any subheadings should be wrapped in a `<div>` with class `prog__sub`

Here is an example:

``` html
<section class="prog__container">
    <p>Creates a JavaScript Date instance that represents a single moment in time.</p>
    <pre>
        <code>
            new Date;
            new Date(value);
            new Date(dateString);
            new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);
        </code>
    </pre>
    <span class="prog__sub">Return Value</span>
    <p>The removed element.</p>
</section>
```

---

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [CSS related searches](https://forum.duckduckhack.com/t/css-search-overview)!

---

IA Page:  http://duck.co/ia/view/yui3 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaganpreet

**Comment by gaganpreet** [comment]
The YUI fathead can possibly be removed. YUI was discontinued 2 years ago and I can't imagine these results being of relevance anymore.

**Comment by sahildua2305** [comment]
Thanks for informing @gaganpreet! I will put a PR to remove this fathead once we get feedback from others.

**Comment by tagawa** [comment]
@gaganpreet @sahildua2305 Thanks for the comments. I agree that this is not very relevant any more. Perhaps we can just close this issue and leave the Fathead as it is without spending time updating it.
