### ISSUE TITLE
Apple Docs: There should be a fathead for watchOS.

### ISSUE THREAD

**Issue by souravbadami** [duckduckgo/zeroclickinfo-fathead#428]
Currently we have fatheads for iOS, macOS & tvOS. It would be great to have a fathead for watchOS.

**Comment by moollaza** [comment]
@souravbadami can you please open a new topic on the forum for this in the [Swift section](https://forum.duckduckhack.com/c/programming/swift)?

That way we can monitor the coverage and organize the work to be done 👍 

/cc @tagawa @MariagraziaAlastra
