### ISSUE TITLE
Python: Create New Redis-py Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#435]
# Redis-py Fathead

Contribute to DuckDuckGo!

![screen shot 2016-10-09 at 8 57 29 pm](https://cloud.githubusercontent.com/assets/8960296/19304432/84ef4e6a-9064-11e6-819e-07c5dda0fe13.png)
### What you will need to know?

Either Python (Preferrable for this mission), Ruby, Perl or JavaScript for Fatheads. You will download the Python redis client source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

https://redis-py.readthedocs.io/en/latest/
### The goal

Help _improve Python language search results_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for Python-related searches by creating new Instant Answers or improving existing ones.

Some relevent examples:
- [Django Built-ins](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/django_built_ins)
- [Redis](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/redis_commands)
- [Python documentation](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/python)
### 

**Fathead Example (Django Built-ins)**

![screen shot 2016-10-09 at 8 59 24 pm](https://cloud.githubusercontent.com/assets/8960296/19304435/8b6f42d6-9064-11e6-80ea-2c923f7ad971.png)
### The steps
- [x] Claim this issue (Comment Below)
- [ ] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [ ] Create the Fathead
- [ ] Create a PR
- [ ] Ping @pjhampton for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/python)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @pjhampton

**Comment by vidhan13j07** [comment]
I want to take up this issue.

**Comment by pjhampton** [comment]
Woohoo! You rock @vidhan13j07!! 

Let me know if you need any help.

**Comment by shanmbic** [comment]
Hey! @pjhampton can i take up this issue too ??sAS @vidhan13j07 is already on it !

**Comment by moollaza** [comment]
@pjhampton thanks for proposing this!

Can you please port this to the Forum though?

We're trying to keep GH Issues for existing IAs. Anything new should be proposed and discussed on the forum, so we can also track it's progress and performance metrics 👍 

Please cross-post the link to the forum topic in @vidhan13j07 's PR as well

**Comment by pjhampton** [comment]
Sure @moollaza! This was the only way (as far as I know) to connect this to hacktoberfest. We can chat more about this off gh :)

**Comment by pjhampton** [comment]
Closing due to lack of searches and developer inactivity. Hopefully, we can take this forward in the future! 👍
