### ISSUE TITLE
NodeJS: Update Parser to latest API

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#436]
NodeJS [JSON reference file](https://nodejs.org/api/all.json) has had some changes to it's structure in latest versions of it's API resulting in the parser not handling the new structure and crashing.

- [ ] Update Parser to be compatible with latest API

Latest  v6.7.0 : https://nodejs.org/api/all.json
Previous structure : https://web.archive.org/web/20150908053932/https://nodejs.org/api/all.json

---

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview)!

------
IA Page:  http://duck.co/ia/view/node_js 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @dhruvbird

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-contributors would any JavaScript developers be interested in fixing this?

You'll ned to look at what has changed in the structure of the NodeJS JSON structure, and update `parse.js` accordingly.

**Comment by VitorVRS** [comment]
I can do it

**Comment by moollaza** [comment]
@VitorVRS awesome! Thanks for volunteering 👍

**Comment by bfmags** [comment]
Thanks @VitorVRS 👍
