### ISSUE TITLE
Apple Docs iOS: 

### ISSUE THREAD

**Issue by FotiosTragopoulos** [duckduckgo/zeroclickinfo-fathead#437]
------
IA Page:  http://duck.co/ia/view/apple_docs_ios 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon 

IA Page: https://developer.apple.com/library/prerelease/content/navigation/#section=Platforms&topic=iOS
[Maintainer] @FotiosTragopoulos

**Comment by moollaza** [comment]
@FotiosTragopoulos is there an issue you wanted to point out with this Instant Answer?

**Comment by FotiosTragopoulos** [comment]
@moollaza if you type Apple Docs iOS in DuckDuckGo search bar the first result is wrong. and there is not IA.

**Comment by moollaza** [comment]
@FotiosTragopoulos the Apple Docs iOS Fathead isn't exactly intended to handle the case when the query matches the IA name, rather it's intended to trigger on keywords from within the actual documentation (e.g. [requestImageForAsset](https://duckduckgo.com/?q=requestImageForAsset&ia=about))

We do have plans to develop a "meta IA" for each search space though that would help users discover the available instant answers that could be relevant.

We haven't started working on those yet, but I believe they would be ideal here.

It looks like our organic results are a little lacking here as well, but we can't fix that on the open source side.

**Comment by FotiosTragopoulos** [comment]
@moollaza Ok I get it. How can I contribute in the project then?

**Comment by moollaza** [comment]
@FotiosTragopoulos sorry for the late reply, I see you've already joined the forum: https://forum.duckduckhack.com

If you're interested in pushing forward one of the current programming languages, please checkout the overview post for the languages to see if there are any projects that need a developer. If not, you're welcome to suggest potential projects and work on those.

If you're just looking to work on anything, checkout the "[needs-developer](https://forum.duckduckhack.com/tags/needs-developer)" tag to see all projects that are waiting for a developer 👍
