### ISSUE TITLE
Apple Docs watchOS: 

### ISSUE THREAD

**Issue by FotiosTragopoulos** [duckduckgo/zeroclickinfo-fathead#438]
------
IA Page:  http://duck.co/ia/view/apple_docs_watchos 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @souravbadami 

IA Page: https://developer.apple.com/library/prerelease/content/navigation/#section=Platforms&topic=watchOS
[Maintainer] @FotiosTragopoulos

**Comment by moollaza** [comment]
@FotiosTragopoulos is there an issue with this Instant Answer you wanted to point out?

**Comment by FotiosTragopoulos** [comment]
Hello, I will be happy to contribute in DuckDuckGo IA. If you type on DuckDuckGo search bar "Apple Docs WatchOS" the first result is not the right result and there is not an IA. Did I get it right?
