### ISSUE TITLE
Create New Flask Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#444]
# Flask Fathead

Contribute to DuckDuckGo!

![screen shot 2016-10-09 at 8 57 29 pm](https://cloud.githubusercontent.com/assets/8960296/19304432/84ef4e6a-9064-11e6-819e-07c5dda0fe13.png)
### What you will need to know?

Either Python (Preferrable for this mission), Ruby, Perl or JavaScript for Fatheads. You will download the Python redis client source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: 
https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

http://flask.pocoo.org/docs/0.11/
### The goal

Help _improve Python language search results_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for Python-related searches by creating new Instant Answers or improving existing ones.

Some relevent examples:
- [Django Built-ins](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/django_built_ins)
- [Redis](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/redis_commands)
- [Python documentation](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/python)

**Fathead Example (Django Built-ins)**

![screen shot 2016-10-09 at 8 59 24 pm](https://cloud.githubusercontent.com/assets/8960296/19304435/8b6f42d6-9064-11e6-80ea-2c923f7ad971.png)
### The steps
- [ ] Claim this issue (Comment Below)
- [ ] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [ ] Create the Fathead
- [ ] Create a PR
- [ ] Ping @pjhampton for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/python)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @pjhampton

**Comment by shanmbic** [comment]
Hey @pjhampton ! I would like to work on this. =D

**Comment by pjhampton** [comment]
All yours @shanmbic!! Thanks!

💛  💙  ❤️  💜  💚

**Comment by shanmbic** [comment]
Hey @pjhampton . I have created a PR for this issue . Could you please review it and suggest improvements. Please do have a look at the output.txt file . Thanks :) 
https://github.com/duckduckgo/zeroclickinfo-fathead/pull/459

**Comment by pjhampton** [comment]
😍  This looks good @shanmbic!!

I will get looking at this over the next couple of days 💙  💛

**Comment by shanmbic** [comment]
@PJhampton Thanks a lot :) !
