### ISSUE TITLE
Python: Create New Jinja2 Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#445]
# Jinja2 Fathead

Contribute to DuckDuckGo!

![screen shot 2016-10-09 at 8 57 29 pm](https://cloud.githubusercontent.com/assets/8960296/19304432/84ef4e6a-9064-11e6-819e-07c5dda0fe13.png)
### What you will need to know?

Either Python (Preferrable for this mission), Ruby, Perl or JavaScript for Fatheads. You will download the Python redis client source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: 
https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

http://jinja.pocoo.org/docs/dev/
### The goal

Help _improve Python language search results_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for Python-related searches by creating new Instant Answers or improving existing ones.

Some relevent examples:
- [Django Built-ins](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/django_built_ins)
- [Redis](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/redis_commands)
- [Python documentation](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/python)

**Fathead Example (Django Built-ins)**

![screen shot 2016-10-09 at 8 59 24 pm](https://cloud.githubusercontent.com/assets/8960296/19304435/8b6f42d6-9064-11e6-80ea-2c923f7ad971.png)
### The steps
- [x] Claim this issue (Comment Below)
- [ ] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [ ] Create the Fathead
- [ ] Create a PR
- [ ] Ping @pjhampton for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/python)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @pjhampton

**Comment by conormag94** [comment]
I'd like to give this one a go if I may 😃

**Comment by pjhampton** [comment]
Hey @conormag94!!

Yeah, definitely. It's all yours! ping me if you need some help / guidance

**Comment by conormag94** [comment]
@pjhampton 

Okay great thanks! I have the basic fathead files set up but I have one initial question actually.

What information should I actually be capturing from the docs?
I'm assuming its the stuff on this page: http://jinja.pocoo.org/docs/dev/templates/

Should I start with [Control Structures](http://jinja.pocoo.org/docs/dev/templates/#list-of-control-structures) just to get started?

**Comment by pjhampton** [comment]
Hey @conormag94,

Sorry for the late reply!! The idea is that there should be only one output.txt file by the end, but yeah. You can start there and we can take it from there 👍 

I recommend taking a look at these two links for a bit more information regarding that file:

https://docs.duckduckhack.com/resources/fathead-overview.html#data-file-format
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/20981499d000c9b5f09eec75d6e086478d884768/lib/fathead/firefox_about_config/output.txt

**Comment by pjhampton** [comment]
Hey @conormag94

Are you still working on this? If not, I can release it back into the wild claimed.

**Comment by conormag94** [comment]
Hi @pjhampton 

I had to put this on hold due to College etc, sorry about that. Its probably best to let someone else work on it as I don't have the time to do it myself at the moment.
