### ISSUE TITLE
Create New Pika Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#446]
# Pika Fathead

Contribute to DuckDuckGo!

![screen shot 2016-10-09 at 8 57 29 pm](https://cloud.githubusercontent.com/assets/8960296/19304432/84ef4e6a-9064-11e6-819e-07c5dda0fe13.png)
### What you will need to know?

Either Python (Preferrable for this mission), Ruby, Perl or JavaScript for Fatheads. You will download the Python redis client source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: 
https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

https://pika.readthedocs.io/en/0.10.0/modules/index.html
### The goal

Help _improve Python language search results_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for Python-related searches by creating new Instant Answers or improving existing ones.

Some relevent examples:
- [Django Built-ins](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/django_built_ins)
- [Redis](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/redis_commands)
- [Python documentation](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/python)

**Fathead Example (Django Built-ins)**

![screen shot 2016-10-09 at 8 59 24 pm](https://cloud.githubusercontent.com/assets/8960296/19304435/8b6f42d6-9064-11e6-80ea-2c923f7ad971.png)
### The steps
- [x] Claim this issue (Comment Below)
- [ ] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [ ] Create the Fathead
- [ ] Create a PR
- [ ] Ping @pjhampton for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/python)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @pjhampton

**Comment by sriranganathan** [comment]
@pjhampton Can I take up this issue?

**Comment by pjhampton** [comment]
Of course you can @sriranganathan!! Let me know if you need any help 😄 

💛  💙  ❤️  💜  💚
