### ISSUE TITLE
JavaScript: Create New AngularJS Fathead

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#471]
# AngularJS Fathead

Contribute to DuckDuckGo!

<img width="852" alt="screen shot 2016-10-21 at 16 36 35" src="https://cloud.githubusercontent.com/assets/3740101/19604348/c45e9520-97ac-11e6-8503-d18e9f94fa3e.png">
### What you will need to know?

Either **JavaScript**, Python, Ruby, or Perl for Fatheads. Bash is also useful. You will download the reference source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: 
https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

https://docs.angularjs.org/api
#### Update Search Json contains partial url for the API source files

https://docs.angularjs.org/js/search-data.json

Example:
path: "api/ng/function/angular.merge",
https://docs.angularjs.org/partials/api/ng/function/angular.merge.html
### The goal

Help _[improve JavaScript language search results](https://forum.duckduckhack.com/t/javascript-search-overview)_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for JavaScript-related searches by creating new Instant Answers or improving existing ones.

Code to some relevant examples:
- [jQuery Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/jquery)
- [NodeJS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/node_js)
- [MDN JS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdnjs)

**Fathead Example (jQuery Reference)**

<img width="892" alt="screen shot 2016-10-21 at 17 06 36" src="https://cloud.githubusercontent.com/assets/3740101/19605229/d8e9a6d4-97b0-11e6-83f4-e10623973e55.png">
### The steps

- [x] Claim this issue (Comment Below)
- [ ] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [x] Create the Fathead (https://duck.co/ia/view/angularjs)
- [ ] Create a PR
- [ ] Ping @bfmags for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/javascript)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @bfmags

---

Instant Answer Page: https://duck.co/ia/view/angularjs

_Thanks to @pjhampton for the template_

**Comment by NamPNQ** [comment]
I would like to work on this.

**Comment by rafaelpadovezi** [comment]
I'm interested too.

**Comment by kousiksatish** [comment]
I am a new contributor and am interested to work on it.

**Comment by NamPNQ** [comment]
@rafaelpadovezi  @kousiksatish Good to hear it

/cc @bfmags Please assign a person do it

**Comment by bfmags** [comment]
@NamPNQ Thanks!
@kousiksatish is working on the Angular 2 Fathead https://github.com/duckduckgo/zeroclickinfo-fathead/issues/472
@rafaelpadovezi you can have this one 👍 

Don't forget to join [The Forum](https://forum.duckduckhack.com/c/programming/javascript) and [DuckDuckHack Slack](https://quackslack.herokuapp.com/) for help/discuss the fathead!

**Comment by rafaelpadovezi** [comment]
@bfmags Ok! Thanks!

**Comment by bfmags** [comment]
@rafaelpadovezi Updated topic. We can use the search json https://docs.angularjs.org/js/search-data.json that contains partial URL to the API source files
