### ISSUE TITLE
JavaScript: Create New Angular 2 Fathead to show doc snippets

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#472]
# Angular 2 Fathead

Contribute to DuckDuckGo!

<img width="852" alt="screen shot 2016-10-21 at 16 36 35" src="https://cloud.githubusercontent.com/assets/3740101/19604348/c45e9520-97ac-11e6-8503-d18e9f94fa3e.png">
### What you will need to know?

Either **JavaScript**, Python, Ruby, or Perl for Fatheads. Bash is also useful. You will download the reference source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: 
https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

https://angular.io/docs/ts/latest/api/
### The goal

Help _[improve JavaScript language search results](https://forum.duckduckhack.com/t/javascript-search-overview)_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for JavaScript-related searches by creating new Instant Answers or improving existing ones.

Code to some relevant examples:
- [jQuery Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/jquery)
- [NodeJS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/node_js)
- [MDN JS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdnjs)

**Fathead Example (jQuery Reference)**

<img width="892" alt="screen shot 2016-10-21 at 17 06 36" src="https://cloud.githubusercontent.com/assets/3740101/19605229/d8e9a6d4-97b0-11e6-83f4-e10623973e55.png">

### The steps
- [x] Claim this issue (Comment Below)
- [ ] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [ ] Create the Fathead
- [ ] Create a PR
- [ ] Ping @bfmags for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/javascript)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @bfmags

---

Instant Answer Page: _To be created by developer_

_Thanks to @pjhampton for the template_

**Comment by NamPNQ** [comment]
I would like to work on this.

**Comment by pjhampton** [comment]
Fatheads are pretty intensive to work on @NamPNQ. I recommend you just work on one for the time being. If that goes well, you should definitely take this up!

**Comment by kousiksatish** [comment]
I am a new contributor and am interested to work on it.

**Comment by NamPNQ** [comment]
@kousiksatish Good to hear it, and you can do it

**Comment by bfmags** [comment]
Thanks @kousiksatish! 👍 Reach out if you need any help

**Comment by kousiksatish** [comment]
@bfmags Thanks...!

**Comment by tagawa** [comment]
Hi @kousiksatish. We updated our documentation recently and two articles that should help with creating this Instant Answer are:
* https://docs.duckduckhack.com/programming-mission/developing-reference-fatheads.html
* https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html

Let us know if you need further help or would like somebody else to take a look.

**Comment by kousiksatish** [comment]
Hi @tagawa... I was half way in progress and I couldn't devote much time into this last few weeks due to some reasons... I will get it done in this week... Thanks for your help... :)

**Comment by kousiksatish** [comment]
Hi @tagawa... I was half way in progress and I couldn't devote much time into this last few weeks due to some reasons... I will get it done in this week... Thanks for your help... :)

**Comment by kousiksatish** [comment]
Hi @tagawa... I was half way in progress and I couldn't devote much time into this last few weeks due to some reasons... I will get it done in this week... Thanks for your help... :)

**Comment by kousiksatish** [comment]
Hi @tagawa... I was half way in progress and I couldn't devote much time into this last few weeks due to some reasons... I will get it done in this week... Thanks for your help... :)

**Comment by kousiksatish** [comment]
Hi @tagawa... I was half way in progress and I couldn't devote much time into this last few weeks due to some reasons... I will get it done in this week... Thanks for your help... :)

**Comment by tagawa** [comment]
No problem @kousiksatish! Didn't mean to put pressure on you.

**Comment by pjhampton** [comment]
Hey @kousiksatish, how are you getting on?

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now 👍
