### ISSUE TITLE
JavaScript: Create New ReactJS Fathead

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#473]
# ReactJS Fathead

Contribute to DuckDuckGo!

<img width="852" alt="screen shot 2016-10-21 at 16 36 35" src="https://cloud.githubusercontent.com/assets/3740101/19604348/c45e9520-97ac-11e6-8503-d18e9f94fa3e.png">
### What you will need to know?

Either **JavaScript**, Python, Ruby, or Perl for Fatheads. Bash is also useful. You will download the reference source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: 
https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

https://facebook.github.io/react/docs/top-level-api.html
https://facebook.github.io/react/docs/component-api.html
### The goal

Help _[improve JavaScript language search results](https://forum.duckduckhack.com/t/javascript-search-overview)_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for JavaScript-related searches by creating new Instant Answers or improving existing ones.

Code to some relevant examples:
- [jQuery Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/jquery)
- [NodeJS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/node_js)
- [MDN JS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdnjs)

**Fathead Example (jQuery Reference)**

<img width="892" alt="screen shot 2016-10-21 at 17 06 36" src="https://cloud.githubusercontent.com/assets/3740101/19605229/d8e9a6d4-97b0-11e6-83f4-e10623973e55.png">
### The steps
- [x] Claim this issue (Comment Below)
- [x] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [x] Create the Fathead
- [x] Create a PR
- [x] Ping @bfmags for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/javascript)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @bfmags

---

Instant Answer Page: https://duck.co/ia/view/react_api_docs

_Thanks to @pjhampton for the template_

**Comment by dip-kush** [comment]
I would like to work on this.

**Comment by bfmags** [comment]
Hi @dip-kush ! You got it! :)

Let me know if you need any help or reach out the [Community Leaders](https://duck.co/help/community/community-leaders) at [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 

Also, the [forum.duckduckhack.com](https://forum.duckduckhack.com/c/programming/javascript) is a great place to discuss Fathead Development

Good luck!

**Comment by bfmags** [comment]
@dip-kush
please take a look at @MariagraziaAlastra comments on https://github.com/duckduckgo/zeroclickinfo-fathead/pull/476
If you can make those changes and create a new PR would be great!
Thanks!

**Comment by dip-kush** [comment]
I will look into it
