### ISSUE TITLE
Java: Update parser to create output.txt articles for class methods

### ISSUE THREAD

**Issue by marti1125** [duckduckgo/zeroclickinfo-fathead#490]
### Description
Add coverage for class methods so we have answers for things like `decimalstyle equals`. 

https://docs.oracle.com/javase/8/docs/api/index.html?java/time/format/DecimalStyle.html

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/java

**Comment by moollaza** [comment]
@marti1125 please don't forget to provide the IA Page link so it's clear which IA this is related to 👍 

I've updated the post by pasting in the ISSUE_TEMPLATE content so the Steps + Resources are there for the developers to see 👍

**Comment by aegis2501** [comment]
Hi, could I work on this?

**Comment by tagawa** [comment]
Hi @aegis2501. That would be great - thank you! If you need any help, feel free to ask questions either here, [in the forum](https://forum.duckduckhack.com/t/improve-java-fathead/963/10) or [on Slack](https://duckduckhack.slack.com).

**Comment by aegis2501** [comment]
@tagawa thank you!

**Comment by aegis2501** [comment]
@tagawa, what should the formatting for the methods look like?

**Comment by tagawa** [comment]
@aegis2501 Sure - I should have added this earlier. Here are a couple of pull requests for very similar issues:
* jQuery: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/561/files
* CSS: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/547/files

Hope that helps!

**Comment by aegis2501** [comment]
@tagawa thanks!

**Comment by tagawa** [comment]
@aegis2501 I think that should be fine, but ideally there should be a `/cover` directory with a text file of all terms that should be covered, so we can use this to test overall coverage.
