### ISSUE TITLE
SASS: Missing newlines in codeblocks

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#492]
Some of the example codes do not have the a newline separating the lines of codes resulting in all the lines being joined instead of each being on its own. 
Example of this is https://duckduckgo.com/?q=sass+opacify&atb=v23&ia=about&iax=1

------
IA Page:  http://duck.co/ia/view/sass 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @VeerpalBrar

**Comment by moollaza** [comment]
@hchienjo this is actually an internal issue -- we will be fixing this. It also affects CSS and other Fatheads

**Comment by MariagraziaAlastra** [comment]
Should be fixed now. Thanks!
