### ISSUE TITLE
SASS: Add coverage for all methods in 'method list' side panel. 

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#494]
### Description
We need to extend the parser to fetch the method list from the [sass documentation](http://sass-lang.com/documentation/). An example instance method is (http://sass-lang.com/documentation/Sass/Tree/Node.html#%3C%3C-instance_method).

You'll need to edit [fetch.sh](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/sass/fetch.sh) and add the [instance methods link](http://sass-lang.com/documentation/Sass/Tree/Node.html) for downloading. 

Then you'll need to edit either https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/sass/parse_functions.py to add the parsing of the instance methods html file. You can also create a new Python script for parsing the instance methods html file, just ensure that you add it to [parse.sh](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/sass/parse.sh) after you are done.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/sass

------

**Comment by moollaza** [comment]
@hchienjo this issue should be re-worded to more clearly describe what the task is -- can you take a look at some of the other issues we've created about increasing coverage and add some explanation of what's involved?

**Comment by pjhampton** [comment]
Closing as this is no longer high priority 👍
