### ISSUE TITLE
SASS: Add coverage for all the classes in the "class list"

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#495]
The methods in the "class list" side panel need to be parsed. Here is how the class list appears on the site:
![class](https://cloud.githubusercontent.com/assets/13175534/19904480/d7307e4a-a083-11e6-86fd-70a29bb67f17.png)

------
IA Page:  http://duck.co/ia/view/sass 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @VeerpalBrar

**Comment by pjhampton** [comment]
Closing as this is no longer high priority 👍
