### ISSUE TITLE
Ruby Fathead Suggestion: Add usage examples to an infobox

### ISSUE THREAD

**Issue by kotoshenya** [duckduckgo/zeroclickinfo-fathead#500]
### Description

For classes, parse out all the usage examples and add them to an infobox. For example the result for ruby array could have an infobox that includes links to articles for "creating arrays", "accessing elements", "obtaining information about an array" and other from this page http://ruby-doc.org/core-2.3.1/Array.html

## Steps to recreate

* Search for “[ruby array](https://duckduckgo.com/?q=ruby+array&ia=about)” or another Ruby class
* An infobox should be shown with relevant links

## People to notify

@jdorweiler @kotoshenya

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/ruby

**Comment by tagawa** [comment]
@koosha-- @mohan08p @Mav7 @Sayanc93 Hi there Ruby developers! We're trying to improve our documentation IA for Ruby developers (example: "[ruby array length](https://duckduckgo.com/?q=ruby%20array%20length&ia=about)")
Would anyone be interested in taking on this issue to add more examples to it?

**Comment by slaterio** [comment]
I'd like to help out here. I'll start with the infobox links then work through more examples.

**Comment by kotoshenya** [comment]
Awesome, thanks so much @slaterio! Let me know if you have any questions, I wrote the script originally so I can talk you through it if anything is unclear 😊

**Comment by moollaza** [comment]
@kotoshenya unfortunately this isn't currently possible ☹️ 

The infobox only shows links to categories the articles is part of OR related articles. Currently we don't support combining those, or external links.

I'd very much like to change this though, as there's no reason why we should limit the InfoBox to only 1 type of information. 

Achieving this will require some big changes internally though.
