### ISSUE TITLE
Apple Docs macOS Bug: Stop triggering on irrelevant search queries

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#501]
### Description
Apple Docs macOS is overtriggering, which means it triggers on queries that are not relevant, and this results in a poor search experience for users.

## Steps to recreate
Some example searches on which it shouldn't trigger:
  - https://duckduckgo.com/?q=skindex&ia=about
  - https://duckduckgo.com/?q=apple+downloads&ia=about
  - https://duckduckgo.com/?q=apple+push&ia=about
  - https://duckduckgo.com/?q=lenient&ia=about

## People to notify
@jagtalon @GuiltyDolphin @souravbadami 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/apple_docs_macos

**Comment by doorknob22** [comment]
I'm interested in taking a crack at this, would testing the fix be confined mainly to running duckpan server apple_docs_ios on codio?
