### ISSUE TITLE
Apple Docs macOS: broaden search results by adding article aliases (redirects)

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#502]
## Description
The [Output.txt](https://raw.githubusercontent.com/duckduckgo/zeroclickinfo-fathead/master/lib/fathead/apple_docs_macos/output.txt) file contains a list of search results for this Instant Answer.

Each row contains a search result, which corresponds to an article in the Apple Docs macOS documentation, and is divided into columns: article title, type, content...

[Learn more about the output.txt file format](https://docs.duckduckhack.com/resources/fathead-overview.html#data-file-format)

For each article title containing symbols in the output.txt file, add an alias (a "redirect") that replaces the symbols with spaces.

## What to do
- Look for all the rows in the output.txt file that have "A" as a type (these will be the article titles)
- Copy them, but replace the symbols with spaces
- Append the resulting list to output.txt

This change will allow the Instant Answer to trigger for more queries, e.g.:

- Searching using the article title "[macos NSData.ReadingOptions](https://duckduckgo.com?q=macos+NSData.ReadingOptions&t=vivaldi&ia=about)" triggers the Instant Answer right now, but this alias should trigger too: [macos NSData ReadingOptions](https://duckduckgo.com?q=macos+NSData+ReadingOptions&t=vivaldi&ia=web) - right now it doesn't because it's not listed in the Output.txt file

- We should also have this alias: [macos getbytes range](https://duckduckgo.com?q=macos+getbytes+range&ia=web) (see the article [here](https://developer.apple.com/reference/foundation/nsdata/1407224-getbytes))

## People to notify
@jagtalon @GuiltyDolphin @souravbadami 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Fork this repository
- [ ] 3) Create a Pull Request

## Resources

- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions

---

Instant Answer Page: https://duck.co/ia/view/apple_docs_macos

**Comment by nikhilsingh291** [comment]
I will take  this task

**Comment by fankee** [comment]
Hi, I would like to take this up if no one else is working on it.

**Comment by souravbadami** [comment]
@fankee -- Please go ahead!

**Comment by BillyBarbaro** [comment]
Hi there,

Is @fankee still working on this issue, or is there any chance I can give it a try?  If so, a couple of quick questions:

1)  Do I only need to modify output.txt, or should I be changing the script that actually does the parsing?
2)  If all I need to do is modify output.txt, should I include the script I use to make this fix with my pull request?

**Comment by moollaza** [comment]
@BillyBarbaro hey there, thanks for offering to help. I believe @snigdha is working on this (based on our conversations) but I see now that it wasn't properly claimed.

To answer your questions though, your point 3 is correct. This task is a little outdated now, but seeing as we have since introduced the `redirects.txt` file we should be using that. Or, you could adjust the parser to create additional redirect entries in the `output.txt`.

**Comment by pjhampton** [comment]
Hey @fankee, are you working on this?
