### ISSUE TITLE
Apple Docs iOS: List all topic titles and language features to help measure coverage

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#504]
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## People to notify
@jagtalon  @souravbadami 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/apple_docs_ios

**Comment by tagawa** [comment]
Just to clarify, this issue requires making a list of keywords in a new text file - no coding is needed.
As an example, there are two similar pull requests for other languages which should be useful for reference:
* jQuery: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/561/files
* CSS: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/547/files
