### ISSUE TITLE
Apple Docs iOS: "more at" link should be more specific

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#505]
### Description
The "more at" link for https://duckduckgo.com/?q=ios+sendAction&t=canonical&atb=v23&ia=about goes to the top of the page for the class. It could instead link to this page https://developer.apple.com/reference/uikit/uicontrol/1618237-sendaction

## People to notify
@jagtalon @souravbadami 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/apple_docs_ios

**Comment by NickCalabs** [comment]
I'll take this

**Comment by MariagraziaAlastra** [comment]
Thanks @NickCalabs!

**Comment by moollaza** [comment]
@NickCalabs let us know if you need any help! The iOS Fatheads are a bit non-standard because of how they work...

**Comment by jagtalon** [comment]
:P

**Comment by NickCalabs** [comment]
Thanks guys, the election delayed me. Getting back to the grind!

**Comment by jigarsingh** [comment]
this feeling is just awesome. I love this earth.

**Comment by pjhampton** [comment]
Hey @MariagraziaAlastra 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
