### ISSUE TITLE
Apple Docs iOS: add coverage for attributes

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#506]
### Description
Add coverage for attributes.
Examples: UIControl isEnabled, UIControl isHighlighted

## People to notify
@jagtalon @souravbadami 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/apple_docs_ios

**Comment by BillyBarbaro** [comment]
I'd like to help with this one.  I can just add the entries to the coverage directory, right?  Or should I include the script I use to pull the info as well?

**Comment by pjhampton** [comment]
Either @BillyBarbaro :-) Have you seen [this perl script Maria wrote](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/utils/extract_articles.pl)?

**Comment by BillyBarbaro** [comment]
@pjhampton Thanks! That's a really neat tool.  Unfortunately the attributes aren't included in the output.txt for iOS docs.

I took a look at the existing parse script, and like the other Apple parse scripts, it uses the docset databases installed with Xcode to scrape the data.  When I went to look for the database, I couldn't find it.

After a little bit of research, I found that with the release of [Xcode 8](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/WhatsNewXcode/introduction.html) (the version I'm running), changed the structure of the databases storing the documentation.  So it seems to me the existing parse scripts for these won't run on the most recent version of Xcode.

If this has been brought up before, just let me know where and I'll take a look at that conversation.  But all that being said, what do you think I should do from here?

**Comment by BillyBarbaro** [comment]
Looks like this might change with #803.  I think this issue would be better addressed once the new apple_docs fatheads are merged.

**Comment by pjhampton** [comment]
Good point, @BillyBarbaro! I have moved this to on hold.
