### ISSUE TITLE
Swift Docs: fetch and parse the Operators section

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#508]
### Description
Fetch and parse the articles in the Operators section of [Swiftdocs](http://swiftdoc.org/v2.2/), and add them to the Output.txt file.
<img width="1209" alt="screen shot 2016-11-03 at 9 14 00 am" src="https://cloud.githubusercontent.com/assets/3652195/19967244/e2a65f42-a1a5-11e6-94d6-cf8c6a305159.png">

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/swiftdocs

**Comment by ahetawal-p** [comment]
Is this still needed ? I see the operators already present in the output.txt for swiftdocs.
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/swiftdocs/swift/output.txt

**Comment by moollaza** [comment]
@ahetawal-p looks like you're right! This must have been addressed already 👍
