### ISSUE TITLE
Swift Docs: List all topic titles and language features to help measure coverage

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#509]
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/swiftdocs

**Comment by tagawa** [comment]
Just to clarify, this issue requires making a list of keywords in a new text file - no coding is needed.
As an example, there are two similar pull requests for other languages which should be useful for reference:
* jQuery: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/561/files
* CSS: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/547/files

**Comment by altern8tif** [comment]
@tagawa sign me up for this.

Just to clarify, are the `.txt` files used for tests in `t/validate_fathead.t` file?  Are the topic titles/language features meant to be generated manually?

**Comment by tagawa** [comment]
Hi @altern8tif (and happy new year!). Thank you for taking this up. Yes, the `.txt` files will be used for tests. Because of this, the topic titles/language features should be generated manually. This could be by scraping from the official docs, for example. Ideally the Fathead will already cover everything in the generated lists but doing it manually in this way will enable us to verify it.

**Comment by altern8tif** [comment]
@tagawa noticed that the current fathead implementation is for Swift 2.2.  Should I be generating the `.txt` file for Swift 3 instead?

**Comment by pjhampton** [comment]
Sorry for the late reply, @altern8tif. Yes, please!

**Comment by altern8tif** [comment]
@pjhampton sweet, thanks!  Will send a PR across soon.

**Comment by altern8tif** [comment]
Noticed that the update to Swift 3.1 is held up (#790).  I'll hold off till that's resolved first.

**Comment by pjhampton** [comment]
Hey @MariagraziaAlastra 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
