### ISSUE TITLE
NodeJS Bug: incorrect "more at" link

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#512]
### Description
The "more at" link is incorrect. E.g. for the query "node http.Agent" the link is http://nodejs.org/api/all.html#all_http.agent, which doesn't exist and redirects to the docs main page. Instead it should be https://nodejs.org/api/all.html#http_class_http_agent.

## Steps to recreate
- [node http.Agent](https://duckduckgo.com/?q=node+http.Agent&atb=v32-1__&ia=about)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by jarrodthibodeau** [comment]
I can grab this!

**Comment by tagawa** [comment]
That would be great - thank you very much @jarrodthibodeau! Please ask for help if you need assistance, or send any questions to the #ask-anything channel in [Slack](https://duckduckhack.slack.com).
