### ISSUE TITLE
NodeJS: add common redirects (aliases)

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#513]
### Description
Add common redirects, for example replace symbols such as dots with spaces; e.g. "http.Agent" should have a "http agent" redirect.

## Steps to recreate
- [node http.Agent](https://duckduckgo.com/?q=node+http.Agent&atb=v32-1__&ia=about) triggers
- [node http agent](https://duckduckgo.com/?q=node+http+agent&atb=v32-1__&ia=software) doesn't trigger

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by jarrodthibodeau** [comment]
Hello! I would like to take a look at this issue if that is alright?

**Comment by tagawa** [comment]
Hi @jarrodthibodeau. That would be great, thank you! 
There are some resources listed in the description above, but if you need feel free ask any questions here, [on the forum](https://forum.duckduckhack.com/t/improve-nodejs-fathead/179) or in the [Slack chat](https://duckduckhack.slack.com).
