### ISSUE TITLE
NodeJS: shorter paragraphs and more visible examples

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#514]
### Description
Currently we show the whole description for each article, which results in a cluttered and often too wordy answer, and the examples usually are too far down and require the user to expand the content. We should instead show the first sentence and then the examples when available.

<img width="966" alt="screen shot 2016-11-03 at 2 21 59 pm" src="https://cloud.githubusercontent.com/assets/3652195/19979457/ea66ef96-a1d0-11e6-99ed-d2e8a5d7a035.png">

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by ahetawal-p** [comment]
I can take a look at this one..
