### ISSUE TITLE
NodeJS: List all topic titles and language features to help measure coverage

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#515]
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## Get Started
- [x] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by tagawa** [comment]
Just to clarify, this issue requires making a list of keywords in a new text file - no coding is needed.
As an example, there are two similar pull requests for other languages which should be useful for reference:
* jQuery: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/561/files
* CSS: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/547/files

**Comment by marteki** [comment]
I'd like to take this one.

**Comment by abijith-ka00** [comment]
if we manage c++ javascript is simple

**Comment by tagawa** [comment]
Hi @marteki. That's very kind of you - thank you!

**Comment by pjhampton** [comment]
Hey @marteki,

How are you getting on? Do you have any questions? 😄

**Comment by pjhampton** [comment]
Hey @marteki,

Due to inactivity, I'm going to open this issue back up for claiming. Please feel free to jump back in if you find the time.

**Comment by VirgaSenis** [comment]
I would like to work on this.

**Comment by pjhampton** [comment]
Awesome! Thanks so much @VirgaSenis 😄

**Comment by VirgaSenis** [comment]
I'm new to the whole thing, so may I get a confirmation that this is correct?
` assert
assert.deepEqual
assert.deepStrictEqual
assert.doesNotThrow
assert.equal
assert.fail
assert.ifError
assert.notDeepEqual
assert.notDeepStrictEqual
assert.notEqual
assert.notStrictEqual
assert.ok
assert.strictEqual
assert.throws
Buffer.alloc
Buffer.allocUnsafe
Buffer.allocUnsafeSlow
Buffer.byteLength
Buffer.compare
Buffer.concat
Buffer.from
Buffer.from
Buffer.from
Buffer.from
Buffer.isBuffer
Buffer.isEncoding
buf.compare
buf.copy`

**Comment by VirgaSenis** [comment]
I just made a pull request. Would you mind checking if what I'm doing is correct?

**Comment by pjhampton** [comment]
@VirgaSenis Hmm, I can't see it. Can you please create a PR and reference this issue? 😄

**Comment by VirgaSenis** [comment]
https://github.com/VirgaSenis/zeroclickinfo-fathead/blob/coverage/lib/fathead/node_js/cover/functions.txt
