### ISSUE TITLE
jQuery: broaden search results by adding article aliases (redirects)

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#516]
### Description
 Add redirects using each of the article's categories + the method name. E.g, the article "jQuery.get" is in the Ajax category, so we should add an "ajax get" redirect.
You can find the categories at the top of each article's page, under the title:
<img width="427" alt="7cdf39eaceaaf11888dc8ca7798284b13c55b9ca" src="https://cloud.githubusercontent.com/assets/3652195/19979957/a87d8c50-a1d2-11e6-9290-beb81e778b97.png">
<img width="596" alt="bb47167ebdc9fc21ca960b270193765b682d88ba" src="https://cloud.githubusercontent.com/assets/3652195/19979960/abfe73d0-a1d2-11e6-95e4-df5d38f0a6dd.png">

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/jquery

**Comment by rajzshkr** [comment]
@MariagraziaAlastra I can do this.

**Comment by MariagraziaAlastra** [comment]
Awesome, thanks @rajzshkr!
