### ISSUE TITLE
jQuery: Create separate category pages depending on an articles master category

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#517]
### Description
Use different categories pages depending on the article's master category: right now all the articles are under "jquery methods" but it might be more useful to divide them and have, e.g, a "CSS" category page, as well as "Attributes", "Core", "Data"...

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/jquery

**Comment by rafaelpadovezi** [comment]
I'm interested in this issue.

**Comment by MariagraziaAlastra** [comment]
Awesome, thanks @rafaelpadovezi!

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra I saw that multiple categories are possible, so I decided to parse all categories from jQuery. There are total 61 categories. Examples of categories created: **_Basic Css Selectors_**, **_Effects_**, **_Global Ajax Event Handlers_**, Dimensions and **_General Attributes_**.

**Comment by MariagraziaAlastra** [comment]
Sounds good @rafaelpadovezi :smile:
