### ISSUE TITLE
PHP Bug: bracket shows up after code block

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#519]
### Description
A square bracket shows up after the code here:
<img width="930" alt="screen shot 2016-11-03 at 2 44 12 pm" src="https://cloud.githubusercontent.com/assets/3652195/19980352/03186620-a1d4-11e6-85be-f34c610b28ef.png">

## Steps to recreate
[php array merge](https://duckduckgo.com/?q=php+array+merge&ia=about)

## People to notify
@VitorVRS 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/php

**Comment by VitorVRS** [comment]
The PHP fathead was rewrited and are still in beta.
You can see it here: https://beta.duckduckgo.com/?q=php+array+merge&ia=about

**Comment by MariagraziaAlastra** [comment]
Thanks @VitorVRS!
