### ISSUE TITLE
Apple reference missing stuff

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-fathead#52]
Like NSStatusItem

https://duck.co/ia/view/ask_different

**Comment by jagtalon** [comment]
Trying to resolve this in #278 (Apple Docs) and #271 (Swift Docs)

**Comment by jagtalon** [comment]
This should be working btw 
<img width="623" alt="screen shot 2016-07-28 at 2 31 43 pm" src="https://cloud.githubusercontent.com/assets/81969/17224707/1298e422-54d0-11e6-8a23-d692f7c8bdff.png">
