### ISSUE TITLE
PHP: add examples and return values

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#520]
### Description
Add examples and return values. For example, [fopen](https://duckduckgo.com/?q=php+fopen&t=canonical&ia=about) could include the examples at the end of the docs page http://php.net/manual/en/function.fopen.php#refsect1-function.fopen-examples

## People to notify
@VitorVRS 

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/php

**Comment by Donkeymasher** [comment]
Just to be clear you want to parse the examples in the retrive document and append it to the end of the source file

**Comment by MariagraziaAlastra** [comment]
Hey @Donkeymasher! 
The examples in the document should be part of the content shown by the IA, which means they should be included in the output.txt file for each article.
You can read more about Fatheads and the correct format of the output.txt file [in the docs](https://docs.duckduckhack.com/resources/fathead-overview.html#data-file-format).

Thanks!

**Comment by VitorVRS** [comment]
Hey @MariagraziaAlastra i would like to do this.
I was reading the php documentation and noticed that there are some pages with more than one examples.
We should show them all?

Ex.: https://secure.php.net/manual/en/function.file-get-contents.php

**Comment by MariagraziaAlastra** [comment]
Hey @VitorVRS! We can start showing the first one and see if it improves the content already. I'm afraid adding all of them might make it too lengthy.
Thanks!

**Comment by VitorVRS** [comment]
@MariagraziaAlastra sorry for the lateness... 

I've already finished the parser, just need your thoughts about the following issues to open my PR.

## Functions without examples

Were found 2475 functions without examples section, i didn't saw every single one, just a few.

---

## The following functions doesn't have an concrete example, just an link to another function:

* maxdb-more-results
* maxdb-options
* maxdb-store-result
* php-check-syntax
* readline-callback-handler-remove
* readline-callback-read-char
* xmlrpc-decode
* xmlrpc-is-fault

---

## Unpadronized examples information

The following functions doesn't have an padronized example area on documentation (some doesn't even have php code):

* apd-breakpoint
* gopher-parsedir
* mysql-fetch-array
* mysql-info
* parse-ini-file
* yaz-search
* yaz-sort

---

## Others

The following function doesn't have an proper title/description, but will be taken without them:

* bcpowmod
* imagepng
* strnatcmp
