### ISSUE TITLE
Python: List all topic titles and language features to help measure coverage

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#522]
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

**Comment by Hestben** [comment]
> Create `cover/` directory containing text files that list all the topic titles and language features to cover.
Should we really list **all** the topics? For the Python Fathead, I see this could easily be unmaintainable to handle manually. We could probably do it automatically, but if it is close to the fathead mining strategy, it might not provide much use.
Another strategy would to list one topic for each special case that is mined in the fathead.

**Comment by MariagraziaAlastra** [comment]
@Hestben this is currently the default way of testing a Fathead intended coverage, so yeah it should be as complete as possible. It's not about spotting bugs, bug just about verifying if we have all the most important information served by the IA, or whether there are gaps in it.

**Comment by mr-karan** [comment]
I'd like to take this on

**Comment by tagawa** [comment]
Great! Thank you very much @mr-karan. There are a couple of similar PRs here which might help:
* jQuery: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/561
* CSS: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/547

**Comment by pjhampton** [comment]
Hey @mr-karan! How are you getting on? 😄  Do you have any questions?

**Comment by mr-karan** [comment]
got a lil busy this, will try to wrap it up by this weekend @pjhampton

**Comment by pjhampton** [comment]
That's cool @mr-karan 😄  Thanks for the update!

**Comment by Logan1x** [comment]
@MariagraziaAlastra @pjhampton does this issue is not done till now if its available i would like to take this.

**Comment by pjhampton** [comment]
TBH @Logan1x we can probably move away from this as it is no longer a priority. Checkout duckduckhack.com/issues to have the most impact! ❤️  

Thanks everyone!
