### ISSUE TITLE
Python Bug: missing parentheses in code blocks

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#523]
### Description
missing parentheses in some method code blocks
https://duckduckgo.com/?q=python+unittest+teardown&atb=v23&ia=about1
should be `tearDown()`

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

**Comment by moollaza** [comment]
@MariagraziaAlastra this may be an internal issue -- @souravbadami mentioned that the output.txt contains the `()`, so it's likely we're removing it internally.

**Comment by himanshugarg** [comment]
Yes I also confirmed that output.txt does have parentheses. 

```
unittest.TestCase.tearDown      A                                                                               <section class="prog__container"><p>Method called i
mmediately after the test method has been called and the result recorded. This is called even if the test method raised an exception, so the implementation in subc
lasses may need to be particularly careful about checking internal state. Any exception, other than AssertionError or SkipTest, raised by this method will be consi
dered an additional error rather than a test failure (thus increasing the total number of reported errors). This method will only be called if the setUp() succeeds
, regardless of the outcome of the test method. The default implementation does nothing.</p><pre><code>tearDown()</code></pre></section>    https://docs.python.org
/3.5/library/unittest.html#unittest.TestCase.tearDown
```

**Comment by souravbadami** [comment]
@himanshugarg -- The internal bugs are fixed internally by the _duckduckgo_ team.

**Comment by pjhampton** [comment]
I assume there is an issue in Github Enterprise, so I'm going to close this down for now.
