### ISSUE TITLE
Python: add coverage for more classes

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#526]
### Description
Add coverage for more classes.

https://duckduckgo.com/?q=python+subprocess&atb=v23&ia=meanings
should show a summary of the class and an infobox link to this category page

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

**Comment by Hestben** [comment]
I am considering taking on this issue, but I have a question regarding
> should show a summary of the class and an infobox link to this category page

Is it meant, rather than the current displaying of "Meanings", there should be an info box with an overview of the class, and then a link to the python documentation for this class?
The current view of the example 
![python_subprocess](https://cloud.githubusercontent.com/assets/22500915/20039018/80ec645a-a43d-11e6-8adc-4b6a6907a262.png)
I guess the question is to @jdorweiler who brought up the issue in the thread https://forum.duckduckhack.com/t/python-docs-fathead/176/23

**Comment by jdorweiler** [comment]
@Hestben I was thinking of something like the [ruby](https://duck.co/ia/view/ruby) IA where it shows a short summary about the class and a link in the infobox to the class methods. 

https://duckduckgo.com/?q=ruby+array&t=canonical&atb=v23&ia=about&iax=1

**Comment by Hestben** [comment]
@jdorweiler So, do you suggest it should have categories? 
So, a module, like "subprocess" should be a category? Then, the view would be similar to using "Disambiguation" entry type, like the example in the [docs](https://docs.duckduckhack.com/resources/fathead-overview.html):
https://duckduckgo.com/180/c/Css_pseudo_elements?ia=list

**Comment by jdorweiler** [comment]
Here's an example of what I was thinking of

![selection_043](https://cloud.githubusercontent.com/assets/1882892/20350280/4b497da0-abdc-11e6-81d9-7777c96e7dc2.jpg)

**Comment by Hestben** [comment]
@jdorweiler Yes, I can see that would be a nice way to display it. But the links under "Related Topics" seems to be categories, according to the docs. And we would want to map from a python class to its functions, and categories would map from the python functions to the python class.

**Comment by jdorweiler** [comment]
The links under related topics could go to the actual abstract pages. For example `subprocess.run` would link here https://duckduckgo.com/35/subprocess.run?iax=1&ia=about

**Comment by Hestben** [comment]
@jdorweiler Yes, I can see that. The problem I am working with now is where to put the actual links in the fathead output fields. Which field should be used? How are the links supposed to look like? From my limited understanding of how categories work, it looks to me that they map the other way around.
I have yet not found an example where the field "related topics" is displayed, and not "categories".

**Comment by jdorweiler** [comment]
@Hestben you're right. For some reason I though we could do this. I just saw this comment on the same idea https://github.com/duckduckgo/zeroclickinfo-fathead/issues/500#issuecomment-261112053

**Comment by Hestben** [comment]
@jdorweiler So, how do we continue this? Should we await a change in the InfoBox to be able to handle this information, or is there some other way we could display this?

**Comment by Hestben** [comment]
I just got a hint from @tagawa of this query: https://duckduckgo.com/?q=python+print&ia=about
There, the output looks like we would want it to be.
Looking in output.txt, I see, that the output type for the query "python print" is "A", and has "print" as category. The related topic displayed ("python2 print") is using "print" as category.
Thus, we could iterate through the things we want to display in "Related Topics" and add a category to it.
Is this an acceptable solution, or is it possible we would add a lot of categories, that will interfere with other searches?

**Comment by jdorweiler** [comment]
@Hestben  I'm going to see what changes need to be made to allow the infobox to work with non-category pages.
