### ISSUE TITLE
MDN JS: List all topic titles and language features to help measure coverage

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#527]
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdnjs

**Comment by mohitgupta07** [comment]
I'll like to work on this issue. can i begin?

**Comment by bfmags** [comment]
Hi @mohitgupta07 you can go ahead! 
If you haven't already, don't forget to join DuckDuckHack Forum and DuckDuck Slack channel.
Let me know if you need any help :)

**Comment by mohitgupta07** [comment]
How to get added into this organization on github?

**Comment by MariagraziaAlastra** [comment]
@mohitgupta07 I just invited you to the duckduckhack-contributors team, you just need to accept :smile:

**Comment by mohitgupta07** [comment]
Yeah Thanks! At the moment when I was just sent the reply ,you invited me
so I couldn't take my comment back :-p . Thanks and I'll love to
contribute. My first open source contribution :-)

**Comment by tagawa** [comment]
Just to clarify, this issue requires making a list of keywords in a new text file - no coding is needed.
As an example, there are two similar pull requests for other languages which should be useful for reference:
* jQuery: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/561/files
* CSS: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/547/files

**Comment by pjhampton** [comment]
Hey @mohitgupta07

How are you getting on? 😄

**Comment by pjhampton** [comment]
Hey @bfmags 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.
