### ISSUE TITLE
MDN JS: List all available articles for each error type

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#529]
### Description
The Errors section could certainly cover more, but the article titles are super specific; we could add disambiguations for each error type, linking to all the different articles for it. E.g. we would have a disambiguation for "SyntaxError" and have all of the following articles listed:

<img width="316" alt="b53b4dee4c2c02ea33a2f703e24809733fc5fc7b" src="https://cloud.githubusercontent.com/assets/3652195/19981819/dbd3eec6-a1d9-11e6-9419-e5a18ff67635.png">

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdnjs

**Comment by mbad0la** [comment]
@bfmags should I take this up? I'd be extensively needing your help though 😛

**Comment by bfmags** [comment]
Sounds good! :D

**Comment by pjhampton** [comment]
Hey @mbad0la :) how are you getting on?

**Comment by mbad0la** [comment]
Hi @pjhampton 

@bfmags and I have been a bit preoccupied lately, but we'll get to this soon. Sorry for any inconvenience.

**Comment by pjhampton** [comment]
No inconvenience at all 😄  just making sure you aren't stuck!

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now 👍
