### ISSUE TITLE
MDN JS: show the first example in the article

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#530]
### Description
For some articles (see [this query](https://duckduckgo.com/92/Headers.get()?iax=1&ia=about) ) we only show the syntax; instead, we should always show the first example box (maybe in addition to the syntax). 
<img width="969" alt="screen shot 2016-11-03 at 3 29 48 pm" src="https://cloud.githubusercontent.com/assets/3652195/19981962/6ceb417a-a1da-11e6-957f-8933aa895c51.png">

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdnjs

**Comment by itai421** [comment]
I will try to fix it

**Comment by MariagraziaAlastra** [comment]
Thanks @itai421! 😄

**Comment by itai421** [comment]
To make sure I understood the problem.
The intended result for the query above is:
```javascript
    var myHeaders = new Headers(); // Currently empty
```
(because this is the first code box at the Example section).

I find it a little bit strange for two reasons:

1.  I did not found queries that output this kind of results (and a quick look at the code made my think it was never written to do this).
2. The query above is an excellent example showing that in many cases the MDN example section contains more than one code box. 

So how should I continue from here?

**Comment by MariagraziaAlastra** [comment]
@itai421 Hey, yeah currently the parser just fetches the content in the syntax box. In order to replace it with the example, you'd need to parse the content of the first example box. 
Doesn't matter if there are more examples, we'd just like the first one. Ideally it would make the IA content more useful :) 

//cc @bfmags

**Comment by itai421** [comment]
O.K, so it took me a while, but I think I am starting to get it.
I notice that the this problem occurs only when querying *Web APIs*  and I found a way to extract the first example.
Now, I am facing a problem showing examples contains both *HTML* an *JavaScript*. 
The solution I found is to display them both in the same `code` tag with comments as separators , this looks like this:

![duck](https://cloud.githubusercontent.com/assets/9339779/21204192/c4f8ceec-c25e-11e6-810b-120bdbff2654.png)

So, what do you say? is it good?

**Comment by bfmags** [comment]
@MariagraziaAlastra @itai421 
Would splitting in two separate code areas work?

<img width="721" alt="screen shot 2016-12-15 at 10 32 20" src="https://cloud.githubusercontent.com/assets/3740101/21220649/cdd661a2-c2b1-11e6-99a6-f98474214630.png">

**Comment by itai421** [comment]
WOW, that looks great :) 
I did not found a way to output a result with two examples and an example description or title for each of them, how did you that?

**Comment by bfmags** [comment]
Thanks! :) 

I just hacked in DevTools. Basically, when there's HTML and JS code, the markup changes to have the extra `<span class="prog__sub">HTML Content</span><code>html code here</code><span class="prog__sub">Javascript Content</span>`

**Comment by itai421** [comment]
Oh I see, I will change the `parse.py` to do that, Thanks :)
