### ISSUE TITLE
Python: Create New PEP Fathead

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#540]
# Create a new Python PEP Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**More Info:**
Our list of unanswered queries recently surfaced that we have queries for Python PEP's, by number, that currently don't show an instant answer.

We can create a Fathead by parsing the PEP Index so queries like "pep 249" or "python pep 20" can show the some information about the PEP such as the abstract, title, authors, etc.

**Data source**: https://www.python.org/dev/peps/

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [x] 5) Create the Fathead
- [x] 6) Create a Pull Request
- [x] 7) Ping @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by pjhampton** [comment]
What exactly do you guys want to display here when someone triggers this FH. Just the abstract with a link to the full spec?

For example

**Query:** _pep 498_

**Response:** 

Python supports multiple ways to format text strings. These include %-formatting [1] , str.format() [2] , and string.Template [3] . Each of these methods have their advantages, but in addition have disadvantages that make them cumbersome to use in practice. This PEP proposed to add a new string formatting mechanism: Literal String Interpolation. In this PEP, such strings will be referred to as "f-strings", taken from the leading character used to denote such strings, and standing for "formatted strings".

This PEP does not propose to remove or deprecate any of the existing string formatting mechanisms.

f-strings provide a way to embed expressions inside string literals, using a minimal syntax. It should be noted that an f-string is really an expression evaluated at run time, not a constant value. In Python source code, an f-string is a literal string, prefixed with 'f', which contains expressions inside braces. The expressions are replaced with their values. Some examples are:
```
>>> import datetime
>>> name = 'Fred'
>>> age = 50
>>> anniversary = datetime.date(1991, 10, 12)
>>> f'My name is {name}, my age next year is {age+1}, my anniversary is {anniversary:%A, %B %d, %Y}.'
'My name is Fred, my age next year is 51, my anniversary is Saturday, October 12, 1991.'
>>> f'He said his name is {name!r}.'
"He said his name is 'Fred'."
```
A similar feature was proposed in PEP 215 . PEP 215 proposed to support a subset of Python expressions, and did not support the type-specific string formatting (the __format__() method) which was introduced with PEP 3101 .

**Comment by pjhampton** [comment]
## IA Page

https://duck.co/ia/view/pep

**Comment by moollaza** [comment]
@pjhampton it looks like many of the pep's have different amounts and content, but they all seem to at least have an abstract, and metadata such as the author(s), written title, status, etc.

I think those would all be useful to show?

**Comment by pjhampton** [comment]
Yeah, I agree @moollaza. I have opened a discussion on the forum here: https://forum.duckduckhack.com/t/new-pep-fathead/1364
