### ISSUE TITLE
The default set of keyboard shortcuts to use Codio efficiently

### ISSUE THREAD

**Issue by selfiz** [duckduckgo/zeroclickinfo-fathead#541]
Explains how to Tri-Force on Windows, Mac, and Linux Computers

------
IA Page:  http://duck.co/ia/view/twentyfour 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
Not getting this. If I'm mistaken we can reopen and discuss this.
