### ISSUE TITLE
MDN CSS: -webkit-* properties should have redirects when no standalone page exists

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#545]
### Description
There are several `-webkit-*` properties that we don't show answers for, because on MDN those properties simply redirect to other pages.

E.g. `-webkit-transform` is just a link to `transform` on the [Webkit Extensions index](https://developer.mozilla.org/en-US/docs/Web/CSS/Webkit_Extensions)

If we detect that the linked page for the property maps to a link we already have, we should create a redirect entry in the `output.txt`.

That way a search for "webkit-transform" will show an Instant Answer for the CSS `transform` property.

## People to notify
@rasikapohankar

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  http://duck.co/ia/view/mdn_css 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hchienjo

**Comment by rasikapohankar** [comment]
I will take this up @moollaza.
