### ISSUE TITLE
PHP: Link goes to manual search results instead of the manual for the function  displayed in infobox

### ISSUE THREAD

**Issue by Targren** [duckduckgo/zeroclickinfo-fathead#546]
To reproduce:
  1. query "php <function>", e.g."[php array_merge](https://duckduckgo.com/?q=php+array_merge)"
  2. Click either the "array_merge" link or the "More at PHP Manual" link in the infobox

Expected Result:  Linked to http://php.net/manual/en/function.array-merge.php

Observed Result: Linked to http://php.net/results.php/?q=array_merge

------
IA Page:  http://duck.co/ia/view/php 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by moollaza** [comment]
@Targren thanks this has been fixed. Somehow the old Fathead data was deployed live. The new Fathead data has been re-deployed.

**Comment by Targren** [comment]
It looks like this bug has re-appeared. 

Example Query: "php file_get_contents"

The widget link opens http://php.net/results.php/?q=file_get_contents  instead of http://php.net/manual/en/function.file-get-contents.php
