### ISSUE TITLE
Python: the searches "python replace" and "python string replace" don't show results for this IA

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#548]
### Description

I wanted to check the syntax for Python's `replace()` method and noticed we're not showing any results for the following searches:

- [python string replace](https://duckduckgo.com/?q=python+string+replace)
- [python string.replace](https://duckduckgo.com/?q=python+string.replace)
- [python replace](https://duckduckgo.com/?q=python+replace)

Similarly `python capwords` has no answer, but `python string.capwords` does.

The way the code for this Instant Answer works is, it fetches the articles from the docs and then creates two different files containing the article titles, output_py2.txt for Python 2, and output_py3.txt for Python 3.

The two files get then combined into the output.txt file.

After some investigation, looks like we have entries for the searches above in the output_py2.txt file, but they're not being copied to the output.txt file.

### What to do
[On these lines](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/python/parse.py#L371-L387) we loop through the articles in output_py3.txt and compare them to the ones in output_py2.txt, but doing this obviously leaves out articles that are exclusively in output_py2.txt.

Change that part of the code to append the missing output_py2.txt articles to output.txt.

### People to Notify
@pjhampton 

------
IA Page:  http://duck.co/ia/view/python 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

**Comment by Hestben** [comment]
> Similarly python capwords has no answer, but python string.capwords does.
I have noticed that issue in PR #538 
When python2 and python3 has different abstracts, the redirect is removed. We should rather display the python3 answer and link to the python2 answer.

Regarding the string replace. In python3, string is a built in, and called str, and most string functions are defined as 'str.<function>', so the replace function in python3 is called 'str.replace(...)'.

Per default, we are only displaying the python3 functions, and when they differ in the python2, we have a respective python2 IA. Functions in python2 not available in python3 will not have an IA.

**Comment by PuneetGupta123** [comment]
@moollaza Can I work on this?

**Comment by Hestben** [comment]
@PuneetGupta123 I looked at the queries above, and now all works. The [python replace](https://duckduckgo.com/?q=python+replace) displays the Q/A answer, but under [Meanings](https://duckduckgo.com/?q=python+replace&ia=meanings), there is an disambiguation.
One caveat is that str.replace is not in the disambiguation list for general python, but I see no easy fix for that right now. In [python2 replace](https://duckduckgo.com/?q=python2+replace&ia=meanings) string is still a module, and the disambiguation includes that, but in python3 string has become a built-in, and is called 'str'.

**Comment by PuneetGupta123** [comment]
Ok :)

**Comment by Hestben** [comment]
...and as a continuation of my comment above 2 days later. @moollaza We should probably close this issue.
