### ISSUE TITLE
Java: Create New Apache Commons Fathead

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#549]
# Create a new Apache Commons Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

#### More Info
The list of commons components is available at http://commons.apache.org. Each component has it's own JavaDoc that can be parsed. The JavaDocs are available at http://commons.apache.org/proper/commons-{{component_name}}/apidocs/index.html (e.g. http://commons.apache.org/proper/commons-math/apidocs/index.html)

For each component's packages, we should scrape the **Interfaces**, **Classes**, **Enums**, etc. 

**Data source**: http://commons.apache.org/ 

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @marti1125 for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by nikhilsingh291** [comment]
I can to this. Assign me

**Comment by marti1125** [comment]
Hi @nikhilsingh291 it's yours 👍 
please check this PR for have an good idea how to can create a Fathead
https://github.com/duckduckgo/zeroclickinfo-fathead/pull/575

**Comment by moollaza** [comment]
@nikhilsingh291 you're assigned!

**Comment by pjhampton** [comment]
Hey @nikhilsingh291! How are you getting on? Do you have any questions?

**Comment by nikhilsingh291** [comment]
Sorry it completely went off my mind. I'll finish this in 2-3 days. @pjhampton can I use a python script to download the source files as the JavaDocs are spread across multiple pages ? A recursive download will take a lot of space and will download extra files.

**Comment by pjhampton** [comment]
Hey @nikhilsingh291, that's cool! just checking in 😄 
Yeah, you can take that approach 👍

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now 👍
