### ISSUE TITLE
Python: Create New Tkinter Fathead

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#550]
# Create a new Tkinter Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: https://docs.python.org/2/library/tkinter.html

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by dejbug** [comment]
hey ho let's go! :smile:

**Comment by dejbug** [comment]
Looking through the source, I just noticed that it has precious little info. It seems the authors intended the reader to be looking at the non-python Tk docs in parallel. [iow] This seems to be a "how to read some other reference", more than an actual reference in itself. Any thoughts?

**Comment by dejbug** [comment]
IA: https://duck.co/ia/view/tkinter

**Comment by nikhilsingh291** [comment]
I want to take this issue.

**Comment by dejbug** [comment]
ok, this is more interesting than I thought. but I'm working at it.

**Comment by pjhampton** [comment]
If you need any help @dejbug, please feel free to reach out! We're all here to advise and help where we can

💙  💛  💜  💚  ❤️

**Comment by dejbug** [comment]
tenkyu @pjhampton !

**Comment by moollaza** [comment]
> ok, this is more interesting than I thought. but I'm working at it.

@dejbug fwiw, we're not beholden to https://docs.python.org/2/library/tkinter.html -- if you know of a better resource, we can certainly use that!

**Comment by dejbug** [comment]
hi @moollaza that is good to hear!

I'm going to work with the original Tk man pages for now. parse them into a usable form then afterwards apply the Python syntax modifications, as outlined in the py27 tkinter docs. (maybe the intermediate files could be useful to someone working on the Tcl IA.)

this done, there'll still remain some extension libraries to add: Pwm, tix, and ttk. the latter is a submodule of py3 but not of py2, so this will need to be made obvious to the reader. I'll be back on the horse in a day or two. not feeling up to specs these days. but it'll pass.

and by the way! what better way to learn `tkinter` than to fiddle with the docs? I too need to read up on things, currently I'm browsing through a couple books and intros. (the one you posted is a good one, too!) just to get the feel. I'm really a wxPython guy myself.

in any case, sorry for the holdup!
😀 cheers!

**Comment by dejbug** [comment]
@moollaza . I just noticed that the `pydoc Tkinter` reads very nice as well. I suppose this is what was meant by OP instead of the data source link to <https://docs.python.org/2/library/tkinter.html>. I'm wondering why not write (if there isn't such a thing already) a pydoc to fathad converter?

**Comment by dejbug** [comment]
let's see if this will work: first every symbol in the Tkinter python sources will be enumerated, then the (often more informative) docs from the Tcl/Tk reference added.

this is taking longer than I thought, also because I'm trying to find a way to avoid copy-and-pasting a whole new documentation page. but, also given how small the library is, that may be a valid option here.

anyway, the more I fiddle with it, the more I'm falling in love with the Tk. it's just such a cutie among GUIs. looking forward to producing an `output.txt` that I can live with and that will be useful in my future and increasing use of it.

**Comment by pjhampton** [comment]
Hey @dejbug 

Just wondering if there is any update? 😄

**Comment by dejbug** [comment]
It's been a while 😭 So so sorry @pjhampton !
Thanks for the friendly reminder though. Let me see what I can do.
Realistically I should be able to muster the willpower to wrap up the groff parser I think I was about to finish and at least get the tk man pages shipshape for anyone who wants to pick it up from there, just in case my energy should fizzle out again, which, during this time of year, is likely to happen.
Thanks for the patience !!

**Comment by pjhampton** [comment]
Hey @dejbug! We all really appreciate your help 😄  Let me know if I can help further

**Comment by dejbug** [comment]
ty 👍

**Comment by dejbug** [comment]
I'm ashamed it's taking me this long. At this point I'm avoiding even thinking about it. And it's all so simple. Give me one more week to try and get my mind focused on this and then please save me from myself and take me off this issue please :D Thank you so much for the divine patience you've been showing me ! I'll be making up for this in the future. I must ! <3

**Comment by pjhampton** [comment]
That's cool, @dejbug. We all really appreciate your help. 
As the programming mission isn't our primary concern at the moment, we can halt this here if you want? There are loads of new issues here: duckduckhack.com/issues - These will have a big impact on DDG users around the world

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now 👍
