### ISSUE TITLE
Python: Separate Python2 only articles into new Python2 Fathead

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#555]
### Description
Currently we have a single Python Fathead responsible for creating all articles related to Python 2 and Python 3. A subset of these articles are only relevant to Python2 and so we prepend the article title with "python2". This requires the user to enter a query of the form: `python2 {{query}}`.

This drastically reduces the flexibility of triggering Python2 articles because different people specify "python2" in different way. E.g. "python 2", "python 2.7", "python27", "python 27", etc.

Internally, Fathead have trigger words (just like Spice and Goodies), that can appear at the start or end of a query. This allows us to broaden the query space of a Fathead without modifying the article titles, or requiring redirects.

If we separate the `python2` articles into their own Fathead, we can specify as many "python2" trigger words as we want, and even require their presence in the query to trigger the Fathead. This will make it considerably easier to trigger the Python2 articles, and should have a big impact on Python coverage.

There are several ways to achieve a separate Python2 Fathead. The simplest being to copy the code from Python and adjust it to only handle Python2 articles.

However, we could definitely find a more clever approach: For example, the Python2 `fetch.sh` could simply execute the Python Fatheads `fetch.py` and `parse.py` scripts to get a copy of `output_py2.txt` and then rename that file to `output.txt`.

As long as DDG staff can `cd` into the Fathead's directory, execute `fetch.sh` and `parse.sh`, and end up with an `ouput.txt` in the current directory, we will be OK.

Does anyone have any other ideas or thoughts about how to achieve this?

Again, the end goal is to have a Fathead that covers articles that are specific to Python2 (i.e. no overlap with the articles in the Python Fathead), so that we can use Fathead trigger words to ensure a "python2" specifier is in the query. We can't achieve this with a unified Fathead because there is no other way of separating python2 articles from python3 articles when they have identical article titles.

### Example

| Query | Triggered Fathead | Trigger | "More at" Link | InfoBox Content | Currently Possible
--------|-------------------|---------|----------------|-----------------|-------------------
"[os.dup](https://duckduckgo.com/?q=os.dup)" | **Python** | None |points to python3 docs | link to "python2 os.dup" | Yes
"[python2 os.dup](https://duckduckgo.com/?q=python2+os.dup)" | **Python2** | "python2" | point to python2 docs | link to "python3 os.dup" | Yes
"[os.dup python 2.7](https://duckduckgo.com/?q=os.dup+python+2.7)" | **Python2** | "python 2.7" | points to python2 docs | link to "python3 os.dup" | NO
"[os.dup for python27](https://duckduckgo.com/?q=os.dup+for+python+27)" | **Python2** | "for python27" | points to python2 docs | link to "python3 os.dup" | NO

## People to notify
@pjhampton @duckduckgo/community-leaders @duckduckgo/language-leaders 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

**Comment by Hestben** [comment]
I just created #576 
Does this issue also include removing python2 results and redirects from python3 result, or are we keeping them as they are (seems logical to me).

**Comment by tagawa** [comment]
@Hestben Thank you for the PR! I think keeping them as they are for now, as you suggest, would be OK. This should make the PR simpler and we can create a new issue for removing the python2 results in future if we need to.
