### ISSUE TITLE
MDN JavaScript: "data type" articles should have redirects with "type" and "data type" postfixed

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#556]
Currently "javascript null type" doesn't trigger the Fathead. However, "javascript null" does.

We should have redirect for each "data type" article.

For example,  "null type" and "null data type" should redirect to "null".

------
IA Page:  http://duck.co/ia/view/mdnjs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ericedens

**Comment by mbad0la** [comment]
I'd like to resolve this. Thanks!

**Comment by tagawa** [comment]
Hey @mbad0la - thank you very much! I've assigned you to the task. You probably know what you're doing but if you need any help, ask any time!

**Comment by mbad0la** [comment]
Hey @moollaza @tagawa are you sure this is for MDNJS Fathead? When I executed the query `javascript null`, instead of the MDNJS Fathead, the Stackoverflow Longtail is invoked. There is no article for `null` in MDN. Atleast not in the ones we have fetched uptil now.

What do you think?

**Comment by bfmags** [comment]
@mbad0la you can find MDN being returned in the 'about' tab

https://duckduckgo.com/?q=javascript+null&t=h_&ia=about
