### ISSUE TITLE
Python: create sklearn fathead

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#558]
# Create a new sklearn Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**More specifically**,
Create a fathead that handles sklearn classes and methods to answer queries like 'sklearn adaBoostClassifier'. http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

**Data source**: http://scikit-learn.org/dev/modules/classes.html

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @pjhampton  for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by sahildua2305** [comment]
@jdorweiler Ah! I think you just copy-pasted the content of the description of issue. Got it! 😛

**Comment by tagawa** [comment]
Well spotted @sahildua2305 - thanks!

**Comment by souravsingh** [comment]
I would like to work on this issue

**Comment by pjhampton** [comment]
It's all yours @souravsingh

**Comment by beng** [comment]
👋 @souravsingh - are you still working on this? would you be open to collaborating?

**Comment by souravsingh** [comment]
@beng I am working on the issue. Will make a PR in a few days.

**Comment by pjhampton** [comment]
Hey @beng 

Are you available on working on another fathead, possibly Tensorflow or keras?

**Comment by beng** [comment]
@pjhampton which issue # (and move convo to somewhere else? maybe slack)? already on #612 and am exploring #334.

**Comment by souravsingh** [comment]
@pjhampton The sklearn fathead was already done before.

**Comment by pjhampton** [comment]
Hey @souravsingh,

Yes, it looks like @jrasanen was working on this a couple of months ago. So sorry for the confusion. Let's chat on skype and see if there is something we can find for you.
