### ISSUE TITLE
CelebHeights: URL and Class values changed

### ISSUE THREAD

**Issue by RobPaul** [duckduckgo/zeroclickinfo-fathead#564]
The A-Z index pages on Celebheights had 2 changes made, so I suggest a quick fix:

Fetch File:
Old A-Z url's : http://www.celebheights.com/s/A.html
New A-Z url's : http://www.celebheights.com/s/allA.html

Parse File:
Old: "process 'div[class="starazCol v11"]'"
New: "process 'div[class="sAZ2 v11"]'"

------
IA Page:  http://duck.co/ia/view/celeb_heights 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): **_None_**

**Comment by pjhampton** [comment]
Thanks @RobPaul! Would you be interested in submitting a patch?

**Comment by lernae** [comment]
@pjhampton @moollaza I'll take this one.

**Comment by rajesh455** [comment]
Having some Malware issues with this link of my website https://oprice.in/blog/bollywood-singers/ Some redirects are going On !!

**Comment by pjhampton** [comment]
Hi @rajesh455 

I've removed that link. I don't understand though - that URL has nothing to do with this Fathead or its source. 
This makes me think this is spam. If you have feedback for DuckDuckGo - please leave it on the search engine's results page.
