### ISSUE TITLE
HTTP Status Codes: Not all status codes work or show IA results

### ISSUE THREAD

**Issue by echosa** [duckduckgo/zeroclickinfo-fathead#565]
There are times when searching http status codes results in an StackOverflow Q/A instant answer or no instant answer at all. See the attached screenshots.

<img width="918" alt="screen shot 2016-11-22 at 1 34 37 pm" src="https://cloud.githubusercontent.com/assets/133786/20538907/cd0c0b6a-b0b8-11e6-8115-a052d3870eb2.png">

<img width="1209" alt="screen shot 2016-11-22 at 1 35 47 pm" src="https://cloud.githubusercontent.com/assets/133786/20538910/cf9c068c-b0b8-11e6-86c3-f47a10a2098c.png">

<img width="1239" alt="screen shot 2016-11-22 at 1 36 07 pm" src="https://cloud.githubusercontent.com/assets/133786/20538912/d28de55e-b0b8-11e6-8e49-3022de4f1891.png">

<img width="1246" alt="screen shot 2016-11-22 at 1 36 27 pm" src="https://cloud.githubusercontent.com/assets/133786/20538918/d5c26b64-b0b8-11e6-8fc0-06981e3a0063.png">

------
IA Page:  http://duck.co/ia/view/httpstatus 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
Hey @echosa 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.

**Comment by echosa** [comment]
Not gonna lie, I completely forgot about this. I've just gotten used to how it works now, for better or worse. No issue with closing. Maybe it'll improve one day, but certainly not a pressing matter. 👍
