### ISSUE TITLE
PHP zeroclickinfo-fathead php unable to create output.txt

### ISSUE THREAD

**Issue by Donkeymasher** [duckduckgo/zeroclickinfo-fathead#568]
### Description

Unable to create output.txt for php on codio from the php/lib  
error code ensues on running:
```
Error: EMFILE: too many open files, open '/home/codio/workspace/zeroclickinfo-fathead/lib/fathead/php/node_modules/jsdom/node_modules/whatwg-encoding/node_modules/iconv-lite/encodings/internal.js' 
```

## Steps to recreate

within zeroclickinfo-fathead/fathead/lib/php run:
1. npm install
2. fetch.sh
3. parse.sh 

## People to notify

@MariagraziaAlastra
@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/php

**Comment by pjhampton** [comment]
This is weird, because I can't recreate this locally, but can on Codio. We should discuss this with codio themselves.

![screen shot 2016-11-23 at 7 53 42 pm](https://cloud.githubusercontent.com/assets/8960296/20576660/b6e9c5ee-b1b6-11e6-8644-03f614f8f0e0.png)

**Comment by moollaza** [comment]
@Donkeymasher @pjhampton I believe the issue here is that the Node.js script is exhausting the memory on Codio. Those machines only have 1 or 2GB of RAM.

We should probably update the parsing script to be less of a resource hog, or allow it to be more configurable.

@Donkeymasher is this something you could do?

/cc @VitorVRS -- can you confirm/deny this?

**Comment by moollaza** [comment]
Sorry it's not a memory issue, but an issue with too many files open. (_I should have read that error message closer..._)

According to http://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files#15934766 it seems like using `graceful-fs` is the first suggested solution but we're already using that. The max limit of open files on Codio may be small.

Anyone interested in finding a solution?

**Comment by VitorVRS** [comment]
@moollaza Yes, this issue occurred with other devs, but not with me. Doing some research, node uses some environment variable "ulimit".

Look at this thread: https://github.com/gruntjs/grunt-contrib-copy/issues/21#issuecomment-10840100

**Comment by moollaza** [comment]
FWIW this error doesn't occur on the DDG machines, so we're OK to run the parser if it's updated.

**Comment by moollaza** [comment]
@VitorVRS good find! Oddly though the ulimit value on Codio is much higher than my DDG box. 

I'm seeing `1024` on my DDG box and `4096` on Codio -- I wonder if the Codio limit is _**too**_ high?

**Comment by VitorVRS** [comment]
Can you test the following manually?

https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/php/parse.js#L5

1. Remove line 5
2. Rename gfs to fs
3. Remove line 7

This will generate warning, but no exception, filling de output.txt file.

**Comment by moollaza** [comment]
@VitorVRS I had tried that and saw the warnings, but I didn't bother to actually check if the output.txt was filled (I assumed it wasn't) -- I will confirm that the final result is the same as what I'm getting on my machine.

**Comment by VitorVRS** [comment]
@Donkeymasher can you try the steps i wrote above?

**Comment by moollaza** [comment]
@VitorVRS unfortunately I'm seeing an empty output.txt ☹️

**Comment by VitorVRS** [comment]
I tried on other machine and worked.
I'll add examples to output as mentioned on another issue and make an PR fixing this too.
