### ISSUE TITLE
Perl: Create New PerlPackageDoc FatHead

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/zeroclickinfo-fathead#569]
# Create a new PerlPackageDoc Fathead Instant Answer

Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?

You'll need to know how to code in **Perl**.

### What am I doing?

You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

We should create a FatHead that provides specific results for different Perl packages.

For example, searching '[perl Mojo::DOM all_text](https://duckduckgo.com/?q=perl+Mojo%3A%3ADOM+all_text&ia=web)' should yield a result describing the `all_text` routine from the `Mojo::DOM` package.

We should start out with a single FatHead that exposes separate parsers for each package, with a script that will run them all as appropriate.

I would suggest using metacpan.org for retrieving the documentation.

The initial implementation should support (at least some) of the following:

* CGI
* Dancer2
* Mojo(licious)
* DBI
* DBIC
* Template Toolkit
* JSON

Some previous discussion can be found on the forum: https://forum.duckduckhack.com/t/cpan-framework-fatheads/196

**Data source**: https://metacpan.org

**Instant Answer Page**: https://duck.co/ia/view/perl_package_doc

### What is the Goal?

As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) ~~Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)~~ (use the following Instant Answer page: https://duck.co/ia/view/perl_package_doc)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @GuiltyDolphin for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by deserted** [comment]
Would be interested to put my hand up for this @GuiltyDolphin, I'll get a start on it next week.

**Comment by pjhampton** [comment]
Hey @deserted! I assume you are still working on this so I assigned it to you

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now 👍
