### ISSUE TITLE
C++: List all topic titles and language features to help measure coverage

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/zeroclickinfo-fathead#573]
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/cppreference_doc

**Comment by tagawa** [comment]
Just to clarify, this issue requires making a list of keywords in a new text file - no coding is needed.
As an example, there are two similar pull requests for other languages which should be useful for reference:
* jQuery: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/561/files
* CSS: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/547/files

**Comment by tagawa** [comment]
@MariagraziaAlastra Is it sufficient to mention all C++ headers in the list, or do the methods inside those headers also need to be mentioned?

**Comment by ankushg07** [comment]
@tagawa @sahildua2305 I would like to take this easy issue
just couple of query
In which directory it has be mentioned there are two c++ folders
1) c++_ref
2) cppreference_doc 

Also can i include all predefined function name(which are part of some header files) along side the main keywords or just the keywords by c++

**Comment by tagawa** [comment]
Hi @ankushg07. Thank you very much for taking this on!
I think cppreference_doc is the correct directory, and it should be fine to include all predefined function names as well. @MariagraziaAlastra - could you confirm that's correct please?

**Comment by sahildua2305** [comment]
@ankushg07 Thanks for taking this up!

Yes, `cppreference_doc` is the correct directory. Please check [docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html) and let me know if you need help. 😄
