### ISSUE TITLE
MDN CSS: Update parser to prevent duplicate articles

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#580]
### Description

After running the Fathead Test, it shows that our `output.txt` file contains 10 duplicate entries:

```
# 10 DUPLICATE ARTICLES FOUND:
# -webkit-appearance        duplicated on lines 155, 156
# left                      duplicated on lines 770, 771
# -moz-placeholder          duplicated on lines 67, 68
# position                  duplicated on lines 949, 950
# -webkit-perspective       duplicated on lines 195, 196
# perspective property      duplicated on lines 940, 941
# symbols                   duplicated on lines 1060, 1061
# right                     duplicated on lines 990, 991
# color                     duplicated on lines 566, 567
# perspective               duplicated on lines 938, 939
```

These need to be reviewed  to determine if the duplicate titles have duplicate abstracts, and if so we need to update the parser to ensure we don't create any duplicate entries. If the abstracts are different it means we need to update the parser to create disambiguations entries for these entries. We will also need a way to differentiate the titles so all the article titles are unique.

## Get Started
- [x] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

**Comment by hchienjo** [comment]
I will work on this.

**Comment by tagawa** [comment]
Great, thank you @hchienjo!
