### ISSUE TITLE
NodeJS: Need to remove HTML from parsed documentation content

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#591]
### Description

https://duckduckgo.com/?q=http.Server.checkExpectation&ia=about

Looking at the output.txt I can see we're pulling the HTML straight from the docs, which already contains `<p>` and `<a>` tags. The `<a>` tags are known to cause issues and should be removed.

By wrapping the `description` in `<p>` we're breaking the pre-existing `<p>` tags, which is causing the browser to add additional `<p>` tags, creating a lot of extra whitespace.

We need to remove all `<p>` and `<a>` tags from the content before using it. We can keep the `<code>` tags if we want, but simply removing all HTML from the parsed content will be the easiest solution here.

## People to notify
@bfmags @jarrodthibodeau 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by willyb321** [comment]
I think that I can probably do this.

**Comment by bfmags** [comment]
Hi @willyb321 it's yours :)
Reach out if you need any help!
