### ISSUE TITLE
PyPi: increase the number of packages we cover

### ISSUE THREAD

**Issue by jdorweiler** [duckduckgo/zeroclickinfo-fathead#598]
## Description

We limited PyPi to only the top 10000 packages in #533 to try to improve the relevancy of the results. It looks good so far and so I'd like to bump it up to 15000 and see how that looks. 

## What to do
Increase this limit to the appropriate number. 
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/py_pi/parse.py#L15

------
IA Page:  http://duck.co/ia/view/py_pi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ezgraphs

**Comment by danidee10** [comment]
If no one has claimed this i would love to (PS...isn't this as easy as bumping up the number in `parse.py` or am i missing something else?)

**Comment by jdorweiler** [comment]
@danidee10 exactly, just find the correct number of pages to get 15k articles.
