### ISSUE TITLE
CanIUse: Create aliases instead of duplicate articles, use <ul> instead of <br>, and more

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#599]
### Issues to be Fixed

1. Currently we create an array of `title`s and loop over that creating individual articles 
    - We should instead create redirect entries from within the parser
    - OR, build a separate `redirects.txt` file that will be used internally to generate all the redirects
2. After the initial paragraph of text, we have a list of supported browsers that are separated with `<br>` -- we should instead build an unordered list using `<ul>` and `<li>`
3. The `Notes:` subtitle should be wrapped in `<span class="prog__sub">` instead of `<p>`, the bolding should be removed
4. The list of notes should be a `<ul>` as well, instead of multiple paragraphs

The final markup should look like this:

```html
<section class="prog__container">
    <p>Method of defining a linear or radial color gradient as a CSS image.</p>
    <ul>
        <li>IE 10+ ✓</li>
        <li>Firefox 16+ ✓</li>
        <li>Chrome 26+ ✓</li>
        <li>Safari 6.1+ ✓</li>
        <li>iOS Safari 7.0-7.1+ ✓</li>
        <li>Android Browser 4.4.3-4.4.4+ ✓</li>
    </ul>
    <span class="prog__sub">Notes:</span>
    <ul>
        <li>Syntax used by browsers with prefixed support may be incompatible with that for proper support.</li>
        <li>Support can be somewhat emulated in older IE versions using the non-standard "gradient" filter.</li>
        <li>Firefox 10+, Opera 11.6+, Chrome 26+ and IE10+ also support the new "to (side)" syntax.</li>
    </ul>
</section>
````

## People to notify
@samskeller @sahildua2305 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/caniuse

**Comment by adentranter** [comment]
Im keen to take on this issue.

Just wanted to get a bit more info on what you mean in point 1 if possible? The other 3 items I understand fully.

**Comment by BharatKalluri** [comment]
Hello ,
I tried this and made a pull request(#864).

This is my first time trying to fix a bug, let me know if there is anything else to change!
