### ISSUE TITLE
jQuery: Add article aliases (redirects) -- $word, $(word), $ word

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#608]
### Description

We have aliases for $.word, e.g. $.ajax, but we still miss the following ones:

$word - e.g. $ajax
$(word) - e.g. $(ajax)
$ word - e.g. $ ajax

### What to do
For each jquery.* method line in the [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/jquery/articles.txt), create aliases and store them in a new redirects.txt file, in the same directory.

Each line of the redirects.txt file should be structured as follows: alias,original line.
E.g: `$Callbacks,jQuery.Callbacks()`

This change will allow the Instant Answer to trigger for more searches.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  https://duck.co/ia/view/jquery

**Comment by amdolan** [comment]
I'll take this.  Maybe a few more when I have things running 😄

**Comment by bfmags** [comment]
@amdolan Thanks! Reach out if you need any help! 👍

**Comment by amdolan** [comment]
No problem @bfmags, just one question; 

>in a new redirects.txt file
I'm not sure if this means to clobber the existing file, or if you really want me to append to the file.  Clarification would be good 😅 

[Here's what I did](https://github.com/amdolan/zeroclickinfo-fathead/commit/c6dbca2f06668b6be626e14f3ca962cf3000c818), but I'm second guessing it, I couldn't find how redirects.txt is used..

**Comment by amdolan** [comment]
questions answered here: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/650
will have a pr later on.

**Comment by bfmags** [comment]
Hi @amdolan is this still going?

**Comment by pjhampton** [comment]
Hey @bfmags 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
