### ISSUE TITLE
jQuery: Add article aliases (redirects) -- Add, remove, set, toggle

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#609]
### Description

We need aliases for the .css() and for the .add() articles, prepending the words "add" and "set":

~~"add css",~~ "add class", "add css class", "add a class", "add a css class", "add classname" as aliases for ~~.css()~~ .addClass()
Same as above, but with "set" instead of "add" (e.g. "set css" etc)
"add element", "add html element", "add dom element","add child", "add child element", "add children", "add children elements", "add to dom", "add to html" (use also the plural of element, e.g. "add elements") as aliases for .add()

**UPDATE:** 
Also add aliases "remove (...)" for removeClass() and "toggle (...)" for toggleClass() 
/ update .css() aliases according to jQuery api :

* .toggleClass() toggles the css class, adding it if it's not present, removing otherwise - _not covering * optional boolean parameter to behave as add/removeClass_;
* .css() allows to retrieve computed style, or set css style for an element;

### What to do
For each article line in the [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/jquery/articles.txt), create aliases and store them in a new redirects.txt file, in the same directory.

Each line of the redirects.txt file should be structured as follows: alias,original line.
E.g: `add css,.css()`

The aliases should have:
- The word "jQuery" removed
- Symbols such as dots replaced with spaces
- Parentheses removed
- CamelCase words split into different words (eg "createClass" would become "create class")

This change will allow the Instant Answer to trigger for more searches.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  https://duck.co/ia/view/jquery

**Comment by devanshdalal** [comment]
Hi guys, I will take this issue.

**Comment by bfmags** [comment]
Cheers! 😄

**Comment by devanshdalal** [comment]
What be the redirects for fields  ``:eq() Selector``?

What would be for this one ``Attribute Contains Prefix Selector`` as well?
