### ISSUE TITLE
jQuery: Add article aliases (redirects) -- Append, After, Before

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#610]
### Description

We need some aliases for the articles .append(), .after() and .before():

"append child", "append element", "append html element", "append elements", "append to html", "append to html element", "append to div", "append to page", "append to dom" as aliases for .append()
"append after", "append after element" etc as aliases for .after()
Same thing as above, but with "before" instead of "after", as aliases for .before()

### What to do
For each article line in the [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/jquery/articles.txt), create aliases and store them in a new redirects.txt file, in the same directory.

Each line of the redirects.txt file should be structured as follows: alias,original line.
E.g: `append after,.after()`

The aliases should have:
- The word "jQuery" removed
- Symbols such as dots replaced with spaces
- Parentheses removed
- CamelCase words split into different words (eg "createClass" would become "create class")

This change will allow the Instant Answer to trigger for more searches.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  https://duck.co/ia/view/jquery

**Comment by pvskarthikeya** [comment]
Hi! This seems like something I can do. I will start working on this. Is anyone already working on this?

@bfmags @MariagraziaAlastra

**Comment by MariagraziaAlastra** [comment]
@pvskarthikeya No one has taken this yet, you're welcome to work on this! Thanks! :smile:

**Comment by bfmags** [comment]
Hi @pvskarthikeya any progress? 😄

**Comment by pvskarthikeya** [comment]
Hey @bfmags. I have yet to start working on this. I will do it today. Sorry about the delay.

**Comment by pjhampton** [comment]
Hey @bfmags 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
