### ISSUE TITLE
jQuery: Add article aliases (redirects) -- Event Methods

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#611]
### Description

Add aliases for [event methods ](https://api.jquery.com/category/events/) : 

* "bind" + event name, e.g. "bind click"
* "trigger" + event name, e.g. "trigger click"
* event name + "element" and "on element", e.g. "click element" and "click on element"
* "on" + event name + "event", e.g. "on click event" and "onclick event"
* event name + "function", e.g. "click function"
* "on" + event name + "function", e.g. "on click function", "onclick function"

### What to do
For each event method line in the [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/jquery/articles.txt), create aliases and store them in a new redirects.txt file, in the same directory.

Each line of the redirects.txt file should be structured as follows: alias,original line.
E.g: ~~`bind click,.bind()`~~ **Updated:** `bind click,.click()`

The aliases should have:
- The word "jQuery" removed
- Symbols such as dots replaced with spaces
- Parentheses removed
- CamelCase words split into different words (eg "createClass" would become "create class")

This change will allow the Instant Answer to trigger for more searches.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  https://duck.co/ia/view/jquery

**Comment by ioanmoldovan** [comment]
I'll take a look at it :-)

**Comment by bfmags** [comment]
Thanks @ioanmoldovan ! Let me know if you need any help

**Comment by ioanmoldovan** [comment]
Can you please message me on slack, I have some questions

**Comment by bfmags** [comment]
Thanks @ioanmoldovan !

https://beta.duckduckgo.com/?q=jquery+on+mouse+enter&ia=about

**Comment by ioanmoldovan** [comment]
If a user searches for "bind click", I think the example shown should be for .bind(), but more specific, with the argument of the bind function containing the event name (in this case "click"), not just eventType. Also it would be nice if developers were warned bind, trigger and others are deprecated.

**Comment by moollaza** [comment]
@bfmags I think "bind click" should point to `.click()` because it sounds like you're trying to do (bind) something when a click occurs.

I think `trigger event` should point to `.trigger` though, because I would search that when I'm looking for the docs about the "trigger" event.

Are you thinking someone might search that to learn about _how to_ trigger an event?

**Comment by bfmags** [comment]
Exactly, I was thinking someone searching for `bind click` might be searching to learn about the click event, rather than how to bind an event.

@ioanmoldovan can you make these changes : bind should be`bind event, event`

Cheers!

**Comment by MariagraziaAlastra** [comment]
@ioanmoldovan @bfmags It's live! https://duckduckgo.com/?q=bind+click&t=vivaldi&ia=about

Thanks so much, going to close this as fixed now :smile:
