### ISSUE TITLE
jQuery: Add article aliases (redirects) -- :checked Selector

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#612]
### Description

We need to add the following aliases for the article ":checked Selector":

"checkbox is checked"
"checkbox checked"
"checkbox on select"
"checkbox on check"
"checkbox select"
"checkbox selected"
"checkbox is selected"

### What to do
Create aliases and store them in a new redirects.txt file, in the same directory.
Reference [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/jquery/articles.txt).

Each line of the redirects.txt file should be structured as follows: alias,original line.
E.g: `checkbox is checked,:checked Selector`

This change will allow the Instant Answer to trigger for more searches.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  https://duck.co/ia/view/jquery

**Comment by beng** [comment]
@bfmags i would like to tackle this issue.

**Comment by bfmags** [comment]
Thanks @beng, you can go for it!
