### ISSUE TITLE
jQuery: Add article aliases (redirects) -- Example

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#613]
### Description

Add aliases appending the word "example" to all article titles.

### What to do
For each article line in the [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/jquery/articles.txt), create aliases and store them in a new redirects.txt file, in the same directory.

Each line of the redirects.txt file should be structured as follows: alias,original line.
E.g: `ajax example,jQuery.ajax()`

The aliases should have:
- The word "jQuery" removed
- Symbols such as dots replaced with spaces
- Parentheses removed
- CamelCase words split into different words (eg "createClass" would become "create class")

This change will allow the Instant Answer to trigger for more searches.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

------
IA Page:  https://duck.co/ia/view/jquery

**Comment by jBaldha** [comment]
https://github.com/jBaldha/jQueryAddarticleAliases/tree/master

**Comment by bfmags** [comment]
Hi @jBaldha thank you for wanting to contribute, and taking the time writing that code!

Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md), also in order to accomplish the task, you'll have to:

* [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
* Create a Pull request on github referencing this issue #613

* Your code will run on a NodeJS environment rather than on the browser
* Your files should be placed inside the jQuery Fathead folder (https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/jquery)
* Your code will parse the articles.txt file and should generate a new redirects.txt file

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by Caldwerl** [comment]
I'd like to give this a shot.
