### ISSUE TITLE
PHP: Improve parser to cover more of the documentation and create redirect entries

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#616]
### Description

We've added the names of all PHP Functions to the `cover/` directory, and after running the test, it reported that over 18,000 functions from our coverage are missing in the output.txt.

We need to investigate why the output only contains approximately 4000 articles, and update the parser to grab the missing 14,000 articles.

We also need to create redirects appropriately so that our output.txt also satisfies our coverage data. It may be that our coverage data needs to be modified, but that should be a last resort.

## People to notify
@VitorVRS @gautamkrishnar 

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/php

**Comment by VitorVRS** [comment]
@moollaza The actual parser only generate articles to php functions, the other entries are, at the majority, class and methods.

Function example: https://secure.php.net/manual/en/function.fopen.php
Class example: https://secure.php.net/manual/en/class.datetime.php

And there are a lot o more "types" of data.

**Comment by tagawa** [comment]
That's correct. The coverage data list contains all the keywords from this search archive on php.net: https://secure.php.net/js/search-index.php?lang=en

I took both the single item name for each entry, e.g. `add`, but because there are many duplicates I also included the full item path for each entry, e.g. `datetime.add`, `event.add`, etc.

Hence a lot of keywords but they should all match an article on php.net. There are also non-functions in there such as error names and reserved variable names.

**Comment by VitorVRS** [comment]
@tagawa should the cover file be splitted on other files according with its context?

Or we should make the parse read that information too?

**Comment by tagawa** [comment]
@VitorVRS Good question - I was wondering that too. I think having it as a single file for now. I've made a small change to the internal code so the articles will be triggered with `... function`, `... class`, `... keyword`, etc. Then we can monitor the coverage and see if we should split the file later, although that might be a lot of manual work.

**Comment by ioanmoldovan** [comment]
Is already someone working on this, and if not, could I work on this?

**Comment by davidjosephhayes** [comment]
I would be down to help

**Comment by moollaza** [comment]
@ioanmoldovan @davidjosephhayes no one is currently working on this -- it's all yours 👍

**Comment by mayank** [comment]
@tagawa can I pick this?

**Comment by gautamkrishnar** [comment]
Yes @mayank you can carry on... 👍

**Comment by mayank** [comment]
@moollaza @tagawa 
When I search `php array_key_exists`, IA is not triggered while if I search for `php array-key-exists` IA is triggered. 
In `output.txt` title is `php array-key-exists`. 

what needs to be done? should I create redirects?

**Comment by VitorVRS** [comment]
@mayank actually you removed the code which replaces "-" to "_".

Look at this diff on you last PR: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/678/files#diff-b1ea04c31c1b207fde401593e8a86892R151

This wrongly pass by the review :sob:

**Comment by mayank** [comment]
@VitorVRS sorry 😕, it was not working on queries so I removed it, let me redo and check it again, I will raise a PR.
