### ISSUE TITLE
Java: Create New iText 7 Community Fathead

### ISSUE THREAD

**Issue by marti1125** [duckduckgo/zeroclickinfo-fathead#624]
# Create a new iText 7 Community Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

## iText 7 Community

Here is where you will find our application programming interfaces (APIs) - the building blocks you may use to create your very own PDF solution.

http://developers.itextpdf.com/apis

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: http://itextsupport.com/apidocs/itext7/7.0.0/

**Instant Answer Page**: https://duck.co/ia/view/itext7

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @marti1125 for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by BillyBarbaro** [comment]
I'd be willing to give this issue a try.  I've never used iText 7 before, but I looked around the linked doc page and it looks like you can just grab all the classes from the left hand pane.  That would allow us to do something similar to the support for Java now which just has the class and a description in their fathead (although it looks like the descriptions in the Java API are much more detailed than for this framework).

**Comment by BillyBarbaro** [comment]
I took a shot at creating an Instant Answer Page at [https://duck.co/ia/view/itext7](https://duck.co/ia/view/itext7).

I've also been working on a script to scrape the data and it's just about finished, but I have a few questions about some of the details.  Is that best discussed here, on a PR, or is there somewhere else to do that?

**Comment by moollaza** [comment]
@BillyBarbaro thanks for taking this up and getting started. Let us know if you need any help!

**Comment by viveksg** [comment]
Hello, May I take this one?

**Comment by BillyBarbaro** [comment]
@viveksg I've been working on this one as I believe was confirmed above.  Not sure why I was never formally assigned.

**Comment by viveksg** [comment]
@BillyBarbaro Hi, I went through comments but then I saw "No one assigned" in Assignee, so got confused.
Any way no problem.

**Comment by moollaza** [comment]
@BillyBarbaro sorry, you need to be part of the DDG organization before we can assign you. I'll add you to the DDH Contributors Team

**Comment by pjhampton** [comment]
Hey @BillyBarbaro! 👋 
How are you getting on? Any update? 😄

**Comment by BillyBarbaro** [comment]
Hi @pjhampton 

Was a little busier than I expected the last couple weeks.  I got the Fathead to the point where it would respond to queries for all the classes in the library.  But before I submitted I wanted to try and add support for methods as well.  I'll spend a bit of time with it the next few days and hopefully I'll have something by the end of the week.

**Comment by pjhampton** [comment]
That's cool @BillyBarbaro! Just making sure you weren't stuck 😄
