### ISSUE TITLE
NodeJS: fix duplicates

### ISSUE THREAD

**Issue by bfmags** [duckduckgo/zeroclickinfo-fathead#628]
### Description

NodeJS output.txt file has a lot of duplicates that need to be removed.
One way to solve this issue is to introduce a Dictionary to keep track of Articles and avoid duplicates.

## Steps to recreate

Run tests in duckpan:
`DDG_TEST_FATHEAD=node_js prove --quiet t/validate_fathead.t 1>/dev/null`

https://gist.github.com/bfmags/86f81caf513c0078b1d3be3918c22526

Refer to documentation : 
https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html

## People to notify

@MariagraziaAlastra @tagawa @moollaza 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by bfmags** [comment]
@ahetawal-p should I assign you to this one? :)

**Comment by ahetawal-p** [comment]
Sure @bfmags I can take a look, although might be a little late getting to this. As I might be away for Holidays soon :)

**Comment by bfmags** [comment]
@ahetawal-p Cheers! I'll assign you but no pressure on timing! 👍

**Comment by ahetawal-p** [comment]
@bfmags added a fix, take a look when you get some time.
