### ISSUE TITLE
Improve Fathead Tests: Check for escaped tabs, broken HTML

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#629]
### Description
The Fathead tests (in `t/lib/TestUtils`) have recently been updated, but there are a few extra things that we should check for and ensure don't exist in the output:

- escaped tabs (`\\t`): any escaped tabs in the output will cause the entry to be tossed out during internal processing. Any unescaped tabs `\t` should be replaced with 2 or 4 spaces, (i.e. `  ` or `     `)
- broken html: the abstract should always contain HTML. If the `<section>`, `<pre>` or `<post>` tags are broken, or out of order, this can cause problems. We should ensure the HTML is valid inside abstracts

## People to notify
@jbarrett 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by kaushik94** [comment]
@moollaza  @jbarrett can I take this up?

**Comment by moollaza** [comment]
@kaushik94 yes please, you're welcome to!
