### ISSUE TITLE
CSS: Create New Less CSS Fathead

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#634]
# Create a new Less Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: http://lesscss.org/
We can start by covering the functions (http://lesscss.org/functions/) and then language features (http://lesscss.org/features/)

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @hchienjo for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by beng** [comment]
i can take this

**Comment by beng** [comment]
in the [color operating](http://lesscss.org/functions/#color-operations) and [color blending](http://lesscss.org/functions/#color-blending)  sections (and also scattered throughout the docs) there are images that show the user the output of calling each function with various parameters. should i capture these images in the `output.txt`?

**Comment by hchienjo** [comment]
Thanks @beng for offering to do this. As at now, the fathead support referencing one image and I see that there are two images. So for now we can focus on capturing the `example` and `output` parts instead of the image output.

**Comment by beng** [comment]
@hchienjo yeah, that makes sense except there are some functions where `output` is the image, eg `multiply` ([seen here](http://lesscss.org/functions/#color-blending-multiply)). should i only extract the `example` for these functions and **ignore** the output?

**Comment by hchienjo** [comment]
For the moment yes, you can ignore the `output` images but you can capture the `returns` part and maybe one example as well for that case.

**Comment by mayank** [comment]
I am picking this.

**Comment by pjhampton** [comment]
Sorry, @mayank. This is a duplicate issue which is already being worked on (https://github.com/duckduckgo/zeroclickinfo-fathead/issues/764). Please see https://github.com/duckduckgo/zeroclickinfo-fathead/issues/747 for high value tasks.

**Comment by pjhampton** [comment]
I have pinged @beng on Slack

**Comment by mayank** [comment]
@pjhampton It's okay I will pick something else.
