### ISSUE TITLE
MDN CSS: Add aliases (redirects) -- font.

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#635]
### Description

This IA shows answers for searches such as [font size](https://duckduckgo.com/?q=css+font+size&t=lm&ia=about) but not for searches such as `text size`. 

## What to do.
Create a new text file called redirects.txt in the same folder as [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt).

For each entry in [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt) that contains `font` and a property, you will create a line in redirects.txt with its alias in the format: `alias,original line`

## Example
`text-size,font-size`
`text-kerning,font-kerning`

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

**Comment by pa7ryk** [comment]
Hi I'd like to work on this issue.

**Comment by hchienjo** [comment]
@pa7ryk Great! Thanks a lot. All yours.

**Comment by pjhampton** [comment]
@pa7ryk Was this closed in #661 aswell?

**Comment by pa7ryk** [comment]
@pjhampton Yes :)
