### ISSUE TITLE
jQuery Bug: Missing data.url, IAs don't load

### ISSUE THREAD

**Issue by ioanmoldovan** [duckduckgo/zeroclickinfo-fathead#636]
### Description
Nearly all jQuery IAs don't work due to the missing data.url, which is needed for fetch.sh.

## Steps to recreate
Search for any jQuery event method, like "on click event", "on dblclick event" and all the other aliases in redirects.txt

## People to notify
@bfmags

**Comment by moollaza** [comment]
@ioanmoldovan sorry about the confusion.

The jQuery IA still works: https://duckduckgo.com/?q=on+mouseenter&t=opera&ia=about

The new redirects you're mentioning haven't been deployed to production yet. After the PR is merged, there is a release process, currently we've been deploying all the Fathead changes on Mondays.

Regarding the `data.url` -- that's my mistake. Those files are old and I didn't realize that some of the shell scripts depended on that file. In most cases it was simply unused.

I'll update the rest of the parsers accordingly today 👍

**Comment by bfmags** [comment]
@moollaza can we close this one?
