### ISSUE TITLE
MDN CSS: Add aliases (redirects) -- background

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#637]
### Description

This IA shows answers for searches such as [background color](https://duckduckgo.com/?q=css+background+color&t=lm&ia=about) but not for searches such as `color background`. 

## What to do.
Create a new text file called redirects.txt in the same folder as [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt).

Create aliases for each entry in [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt) for which `background` is prepended or appended to one of the following words:

-  color
-  width
-  height
-  position
-  size
-  align
-  center
-  image

Each alias goes to its line in redirects.txt in the following format: `alias,original name`

## Example entries
`background-color,color-background`

## People to notify

@moollaza @hchienjo

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

**Comment by onchance** [comment]
I'll take a stab at this one.

**Comment by onchance** [comment]
@hchienjo I can't work out where `redirect.txt` is being processed. Adding those redirects (7f9fd2f92b99de02f6fa9bbf287475d053a186ba) doesn't appear to have an effect. What am I missing?

**Comment by MariagraziaAlastra** [comment]
@onchance We process that file internally, you can't currently reproduce that on a local instance. If you open a PR containing that file it will be automatically deployed to our beta server and you'll be able to test there.
Thanks! :smile:

**Comment by onchance** [comment]
@MariagraziaAlastra Thanks! I'll go ahead and submit the PR.
