### ISSUE TITLE
MDN CSS: Add aliases (redirects) -- list values

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#638]
### Description

Improve triggering of this IA by add aliases for each CSS property listing the possible values.

For instance the article `font-style` should have the following aliases types:

1. Attribute and value (e.g. "font style bold", "bold font style", "font-style bold", "font-style: bold", "font style: bold", "font-style: bold;")
2. First word in the attribute if it's a composite one with the dash (like font-style or background-color)  and the value, e.g. "font bold", "bold font"
    just the value, e.g. "bold"

Each alias should go in its own line in a file called redirects.txt in the same folder as [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt).

Each line of the redirects.txt file should be structured as follows: alias,original line

## Get Started
- [x] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

**Comment by ankitbisla21** [comment]
I am a beginner. I would like to work on this issue.

**Comment by hchienjo** [comment]
@ankitbisla21 thanks. All yours.

**Comment by rahulxxarora** [comment]
I would like to work on this issue. Will need a little help though, since I am a beginner.

**Comment by TowelDude** [comment]
Can you further explain the task needed to be done? 
I would like to contribute.

**Comment by shivamgupta-gupta** [comment]
Hi, I am interested in contributing.

**Comment by hchienjo** [comment]
@ankitbisla21 Any updates?

**Comment by hchienjo** [comment]
@shivamgupta-gupta  @TowelDude thanks for offering to help. Unfortunately this issue has already been claimed.  However, there are issues [here](https://duckduckhack.com/issues.html) as well if you're interested in helping out.

**Comment by shivamgupta-gupta** [comment]
@hchienjo ok.

**Comment by pjhampton** [comment]
@ankitbisla21 ping

**Comment by adityatandon007** [comment]
@pjhmapton @hchienjo It seems @ankitbisla21 is currently inactive. We should give this issue to someone else. It is unfair to new members, who just come looking to find a way to get in to the community. We cannot let them go, by saying statements like: 
However, there are issues [here](https://duckduckhack.com/issues.html) as well if you're interested in helping out. 
We should always encourage them, not let them wander here and there

**Comment by pjhampton** [comment]
@adityatandon007 we can release this back to the wild soon if we don't hear back from @ankitbisla21. Sometimes this happens, and it's always fine 😄

**Comment by VirgaSenis** [comment]
Is anyone else working on this? If not, I would like to give a try.

**Comment by pjhampton** [comment]
Ok, I think we can safely call this is a time out 😄 
Sure, @VirgaSenis - it's all yours!

**Comment by hchienjo** [comment]
Thanks @pjhampton

**Comment by VirgaSenis** [comment]
How should I address CSS properties with a lot (or even infinite) values? Could you give me an example for _color_ or _width_?

**Comment by alessiodionisi** [comment]
Hello guys,
I'm working on this issue

**Comment by pjhampton** [comment]
Hey @hchienjo!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
