### ISSUE TITLE
MDN CSS: Add aliases (redirects) -- composite words

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#639]
### Description

Create aliases for all the composite-word CSS properties where we switch the words order, e.g. "background-position" would have "position background" as an alias

Each line of the redirects.txt file should be structured as follows: alias,original line.
**Example:** `position background,background-position`

Each alias should go in its own line in a file called redirects.txt in the same folder as [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt).

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

**Comment by pa7ryk** [comment]
I can deal with it.

**Comment by ManrajGrover** [comment]
@pa7ryk Go ahead with it! 😄

**Comment by pa7ryk** [comment]
I don't know how to exactly handle for example this line `:-moz-handler-blocked`.
Should I create separated lines in redirects.txt file like:
```
moz blocked handler
bolcked moz handler
blocked handler moz
...
```
?

**Comment by MariagraziaAlastra** [comment]
@pa7ryk for browser-specific stuff the first line in your example will be enough, you can skip the other combinations :smile: 
Thanks!

**Comment by pa7ryk** [comment]
How about case like this `border-block-start-style`?

**Comment by MariagraziaAlastra** [comment]
@pa7ryk actually you can just skip those altogether, it doesn't make a lot of sense to revert the order in that case. Thank you! 😄

**Comment by pa7ryk** [comment]
@MariagraziaAlastra There are two separated files for redirects (redirect.txt and redirects.txt). One is created by me in issue #635 and another from #637. I think it can be mistake. Should I ignore that?

**Comment by MariagraziaAlastra** [comment]
@pa7ryk yeah don't worry about it, just add the new ones to the file you previously created. 👍

**Comment by hchienjo** [comment]
closed via https://github.com/duckduckgo/zeroclickinfo-fathead/issues/661
