### ISSUE TITLE
MDN CSS: Add aliases (redirects) -- adding elements and divs

### ISSUE THREAD

**Issue by hchienjo** [duckduckgo/zeroclickinfo-fathead#641]
### Description

Add aliases for all articles by appending and prepending the words "element" and "div". 
For instance the article "background-color" would have the following aliases:

1.  "background color element", "background-color element"
2. "element background color", "element background-color"
3. "background color div", "background-color div"
4. "div background color", "div background-color"

Each alias should go in its own line in a file called redirects.txt in the same folder as [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt).
Each line of the redirects.txt file should be structured as follows: alias,original line

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

**Comment by rahuldecoded** [comment]
Can I take this bug?

**Comment by MariagraziaAlastra** [comment]
Sure, thanks @rahuldecoded! 👍

**Comment by rahuldecoded** [comment]
@MariagraziaAlastra Can you tell me what to do with this one?
[webkit pseudo-element selectors (shadow dom elements)](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt#L601)

**Comment by MariagraziaAlastra** [comment]
@rahuldecoded you could have two aliases there for the same article, "webkit pseudo element selectors" and "webkit shadow dom elements" :smile:

**Comment by rahuldecoded** [comment]
@MariagraziaAlastra What to do with this ":-moz-suppressed"?

**Comment by MariagraziaAlastra** [comment]
@rahuldecoded you can skip the ones like that

**Comment by pjhampton** [comment]
Hey @rahuldecoded! How are you getting on? 😄

**Comment by harshit98** [comment]
Hi. I'm new here. I wanted to try contributing some code here :)
I'm not able to understand the issue. Can anyone guide me? Thanks.

**Comment by pjhampton** [comment]
Hey @hchienjo 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
