### ISSUE TITLE
Pika: broaden search results by adding article aliases

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#655]
### Description
For each line in the [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/pika/articles.txt), create aliases and store them in a new redirects.txt file, in the same directory.

Each line of the redirects.txt file should be structured as follows: alias,original line.
The aliases should have symbols, such as dots and underscores, replaced with spaces.

This change will allow the Instant Answer to trigger for more searches.

## People to notify
@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/pika

**Comment by rahuldecoded** [comment]
Is this bug open? I can't see any redirects.txt file in repo.
If this bug open, can I work on this?

**Comment by MariagraziaAlastra** [comment]
@rahuldecoded Yeah it's open! There isn't a redirects.txt file yet for Pika, you'd need to create one.
Of course you can work on this, thanks for your interest! :smile:

**Comment by rahuldecoded** [comment]
@MariagraziaAlastra Actually I'm new to thing so I need some help, hope you don't mind.  :smile: 
As per you comment#1 the dots and underscore will be replaced with space.
example:
access, Access
access request, Access.Request
access request get body, Access.Request.get_body
access request get properties, Access.Request.get_properties
Am I getting it right?

**Comment by MariagraziaAlastra** [comment]
@rahuldecoded Yup, that's right! 
Also no worries, please feel free to ask any questions you might have :smile:

**Comment by rahuldecoded** [comment]
@MariagraziaAlastra I've added a PR. I have done it programmatically using python :baby: 
Sorry in Advance if I've done any mistake.
