### ISSUE TITLE
C#: Create new C# Reference Fathead

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#663]
# Create a new C# Reference Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: https://docs.microsoft.com/en-us/dotnet/articles/csharp/
All the articles in the section [Tour of C#](https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/) should be fetched and parsed.

**Instant Answer Page**: https://duck.co/ia/view/c_sharp

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by johnjkim** [comment]
Hi, can I claim this issue?

**Comment by johnjkim** [comment]
I created a new IA page: https://duck.co/ia/view/c_sharp

**Comment by moollaza** [comment]
> Hi, can I claim this issue?

@johnjkim it's all yours!

> I created a new IA page: https://duck.co/ia/view/c_sharp

Awesome, thanks!

**Comment by johnjkim** [comment]
Just a quick clarification, but by the line "All the articles in the section Tour of C# should be fetched and parsed," does this mean I only need to fetch and parse articles from Tour of C# and I don't have to get articles from the other sections in the Data source?

**Comment by pjhampton** [comment]
Hey @johnjkim,

Sorry for the delay! I got looking into this for you. It seems that this is a [good URL to start from](https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/). From the unanswered query data, I think the sections that would be helpful for c# developers current are:

  - [C Sharp Keywords](https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/keywords/index)
  - [C Sharp Operators](https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/operators/index)

So I think scraping the introduction of each part would make a really sweet fathead!

**Comment by pjhampton** [comment]
Hey @johnjkim, How are you getting? Just checking you if have any more questions? 😄

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now 👍
