### ISSUE TITLE
Haskell: Create New Haskell Reference Fathead

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#664]
# Create a new Haskell Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: https://wiki.haskell.org
E.g. https://wiki.haskell.org/State_Monad
For each article, let's show the first example and the comments.

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @{Language Leader Handle} for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by GuiltyDolphin** [comment]
@MariagraziaAlastra I'll be happy to help review once a PR is made for this IA.

**Comment by sam09** [comment]
I am already working on something else and have a PR up for review. Is it fine if I take this up? Or should I wait till the other PR is merged before taking up something new?

**Comment by pjhampton** [comment]
Hey @sam09, 

That is ok. You can have this one 😄  Thanks!

**Comment by sam09** [comment]
Hey @pjhampton .. It seems the Haskell fathead has already been created.

Also [this](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/index.html) looks like a pretty good source for documentation. It provides offline downloading of documentation which we could use. Your thoughts?

**Comment by pjhampton** [comment]
> It seems the Haskell fathead has already been created.

Where @sam09? Are you talking about this: https://duck.co/ia/view/hayoo?

**Comment by sam09** [comment]
I mint this https://duck.co/ia/view/haskell

**Comment by pjhampton** [comment]
@GuiltyDolphin are you cool if I ghost this IA page?

**Comment by GuiltyDolphin** [comment]
@pjhampton Err, yeah. I forgot about that ^.^

**Comment by pjhampton** [comment]
Thanks @GuiltyDolphin! 😄 
This page is now gone @sam09 if you want to remake it 👍

**Comment by sam09** [comment]
I tried remaking it but I get the same error that the an IA with same title exists.

**Comment by GuiltyDolphin** [comment]
Hmm, @sam09 @pjhampton mightn't it be better to call this FatHead `haskell_wiki`? Then `haskell` could be used for the main docs.

**Comment by sam09** [comment]
Sounds good to me

**Comment by sam09** [comment]
Hey @pjhampton @GuiltyDolphin  I have created a new IA page https://duck.co/ia/view/haskell_wiki. Also the haskell wiki site mentions [this](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/) as a complete documentation. And I think this is available offline too. I think we should be using that.

**Comment by pjhampton** [comment]
Hey @MariagraziaAlastra!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
