### ISSUE TITLE
R: Create New R Reference Fathead

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#665]
# Create a new R Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: https://cran.r-project.org/doc/manuals/r-release/R-lang.html
This is structured as an ebook.
For each article it'd be good to show an example, if available, otherwise just the first paragraph.

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below

**Comment by iamsidshetty** [comment]
Hi @MariagraziaAlastra 

I would like to give this a try. 

Sid

**Comment by pjhampton** [comment]
Hey @iamsidshetty, sorry for the delayed reply

Are you still interested in working on this?

**Comment by iamsidshetty** [comment]
@pjhampton,

Yes, I am willing to work on this. You can assign this to me. 

-Sid

**Comment by pjhampton** [comment]
Hey @iamsidshetty, it's all yours! Can you please create an IA page and join the org here: https://github.com/duckduckgo/duckduckgo/issues/182 - I can assign you after that.

**Comment by iamsidshetty** [comment]
Hi @pjhampton, I have created the IA page with same handle "iamsidshetty" and also requested to be added to the Org. 

I will start working on this.

**Comment by pjhampton** [comment]
This seems to have gone stale. Closing for now 👍
