### ISSUE TITLE
Mercurial documentation instant answer - broken "More At" link

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#67]
When you search for a Mercurial command, like `hg commit`, it gives a short description from the documentation site. However, clicking on that to go to the documentation site doesn't show you the correct spot on the page. 

It links to `http://www.selenic.com/mercurial/hg.1.html#hg commit`, when it should be `http://www.selenic.com/mercurial/hg.1.html#commit`. (The difference is the last part, after the `#`. It should just be the command name, without `hg` in front of it.

**Comment by fish-dango** [comment]
I can take a look here!
