### ISSUE TITLE
Wikipedia Bug: please respect NOINDEX on newly created pages

### ISSUE THREAD

**Issue by MER-C** [duckduckgo/zeroclickinfo-fathead#676]
### Description
The English Wikipedia places NOINDEX on unreviewed new articles because they may contain any combination of libel, spam, vandalism and copyright violations (https://en.wikipedia.org/wiki/Wikipedia:Requests_for_comment/NOINDEX). DDG Wikipedia fathead answers appear regardless of whether the page is NOINDEXed or not.

## Steps to recreate
1. Go to https://en.wikipedia.org/wiki/Special:NewPages
2. Select "Hide patrolled edits" and 500 entries.
3. Click on any article near the bottom. Observe that these articles are tagged with "&lt;meta name="robots" content="noindex,nofollow"/>"
4. Search for the article titles in DDG. A fathead answer appears when it shouldn't.

---

Instant Answer Page: http://duck.co/ia/view/wikipedia_fathead
Maintainer: @duckduckgo

**Comment by pjhampton** [comment]
Thanks @MER-C. I have passed these comments to the internal team.
