### ISSUE TITLE
Python: numpy Fathead should include at least one example, if available

### ISSUE THREAD

**Issue by ashishbhate** [duckduckgo/zeroclickinfo-fathead#684]
### Description
The numpy fathead should also include at least one example. See the discussion in the numpy fathead pull request #584 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/numpy

**Comment by carolkng** [comment]
I'd like to work on this, if it hasn't been assigned yet.
I just have one question, the example from numpy.array mentioned in #584 was taken from https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html, which is not included in the dataset being used to generate the fathead right now. In that case, is it worth downloading all the doc entries from https://docs.scipy.org/doc/numpy/reference/generated/ instead?

**Comment by ashishbhate** [comment]
Hi Carol, thanks for volunteering! 

numpy.array is already included in the dataset that is downloaded by the parser. You can verify this by downloading the zip file that the parser uses (currently https://docs.scipy.org/doc/numpy/numpy-html-1.11.0.zip). The `reference/generated/numpy.array.html` file in the zip file is the same as the one at https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html

From the html source of the documentation, the examples, if they exist, are in the "rubric" html class. Take a look at the `get_related_topics` function and its usage in `get_abstract`. You'll want to do something very similar.

**Comment by ashishbhate** [comment]
@carolkng Looks like someone has just submitted a PR for this issue. Sorry if you already started working on it. I had no idea someone was working on this issue.

Would you be interested in working on any of the other open issues? There are quite a few Python specific ones, if that's your area of interest.

**Comment by carolkng** [comment]
@ashishbhate Project recommendations would be great, thank you!

**Comment by ashishbhate** [comment]
It looks like all the Python related issues are already taken. There are open issues on the issue list, but not all are Python related. You could also take a look at  https://forum.duckduckhack.com/ for ideas for new fatheads.
