### ISSUE TITLE
Perl 6 Documentation Bug: parse.pl fails in parsing code snippets

### ISSUE THREAD

**Issue by titsuki** [duckduckgo/zeroclickinfo-fathead#689]
### Description
As you can see, some Perl 6 IA lack their code snippets:
https://duckduckgo.com/?q=perl6+Cool.chomp&t=h_&ia=about

Recently, the official documentation of Perl 6 changed its syntax highlighter.
See: https://github.com/perl6/doc/commits/12a65aa80ba13aedf17efbf16a83b49057f18748/highlights

I found that the above modification also changes the structure of html documents and it's cause of  this parsing failures:

+ 2016/7/20
![Wed Jul 20](https://udhxna-ch3302.files.1drv.com/y3mE8IBjgUeW0vprDnYJw82mtBOoV3zszLcpcM8jQ-nvpWnXjVV6fbWVCC6RoQG_EXgAqwvF4RY39mJZhBWgx_fHE2QzmnRpm25fg1DoWitmvM2N91fV4PvpBQB6OAg14QbDa3Q8Ynm24nbLikAROZ7iGHtt6WZu9bUSK5N5J_EyZM/2017-01-11.png?psid=1)

+ 2017/01/12
![current](https://ude8wa-ch3302.files.1drv.com/y3mZfuNoFOtl0VOidac4nmGbFDibUMiaUE5G_Dn0psPjAaf7ZsaEQz53Yl2CtvCikMVEWp3pyz8ksFz0_HdURB0nnwwIwO_Wz-U5gDrrvaI1XlitPwqwsRTkgC8gFQglayKY8u6D4OW-4OCCkxkoNFRgWdmlIQsvu-45sVT4tT6Mx0/2017-01-12.png?psid=1)

## Steps to recreate
Fix the parser so that it can handle the html of the latest Perl 6 documentation.

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/perl6doc

**Comment by moollaza** [comment]
@titsuki thanks for reporting this! Would you be interested in fixing it?

**Comment by titsuki** [comment]
@moollaza Thanks for your reply! 
I'm interested in fixing this issue, but I'm not very familiar with HTML::Parser. So it may take a little bit time.

**Comment by moollaza** [comment]
> I'm not very familiar with HTML::Parser. So it may take a little bit time.

@titsuki that's no problem! We're here to help 👍
