### ISSUE TITLE
R: Create New CRAN Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#691]
# Create a new CRAN (R Package Manager) Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: https://cran.r-project.org/web/packages/available_packages_by_name.html

**Instant Answer Page**: https://duck.co/ia/view/cran

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @raj-maurya for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by pjhampton** [comment]
Anybody interested in this? @duckduckgo/duckduckhack-contributors 🚀 
This could make a good first Fathead

**Comment by gautamkrishnar** [comment]
Looking great @pjhampton I would like to work on this. I will populate the output.txt with python. What template should i use?

**Comment by laurenancona** [comment]
I actually had a local stub repo for this that I was trying to work on last year. I haven't checked back in a while but at the time there was something weird about the way CRAN's master package list was formatted (e.g. I'd thought I would need to write a scraper).

I'd like to dig back in since this has been on my personal wish list, so I'll take it @pjhampton

**Comment by gautamkrishnar** [comment]
@laurenancona you can take this if you want 👍. Shall i assign you on this?

**Comment by pjhampton** [comment]
Yes, please @gautamkrishnar! And thanks so much @laurenancona!

**Comment by laurenancona** [comment]
@pjhampton @gautamkrishnar 

Created the IA page:
https://duck.co/ia/view/r_packages

Originally tried to name it `CRAN` but there is a [dead Spice](https://github.com/duckduckgo/zeroclickinfo-spice/pull/2644) by that name that depends on METACRAN's (unofficial) [API](https://www.r-pkg.org/).

What generally happens to IA names when deprecated (or never merged, etc)? No strong preference here - just whatever you think is most relevant, given the topic and IA type.

**Comment by gautamkrishnar** [comment]
@laurenancona Yes IA pages would become something just like ghosts  when the PR Is abandoned😄. Its not possible to anyone to delete it other than DDG employees. 
Yes `r_packages` is a good name for this IA 👍.
Please don't forget to update the example queries when the IA is complete.

**Comment by moollaza** [comment]
@laurenancona @gautamkrishnar I can "ghost" IA pages, which relinquishes their ID. I'll ghost the cran page so you can use it here, or elsewhere as it's a good name ;)

**Comment by moollaza** [comment]
@laurenancona I've updated the ID for your r_packages IA Page. It's now `cran`:

https://duck.co/ia/view/cran

**Comment by pjhampton** [comment]
Hey @laurenancona!

Just in case you are interested or in need of some inspiration, I have done something similar with another package manager (OPAM) here: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/775

**Comment by laurenancona** [comment]
Thanks, @pjhampton, I'll take a look!

I started a new job last month and needed to pause work briefly, but have made progress on the scraper with @ctufts.

**Comment by pjhampton** [comment]
That's awesome! Congrats on the new job 😄

**Comment by pjhampton** [comment]
Hey @laurenancona,

We've moved on from the programming mission. I'm not sure if you're still working on this currently? If you are we can reopen :)
