### ISSUE TITLE
New Scala Docs Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#692]
# Create a new Scala Docs Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: http://www.scala-lang.org/api/2.12.1/

**Instant Answer Page**: https://duck.co/ia/view/scala_documentation

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [x] 5) Create the Fathead
- [x] 6) Create a Pull Request
- [x] 7) Ping @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by pjhampton** [comment]
Hey @pedrozan,

Are you still working on this? I'm just wondering based on this conversation a couple of months ago? 
https://forum.duckduckhack.com/t/new-scala-documentation-fathead/1011
If not, please let me know 😄

**Comment by sam09** [comment]
Would love to work on this.

**Comment by pedrozan** [comment]
Hello, unfortunately life hás trampled me over and I couldn't continue. Please, feel free to develop this

**Comment by sam09** [comment]
Hi I created the IA page [here](https://duck.co/ia/view/scala_documentation)

**Comment by sam09** [comment]
@pjhampton From what I understand, the correct way to implement this would be to download scala documentation and parse it to generate a correct output.txt file. [This](http://www.scala-lang.org/download/2.10.2.html) page provides the entire docs offline. I assume we could use that?

**Comment by pjhampton** [comment]
Yeah, downloading the entire docs is probably a good idea. I scraped a URL at a time in the Python PEP Fathead and it was a real hassle. I recommend you check out the Java Docs Fathead before you do this and run it. Check out the code too! This may help with implementing this as the HTML documents are similar.

https://duck.co/ia/view/java

**Comment by sam09** [comment]
How exactly is output.txt  created?

**Comment by pjhampton** [comment]
Hey Sam, Can you please expand on your question for me? It looks ash if you already have a function to *create* an outputfile. 
see: https://docs.duckduckhack.com/resources/fathead-overview.html#output-fields

**Comment by sam09** [comment]
Yeah. What I meant was that I was unable to run it on codio. I wanted to
know whether I have to run the script locally and push the file or is there
any other way?

**Comment by pjhampton** [comment]
Hey @sam09,

Once the output.txt file has been created in codio you can run it by `duckpan server <ia_name>` and that will start up the dev machine 😄

**Comment by moollaza** [comment]
> I wanted to know whether I have to run the script locally and push the file or is there any other way?

As @pjhampton said you can test your output.txt locally in Codio with `duckpan test <ia_id>`, but also you'll want to commit that file and push it here. We will then automatically install the new Fathead on beta.duckduckgo.com so you can see how it will behave in a real production environment. DuckPAN is just a very basic approximation of the production environment. It's mostly there so you can check how your Fathead will look when it displays.

**Comment by pjhampton** [comment]
Hey @sam09! How are you getting on? 😄  Need any help?

**Comment by sam09** [comment]
Hi @pjhampton... Thanks a lot.. I have been a bit busy past couple of days... opened a pull sometime back..
https://github.com/duckduckgo/zeroclickinfo-fathead/pull/704
