### ISSUE TITLE
JavaScript: Create new Webpack Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#695]
# Create a new Webpack Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the Webpack commands below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: https://webpack.js.org/configuration/

**Instant Answer Page**: https://duck.co/ia/view/webpack_config

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @bfmags for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by pjhampton** [comment]
It seems there is quite a demand for quick look up of Webpack functions. Anybody interested taking this forward @duckduckgo/duckduckhack-contributors?

**Comment by itai421** [comment]
I'll give it a try

**Comment by pjhampton** [comment]
Awesome @itai421, ping me if you have any questions! 😄

**Comment by itai421** [comment]
The link given at task 4 is for viewing `npm_cli` IA.
Did you mean to ref [this link](https://duck.co/ia/new_ia)?

**Comment by pjhampton** [comment]
Yeah, sorry - My bad!

**Comment by itai421** [comment]
(IA page)[https://duck.co/ia/view/webpack_config]

**Comment by itai421** [comment]
The [webpack site](https://webpack.js.org/configuration/) is [open source](https://github.com/webpack/webpack.js.org/tree/master/content/configuration), so can I fetch the data from gitHub?

**Comment by pjhampton** [comment]
You can do, but .md files are going to be difficult to scrape. I recommend you scrape the converted HTML files.

**Comment by itai421** [comment]
Things are going great :)
![screenshot_2017-01-25_23-47-56](https://cloud.githubusercontent.com/assets/9339779/22310733/da46bd52-e358-11e6-978b-5e3e807fa549.png)

But I wonder how to add the *More at* link near the *Show more/less*. Looking at the docs was not so helpful for this, I tried to use the `External links` for that with, but no success on that one. Reading the note: ([taken from here](https://docs.duckduckhack.com/resources/fathead-overview.html#6))
```
Note: Some elements of the pre-process script are configurable from the Fatheads metadata, specified on the Instant Answer Page.
```
made me wonder, whether the *More at* link is one of those things, so am I right?

**Comment by moollaza** [comment]
> But I wonder how to add the More at link near the Show more/less.

@itai421 that is controlled by your IA Page data. Please see https://docs.duckduckhack.com/resources/fathead-overview.html#instant-answer-page-fields

**Comment by moollaza** [comment]
@itai421 I've filled it in for you so you should see it now. Feel free to adjust it.
