### ISSUE TITLE
C   Reference Docs: 

### ISSUE THREAD

**Issue by avenger444** [duckduckgo/zeroclickinfo-fathead#705]
------
IA Page:  http://duck.co/ia/view/cppreference_doc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @manrajgrover

**Comment by avenger444** [comment]
avenger444

**Comment by pjhampton** [comment]
Hi @avenger444,

I'm not entirely sure what the issue is here. If there is an issue with the IA page referencing the IA, please reopen an appropriately titled issue with information to help us identify the issue.
