### ISSUE TITLE
Python: New PyMongo Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#711]
# Create a new PyMongo Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?
You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: http://api.mongodb.com/python/current/api/index.html

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by Lord-Lavios** [comment]
Is there a fathead for [Node.js MongoDB Driver](https://mongodb.github.io/node-mongodb-native/2.2/api/index.html)? If there's a need for it or if it hasn't already been made, then I think I'll be able to make it.

**Comment by pjhampton** [comment]
@Lord-Lavios no there is any queries from what I can see regarding the MongoDB Driver. However there does seem to be a demand for [Mongoose](http://mongoosejs.com/docs/api.html) related searches. Would you be interested in take something like this forward? If so, let me know and I will create an issue for you

```
mongoose migration 
mongoose migrations 
mongoose migrations 
mongoose mock mongoose schema extend 
mongoose model save promise 
mongoose model this 
mongoose model tpyes 
mongoose model types 
mongoose mongo 
mongoose mongodb 
mongoose mpromise 
mongoose nested instance 
mongoose node 
mongoose npm 
mongoose observable 
mongoose plugins 
mongoose poopulate 
mongoose populate 
mongoose populate with find one 
mongoose populating 
mongoose query 
mongoose request-context howto 
mongoose required unique 
mongoose schema to graphql 
mongoose strict 
mongoose time calculations 
mongoose toObject API 
mongoose unique js 
mongoose update collection 
mongoose user model timenow 
mongoose validate object 
mongoose validate objectids 
mongoose validateSync() 
mongoose validation 
mongoose validation number 
mongoose-delete promises 
mongoose-forms 
mongoose-q 
mongoose.createConnection 
```

**Comment by Lord-Lavios** [comment]
Yup. Create an issue for this, I'll do it.

**Comment by dankolbrs** [comment]
I can grab this, but to save some work for everyone I'll be waiting for #738 for final feedback/merge before submitting this one. 

If someone wants this before the other gets merged, I'm cool with that.

**Comment by dankolbrs** [comment]
Created [IA Page](https://duck.co/ia/view/python_pymongo)
https://duck.co/ia/view/python_pymongo
