### ISSUE TITLE
MDN CSS: HTML <code> blocks are stripped from result

### ISSUE THREAD

**Issue by jonathanKingston** [duckduckgo/zeroclickinfo-fathead#722]
Using the following search:
  https://duckduckgo.com/?q=radio+element+pseudo&t=ffab&ia=about

The `<code>` blocks within the source of the MDN page are stripped meaning code is injected into the page directly from MDN. This could lead to XSS'ing users of DDG.

Note the checkbox, radio button and select that are all visible in the search results.

------
IA Page:  http://duck.co/ia/view/mdn_css 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @hchienjo

**Comment by hchienjo** [comment]
@moollaza What is your take on this? Should we leave the leave the <code> and wrap it in another <code>?

**Comment by moollaza** [comment]
@hchienjo yes, we need to wrap any html inside `<p>` in `<code>`
