### ISSUE TITLE
Sass Suggestion: Add Rules, Directives & Expressions

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#727]
## Description

From the [forum statistics](https://forum.duckduckhack.com/t/css-search-overview/96), it's clear that the [Sass docs IA](https://duck.co/ia/view/sass) is steady in delivering content for Sass related queries. However, there is a lot of Sass queries not being served by the IA currently. A [very] small sample includes queries such as:

```
sass import
@while sass 
sass !default
```

It could be a worthwhile effort to update the parser to also parse the following document. http://sass-lang.com/documentation/file.SASS_REFERENCE.html

This would include scraping sections of this one page document such as:

![screen shot 2017-01-30 at 5 08 20 pm](https://cloud.githubusercontent.com/assets/8960296/22433088/179b2fc6-e70f-11e6-85f3-0686ed990582.png)

![screen shot 2017-01-30 at 5 08 39 pm](https://cloud.githubusercontent.com/assets/8960296/22433091/1940be72-e70f-11e6-8f3c-59fe06e076ef.png)

## People to notify
@duckduckgo/duckduckhack-contributors 
cc. @VeerpalBrar (IA Maintainer)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/sass

**Comment by VeerpalBrar** [comment]
The parser already parses the  http://sass-lang.com/documentation/file.SASS_REFERENCE.html file. 

It seems this may be a triggering issue? I'm not sure how to go about fixing that ....

**Comment by pjhampton** [comment]
Hmm, you are correct @VeerpalBrar, the current parser is [catching these](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/sass/output.txt#L192) but they are not triggering. I suspect it has something to do with the special characters such as `!`, `?`. @moollaza will redirects rectify this issue?

**Comment by VeerpalBrar** [comment]
Also it seems that even though the output text contains:
import	R	@import
searching  'sass import' doesn't trigger the AI either.

**Comment by pjhampton** [comment]
Closing as this is no longer high priority 👍
