### ISSUE TITLE
Angularjs (1.X): Replace h2 in Parser with span, as outlined in Fathead Documentation

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-fathead#730]
The parser is creating headings using `<h2>`, but it should be using `<span class=prog__sub">` as outlined in the docs.

This should be adjusted in the parser, and a new output.txt should be generated. 

------
IA Page:  http://duck.co/ia/view/angularjs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rafaelpadovezi

**Comment by rafaelpadovezi** [comment]
My bad. I can do this

**Comment by aeisenberg** [comment]
Sorry, @pjhampton, I had some time and wanted to get started contributing to duckduckhack and sent a PR.
