### ISSUE TITLE
C: New Linux Man Pages Fathead

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#734]
# Create a new Linux Man Pages Fathead Instant Answer
Help us make DuckDuckGo the best search engine for programmers!

### What do I need to know?

There is surprisingly quite a lot of searches for linux commands and their man pages. It would be great to scrape the [following URL](http://man7.org/linux/man-pages/dir_all_alphabetic.html) and turn this into a fathead. A random portion of the queries include (duplicates omitted):

```
linux memset 
linux mkfifo remove fifo 
linux mmap 
linux mmap example 
linux mmap no disk 
linux mmap ram 
linux mutex_lock 
linux nano_sleep 
linux nanosecond gpio 
linux nanosleep example 
linux ncurse 
linux ncurses ESCDELAY 
linux ncurses noecho 
linux ncurses wmove 
linux open 
linux open O_RDWR 
linux opendir 
linux opendir spaces 
linux os.rename system call 
linux perl Storable file 
linux popen 
linux print cwd from program 
linux process time 
linux program mktemp 
linux programmed sleep 
linux pthread 
linux read file arbitrary position 
linux read number from picture 
linux read syslog 
linux readconfig files 
linux readdir 
linux readline 
```

Should also trigger on `unix, man, linux man, unix man`

You'll need to know how to code in **Perl**, **Python**, **Ruby**, or **JavaScript**.
![fathead languages](https://cloud.githubusercontent.com/assets/873785/19787916/57b4c31a-9c73-11e6-9bd9-f85c8893ec93.jpg)

### What am I doing?
You will write a script that scrapes or downloads the data source below, and generates an **output.txt** file containing the parsed documentation. You can learn more about Fatheads and the `output.txt` syntax [**here**](https://docs.duckduckhack.com/resources/fathead-overview.html).

**Data source**: http://man7.org/linux/man-pages/dir_all_alphabetic.html

**Instant Answer Page**: *to be created by developer*

### What is the Goal?
As part of our [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53), we're aiming to reach 100% Instant Answer (IA) coverage for searches related to programming languages by creating new Instant Answers, and improving existing ones.

Here are some Fathead examples:

- Ruby Docs
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/ruby) | [Example Query](https://duckduckgo.com/?q=array+bsearch&ia=about)
- MDN CSS
    - [Code](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdn_css) | [Example Query](https://duckduckgo.com/?q=css+background-position&ia=about)

  ![css background-position search](https://cloud.githubusercontent.com/assets/873785/19787980/cdf51566-9c73-11e6-9ef2-ac44dede62c7.png)

[See more related Instant Answers](https://duck.co/ia?repo=fathead)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a new Instant Answer Page: https://duck.co/ia/new_ia (then let us know, here!)
- [ ] 5) Create the Fathead
- [ ] 6) Create a Pull Request
- [ ] 7) Ping @{Language Leader Handle} for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by danidee10** [comment]
@pjhampton i would like to handle this.

**Comment by pjhampton** [comment]
Awesome! Thanks @danidee10 👍 
Let me know if you need any help! 😄

**Comment by pjhampton** [comment]
@danidee10 It seems that there is already a fathead for this (Sorry!). But reach is fairly limited. I reckon you update the trigger words of that fathead for now, and in a couple of weeks time if the bounce data is low or there is a high click through rate we will change the source. What do you think?

https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/unix_man
https://duck.co/ia/view/unix_man

**Comment by pjhampton** [comment]
Hmm, weird. @edgesince84 reported this issue (https://github.com/duckduckgo/zeroclickinfo-fathead/issues/273) which is pretty serious. Maybe we will just deprecate that one if it's got these problems and not a lot of content. What do you think, @danidee10? 😄

**Comment by danidee10** [comment]
@pjhampton i think we should change the source. Because aside from `adduser` some other commands might also have the same issue. 
The new source is also easier to parse (all the commands are listed on the main page) Looking at the future this is going to be more maintainable, and it's kinda harder to get things wrong with the new source :smile:

**Comment by danidee10** [comment]
@pjhampton The new source is easier to parse (all the commands are listed on the main page) Looking at the future this is going to be more maintainable, and it's kinda harder to get things wrong with the new source :smile: 

On the Other hand `adduser` is not really a *nix command, it's just a perl script that still calls `useradd` at the backend. Currently on my Machine (ArchLinux) I don't have `adduser`. so the IA's answer kinda makes sense :smile:

I think we should stick with the old source if another issue aside #273 hasn't been reported, because the new source has nothing on `adduser` too.

**Comment by pjhampton** [comment]
Hey @danidee10, 

So I'm confused by your first and third paragraph. Are you taking this forward or are we just updating the current IA?

**Comment by danidee10** [comment]
My point is changing the source won't really do much good if it's just to address #273 because the new source doesn't have a section for the `adduser` command

And i assume that they both cover the same set of commands (I'm yet to do a thorough check yet). So the new source doesn't add more commands to the IA.

**Comment by pjhampton** [comment]
Hey @danidee10, 
How are you getting on?
It's more about increasing the coverage and **improving the content**. The last fathead had one liner descriptions, causing people to click on SERP links instead of bouncing (seeing the IA and going). That is the purpose of this 😄

**Comment by danidee10** [comment]
@pjhampton i've created a new IA page https://duck.co/ia/view/manpages
