### ISSUE TITLE
SQLAlchemy: List all topic titles and language features to help measure coverage

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#735]
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/sqlalchemy

**Comment by himanshugarg** [comment]
May I claim this for upto 48hrs from assignment?

**Comment by pjhampton** [comment]
Hey @himanshugarg, it's all yours 😄

**Comment by TheDeBug** [comment]
im new to programming, i can programm little things but im not a professional, and thought if someone could "giude" me through a task like this and explain me somethings.... i would really appreciate if someone helped me.
I also would appreciate if i could just watch (idk how but we'll figure that out..) someone programm something and tells me what he's doing.

**Comment by pjhampton** [comment]
Hey @himanshugarg! Are you still working on this?

**Comment by himanshugarg** [comment]
Sorry @pjhampton . No. Please reassign.

**Comment by knowledgewarrior** [comment]
I'll take this task on.

**Comment by pjhampton** [comment]
Awesome, @knowledgewarrior! Thanks so much 💙  💛  💜

**Comment by knowledgewarrior** [comment]
https://github.com/duckduckgo/zeroclickinfo-fathead/pull/845
