### ISSUE TITLE
Cpp Boost Suggestion: Update the data source

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-fathead#739]
**Suggestion**

Update  the data source link http://www.boost.org/doc/libs/1_62_0/ to the new data source link
http://www.boost.org/doc/libs/1_63_0/

------
IA Page:  http://duck.co/ia/view/cpp_boost 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nikhilsingh291

**Comment by pjhampton** [comment]
Thanks for suggesting this @adityatandon007. I don't think this will necessarily improve coverage or impact of this IA, but we should always strive to have the latest source. Are you going to take this forward?

**Comment by adityatandon007** [comment]
@pjhampton Yeah, I will look into this. Also that deprecated cpp reference is not removed from IA. It still triggers and sometimes clashes with this IA.

**Comment by nikhilsingh291** [comment]
@adityatandon007 There is almost no difference between 1.62 and 1.63 library. The number of functions listed is exactly the same. Just a few character changes in the description. We can simply move on by changing the source url only. I don't think there is a need to create a new IA for this.

**Comment by adityatandon007** [comment]
@nikhilsingh291 You didn't get me. I was not taking about your IA . There is this IA https://duck.co/ia/view/cppreference_doc which I was talking about which is deprecated and sometimes clashes with your IA triggers. Yeah you can change the source url or if you want I can change the url so that we always have the latest available for our audiences.

**Comment by adityatandon007** [comment]
@nikhilsingh291 One more thing I want to ask Why is that your IA triggers for some and doesn't trigger at all for other. Ex: cpp boost ref trigger and cpp boost smart ptr doesn't trigger. Though when I looked into your output.txt it has the title for smart ptr. Here are the screenshots
![screenshot from 2017-02-06 13-42-11](https://cloud.githubusercontent.com/assets/25108385/22639094/4899d2f4-ec72-11e6-894e-3bb65ae6f3c0.png)
![screenshot from 2017-02-06 13-43-08](https://cloud.githubusercontent.com/assets/25108385/22639093/4896d28e-ec72-11e6-8655-a56bca5df071.png)

**Comment by nikhilsingh291** [comment]
@adityatandon007 Even I noticed that but couldn't figure out why that happens.

**Comment by pjhampton** [comment]
@adityatandon007 Please always strive to be as clear as possible when creating issues so there is no confusion 👍 
No, cppreference_doc is not yet deprecated. We are still discussing it in favor of rebuilding as we don't have the code to update it.
As for `smart prt`, it could be a problem with the description in the output.txt file.

**Comment by adityatandon007** [comment]
@pjhampton I didn't mean to create confusion. I apologize for that. It's just that I am very new to the open source world and still learning the etiquettes on how I can be more effective and more clear. Although suggestions and feedback from someone like you do help a lot. :hugs: :smile: :innocent: 
I looked into the output.txt file. I couldn't figure out. Even @nikhilsingh291 couldn't get get this thing. Can you please help :+1:

**Comment by pjhampton** [comment]
You are in the right place! You're more than welcome in the DuckDuckHack community and always will be. We all appreciate your enthusiasm. 

Does the entry show up in codio?

**Comment by adityatandon007** [comment]
@pjhamptop I tried to run this command in codio  
DDG_TEST_FATHEAD=<lib/fathead/cpp_boost/> prove -Ilib t/validate_fathead.t

and it printed 
-bash: -Ilib: command not found
Is it something wrong with this command
