### ISSUE TITLE
NPM CLI: Parser throwing requests.exceptions.SSLError.

### ISSUE THREAD

**Issue by souravbadami** [duckduckgo/zeroclickinfo-fathead#740]
### Description

Parser throws requests.exceptions.SSLError. Here's the traceback.

```
Traceback (most recent call last):
  File "parse.py", line 151, in <module>
    get_page_links()
  File "parse.py", line 135, in get_page_links
    page = requests.get(START_URL)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'docs.npmjs.com' doesn't match either of 'a.sni.fastly.net', 'a.sni.global-ssl.fastly.net'
```

## Steps to recreate

Try to run `parse.sh` from the npm_cli directory.

## People to notify

@moollaza @rahulxxarora 

---

Instant Answer Page: https://duck.co/ia/view/npm_cli

**Comment by rahulxxarora** [comment]
@souravbadami I tried running it on my codio environment too, but it didn't give me any error @moollaza  what could be the reason here?

**Comment by pjhampton** [comment]
According to this article in their documentation, Python 2.7.6 (The version installed by default on codios box) doesn't include native support for SNI in their SSL modules. Which **_could_** be causing this issue. I can't reproduce either. Can you please upgrade to Python 2.7.10(or +) and try again @souravbadami 😄 

http://docs.python-requests.org/en/master/community/faq/#what-are-hostname-doesn-t-match-errors

**Comment by souravbadami** [comment]
Ah, I tried it on **codio** and it's working fine there. Also, It's working fine on my local system with `Python 2.7.6` now without any upgrade.
