### ISSUE TITLE
CPP Boost: Overtriggering

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-fathead#749]
**Issue Description**:

This IA triggers for any query related to things like cpp preprocessor. This happens because boost has a preprocessor title in output.txt which matches but the search is simply regarding cpp preprocessor and not cpp boost preprocessor.

Below is the screenshot 

![screenshot from 2017-02-07 01-02-51](https://cloud.githubusercontent.com/assets/25108385/22663692/8cd0d100-ecd3-11e6-8f64-551abf97e046.png)

**People to notify** 

@pjhampton @sahildua2305 

------
IA Page:  http://duck.co/ia/view/cpp_boost 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nikhilsingh291

**Comment by pjhampton** [comment]
Space Coverage is less than 1% - https://forum.duckduckhack.com/t/c-boost-fathead/1368
We can remove `cpp` for now as a trigger and reevaluate the unanswered query data in 2 - 4 weeks. What do you think @sahildua2305?

I guess another option would be giving higher priority to the outgoing cpp_reference

**Comment by adityatandon007** [comment]
@pjhampton @sahildua2305 we can remove cpp for now as a trigger but there is one minor change that I would like to bring into your knowledge it should not trigger for <cpp> but it should trigger for <boost cpp> when boost cpp is at the end. Currently it triggers only for starting <cpp boost> triggers but not ending. Here are the screenshots 
![screenshot from 2017-02-07 01-45-42](https://cloud.githubusercontent.com/assets/25108385/22664791/36ae3024-ecd8-11e6-8f59-a9e8f74ee1ee.png)
![screenshot from 2017-02-07 01-52-35](https://cloud.githubusercontent.com/assets/25108385/22664792/36b0c42e-ecd8-11e6-9aeb-d617b62c0a91.png)

**Comment by moollaza** [comment]
> Currently it triggers only for starting cpp boost triggers but not ending.

This is due to a known, internal bug -- we don't have a fix for it right now though.

**Comment by adityatandon007** [comment]
@moollaza So, should I close this issue for now.

**Comment by sahildua2305** [comment]
@moollaza @adityatandon007 does it trigger when keyword is in the middle of the query? For example, for this query - `cpp boost ref` if we remove `cpp` from the trigger?

**Comment by adityatandon007** [comment]
@sahildua2305 it does trigger for boost ref (after removing cpp from the trigger). I think something was recently added to the triggrer_words.txt file. This is what I have mentioned earlier that there is something generic going on with this IA and we should avoid generic triggering and therefore I created this issue in the first place.

**Comment by adityatandon007** [comment]
@sahildua2305 I think @moollaza recently added this **boost** in the trigger_words.txt if I remember it correctly and I think it became now more inconsistent.

**Comment by adityatandon007** [comment]
yeah @sahildua2305 I found it and I was correct. here is the [https://github.com/duckduckgo/zeroclickinfo-fathead/commits/master/lib/fathead/cpp_boost/trigger_words.txt](url)

**Comment by adityatandon007** [comment]
@sahildua2305 I also think that we should remove this **boost** trigger because boost and anything related to title of that output.txt file can trigger this IA which user might not want to see. Like he might type "boost spirit" and he want to see the answer regarding how to boost spirit but instead he would see this IA result which we didn't want in the first place. 
![screenshot from 2017-02-14 04-06-44](https://cloud.githubusercontent.com/assets/25108385/22906582/1e20a49a-f26b-11e6-9d96-4b2f903abe32.png)

**Comment by sahildua2305** [comment]
> I also think that we should remove this boost trigger

I agree

**Comment by adityatandon007** [comment]
I will make the changes and then let you know

**Comment by adityatandon007** [comment]
@sahildua2305 I have updated the triggers. I have also removed the cpp trigger too avoid the clashes with cpp reference fathead. If you suggest it's not right then I can add that in the trigger_words.txt file.

**Comment by adityatandon007** [comment]
@sahildua2305 Please review
