### ISSUE TITLE
Numpy: Improve Redirects

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#751]
Numpy queries make up a huge part of the Python Search Space so we need to get it right. It seems that there is a redirect issue in [output.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/e44b6520fa67ed6dca5f96dd9baf629205965c41/lib/fathead/numpy/output.txt). 

```
numpy.absolute	A										<section class="prog__container"><p>Calculate the absolute value element-wise.</p><pre><code>numpy.absolute(x[, out]) = <ufunc 'absolute'></code></pre><span class="prog__sub">Parameters:</span><pre><code>x : array_like\n    Input array.</code></pre><span class="prog__sub">Returns:</span><pre><code>absolute : ndarray\n    An ndarray containing the absolute value of each element in x.  For complex input, a + ib, the absolute value is .</code></pre></section>	https://docs.scipy.org/doc/numpy/reference/generated/numpy.absolute.html
numpy absolute	R	numpy.absolute		
```

It turns out `numpy absolute	R	numpy.absolute` is redundant, because the query parser ignores `.`. So this redirect would trigger on `numpy numpy absolute`. This needs to be fixed. If we could update the redirects to omit `numpy` that would be great. 

So the redirects should look as follows:

```
absolute	R	numpy.absolute
```

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/numpy
Maintainer: @ashishbhate

**Comment by adityatandon007** [comment]
@pjhampton Can I look into this

**Comment by ashishbhate** [comment]
If I understand the issue correctly, then the fix is pretty simple. `get_redirects` in `parse.py` will need to be changed to something like the following:

```
def get_redirects(title):
    redirects = set()
    title_split = title.split(".")
    if title_split[0] == PACKAGE_NAME:
        title_split = title_split[1:]

    redirects.add(".".join(title_split))
    redirects.add(" ".join(title_split))
    return redirects
```

**Comment by adityatandon007** [comment]
@ashishbhate I have messaged you on slack
