### ISSUE TITLE
Angularjs (1.x) Suggestion: Add further redirect

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#755]
## Description
 
It seems from the unanswered query data a lot of people are searching for `angular js` as well as `angularjs` and `angular`. It would be good to update this trigger and see if it improves the coverage of this IA. 

## People to notify

Lang Leader: @bfmags 
Maintainer: @rafaelpadovezi

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/angularjs

**Comment by adityatandon007** [comment]
@pjhampton Hi, :smile: can I take this

**Comment by pjhampton** [comment]
@adityatandon007 it's all yours! 😄  Thanks!

**Comment by rafaelpadovezi** [comment]
@adityatandon007 Great!
