### ISSUE TITLE
Swift Suggestion: Update docs from 2.2 to 3.1

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#757]
## Description

Update the source of the docs from [2.2](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/swiftdocs/swift/src/parse.js#L28) to [3.1](http://swiftdoc.org/v3.1/)

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/swiftdocs

**Comment by adityatandon007** [comment]
@pjhampton can I give it a try :question:

**Comment by adityatandon007** [comment]
@pjhmapton please reply on slack
