### ISSUE TITLE
React.js Suggestion: Improve Redirects

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#758]
## Description
There is a problem with the [redirects that needs fixed](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/reactjs/). It seems that we might need to add trigger words as well.

**react.component** triggers

![screen shot 2017-02-08 at 7 35 47 pm](https://cloud.githubusercontent.com/assets/8960296/22753994/ecad6b52-ee35-11e6-8e1c-ab7eb4cc9637.png)

**react component** does not
![screen shot 2017-02-08 at 7 35 18 pm](https://cloud.githubusercontent.com/assets/8960296/22754000/f534c7fc-ee35-11e6-980e-ae3b0c050e32.png)

## People to notify
Lang Leader: @bfmags 
Maintainer: @dip-kush 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/reactjs

**Comment by Hestben** [comment]
I would like to take a look at this. First try showed that parse.sh doesn't run. Maybe the doc source has changed its format =/

**Comment by pjhampton** [comment]
Thanks @Hestben!! And yes, that's possible. Let me know if that's the case and we can create an issue

**Comment by Hestben** [comment]
@pjhampton It is not easy to see if they have changed their design, since, they seem to have a rolling release of the docs, and not locked to each released react version. I think it is safe to say that something has broken recently.
Do you think we need to create a different issue for this? I think I could solve both things in this issue.

**Comment by pjhampton** [comment]
If you think you can solve it, that is fine @Hestben. Please just make sure the git trail is clear. For example, **fixed parse error** -> **improve redirects** -> _future tasks_. I don't we have been doing a great job of this so far in this repository.

**Comment by Hestben** [comment]
@pjhampton I see. If I fix both things in one PR, the commits will be squashed into one commit. Maybe it is more clear if those things are fixed in different PRs?

**Comment by pjhampton** [comment]
@Hestben Sure 👍

**Comment by Hestben** [comment]
@pjhampton OK, could I also create an issue for parsing error?

**Comment by pjhampton** [comment]
Yeah, sure thing! Just make sure to assign yourself 😄

**Comment by Hestben** [comment]
Hmm, I just found out, that the redirects.py is never executed. @bfmags Did you mean to run that in parse.sh, or is it supposed to be used separately? I see that it doesn't generate any output to output.txt. I think I will change so that it adds redirects to the output.txt, so we get the redirects in the output.

**Comment by pjhampton** [comment]
Hey @Hestben, 

This is supposed to be run separately. Redirects can go into the output.txt or cover directory 👍

**Comment by Hestben** [comment]
@pjhampton OK. So I take it the format "<redirect key>,<original article>" is correct.
I will simply modify the redirect.py to add more redirects.
I guess the cover directory is something you generate when deploying the fathead?

**Comment by Hestben** [comment]
@pjhampton I have looked in the redirects.txt it currently generates, and there is an entry `component,React.Component`. So, in my understanding of the fatheads, I guess the keyword `react` should trigger this fathead, and the redirects.txt seems to have the correct redirect. So my guess is that something internal does not trigger the redirect (where do you load in the redirects.txt? Have they been loaded?).
After more looking into the redirects, I don't see any of them triggering, so my guess is, that this manual step has been forgotten somewhere in the latest deployment.
This works [React.PureComponent](https://duckduckgo.com/?q=React.PureComponent&ia=about)
This does not [react purecomponent](https://duckduckgo.com/?q=react+purecomponent&ia=software)

**Comment by Hestben** [comment]
@pjhampton So, how should we go about this. I thought you may be looking at the internal works of this fathead, as I mentioned that the redirects look all right.
Or should I migrate this fathead from specifying redirects in a separate file, and output them to the output.txt instead?

**Comment by pjhampton** [comment]
Hmm, maybe the redirects have not been deployed with the Fathead. I am not part of the internal team so I can't check this myself. @moollaza, what is your take on this?

**Comment by Hestben** [comment]
@pjhampton, @moollaza  Are we getting anywhere with this PR?

**Comment by pjhampton** [comment]
Hey @Hestben!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
