### ISSUE TITLE
MDN CSS Suggestion: Improve Coverage with further redirects

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#762]
## Description

This Fathead is awesome, but based on the unanswered query data it's not triggering for a lot of searches. This issue is part experiment. We want to see if updating the redirects manually in [redirects.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/redirects.txt) will improve coverage for the CSS language space which can be seen on the [forum](https://forum.duckduckhack.com/t/css-search-overview/96). 

### Examples
These need to be included. Notice the query on the left, and the article to redirect to on the left. That's what we need to do for the below list. 
```
align center html, text-align
align in center html, text-align
center align html, text-align
css font align, text-align
center align image, text-align
center font css, text-align
background images, background-image
background linear gradient, linear-gradient
css font bold, font-weight
css body font, font-family
```

### The List
```
body font size 
change font 
change font color
define font-family 
font code 
font codes
font color 
font example 
font face 
font families
font height 
font italic 
font shadow 
font spacing 
font stack 
font style bold 
font tag 
font underline 
font-color 
import font 
set font 
font bold 
font families 
font spacing
font underline 
font-background 
html code font weight 
center text in css
ease-in 
position fixed in css 
position in css 
button style color 
html style bold 
html style bg color 
html style background color 
html style padding 
html style positioning 
html style text bold 
html style text size 
html style top 
html style underline 
html style uppercase 
style align center 
style text color 
text style capitalize css 
underline html style 
background color in html 
background color rgb 
background color linear gradient 
background-color gradient 
body background color 
background color gradient 
bg color 
font color 
foreground color 
text color 
font color
gradient color 
display block 
display flex 
display inline 
display inline-block 
display none 
display block html
```

## Steps to recreate

You can get the full list of articles with [this perl script](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/utils/extract_articles.pl) which can be run as `./get_article_titles.pl mdn_css`

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

**Comment by BillyBarbaro** [comment]
@pjhampton I wouldn't mind helping out on this issue, but I'm not 100% clear on what I'm supposed to do here.  I understand you want to create a redirect for each entry in the list, but what should it redirect to?  Maybe could you give an example for the first one or two on "The List"?

**Comment by pjhampton** [comment]
Hey @BillyBarbaro, 

Many thanks. Over the past week, the internal guys shifted their focus to improving existing IAs. You can see these here: 

- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3971
- https://github.com/duckduckgo/zeroclickinfo-spice/issues/3162

Closing as this is no longer high priority 👍  Hope you don't mind!
