### ISSUE TITLE
Python Suggestion: Improve Coverage with further redirects

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#765]
## Description

This Fathead is awesome, but based on the unanswered query data it's not triggering for a lot of searches. We want to see if updating the redirects manually in [the cover directory](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/python/cover) will improve coverage for the Python language space which can be viewed on the [forum](https://forum.duckduckhack.com/t/python-search-overview/97/). 

### Examples
Notice the query on the left, and the article to redirect to on the left. That's what we need to do for the below list. **This can be done manually!**
```
align center html, text-align
align in center html, text-align
center align html, text-align
css font align, text-align
center align image, text-align
center font css, text-align
background images, background-image
background linear gradient, linear-gradient
css font bold, font-weight
css body font, font-family
```

### The List
```
class 
classes
class __str__ 
cpickle 
csv quote 
csv read 
dict to json 
dict get 
dicts in 
elif 
enum list 
for loop in 
if else 
call process 
__add__ 
__builtin__ 
__dict__ 
__doc__ 
__hash__ 
__import__ 
__nonzero__ 
__version__ 
datetime.datetime.strptime 
datetime.datetime 
datetime tzinfo 
datetime to timestamp 
datetime tzinfo 
datetime without hour 
AND 
AND && 
assert statement 
byte array 
bytearray 
def
file open 
file write 
format string 
glob 
lambda
logging 
multithreading 
next
object
os module 
os mkdir
os.environ 
os.chdir
```

## Steps to recreate

You can get the full list of articles with [this perl script](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/utils/extract_articles.pl) which can be run as `./get_article_titles.pl python`

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

**Comment by mustang25** [comment]
@pjhampton I'd be interested in picking this project up.

**Comment by pjhampton** [comment]
Thanks so much, @mustang25!

**Comment by mustang25** [comment]
Hi @pjhampton, I just wanted to make sure that I am understanding things correctly. For all of the items in The List, I need to add an entry to functions.txt in the cover directory. Does this sound correct?

Also, I wanted to check what should be done if I can't find an article for one of the functions listed?

**Comment by pjhampton** [comment]
Hey @mustang25! Yep that's correct.

> Also, I wanted to check what should be done if I can't find an article for one of the functions listed?

That's fine and expected. Can you please take a note of them and let us know?

**Comment by hliu45** [comment]
I'm interested in the project, too.

**Comment by pjhampton** [comment]
Hey @hliu45,

Awesome! This project only requires one person working on it though! Fear not, there is loads of other stuff you can be helping with 😄  Checkout:

- https://github.com/duckduckgo/zeroclickinfo-spice/issues/3162
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3971

Hope you can help out sometime! 🚀

**Comment by pjhampton** [comment]
Looks like this can be closed off 👍 

Thanks everyone 💛
