### ISSUE TITLE
Django Suggestion: Extend parser to include submodules + methods

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#766]
### Description

This is a really cool IA, but it's not covering much of the search space and it's definitely under-triggering based on the unanswered query data. Currently, we are only scraping the top module and need information on sub modules and their methods. For example:

Triggers: `django admin`
Doesn't trigger: `django admin modelAdmin`

## People to notify
Maintainer: @vigzmv

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/django

**Comment by Hestben** [comment]
I am looking for something to do, so I might just take on this task :)

**Comment by pjhampton** [comment]
Awesome! Thanks so much @Hestben

**Comment by Hestben** [comment]
Taking a brief look at it, it looks like the current architecture doesn't allow for easily adding a module-submodule division. Am I at liberty to replace the it with the architecture used for the python-fathead?
