### ISSUE TITLE
Sqlalchemy parser throws IOError.

### ISSUE THREAD

**Issue by souravbadami** [duckduckgo/zeroclickinfo-fathead#770]
### Description

Sqlalchemy parser throws IOError. Here's the traceback:
`
Traceback (most recent call last):
  File "parse.py", line 409, in <module>
    dp.get_pages()
  File "parse.py", line 22, in get_pages
    file = open(file_loc,'r+')
IOError: [Errno 2] No such file or directory: 'download/events.html'
`
## Steps to recreate

Try to fetch the docs using `fetch.sh` and then parse using `parse.sh`.

## People to notify

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/sqlalchemy

**Comment by pjhampton** [comment]
Hey @souravbadami! Thanks for reporting

Reproduced. Yeah, this is going to need to be fixed 👍

**Comment by gautamkrishnar** [comment]
I think we need to remove the backup/ dir too @moollaza

**Comment by shravan97** [comment]
@gautamkrishnar , I already removed the backup dir in this PR : https://github.com/duckduckgo/zeroclickinfo-fathead/pull/756
