### ISSUE TITLE
Instant answers show Icon when it is disabled via customized DuckDuckGo Theme

### ISSUE THREAD

**Issue by anton19291** [duckduckgo/zeroclickinfo-fathead#783]
## BUG FIX

lyrics Bug: I disabled Icons in the DuckDuckGo Theme settings but in instant answers the Icon is still displayed.

## SUGGESTION
lyrics Suggestion: Either add a possibility to configure the instant answers seperately or take over the theme settings configured for duckduckgo

## Steps to recreate

Disable Icon display via the DuckDuckGo Theme settings. After that search for "torture lyrics" without ".

## People to notify

@moollaza 
@bsstoner 

---

https://duck.co/ia/view/lyrics

**Comment by pjhampton** [comment]
@anton19291 Can you please take a screenshot. I can't reproduce.

**Comment by anton19291** [comment]
![lyrics](https://cloud.githubusercontent.com/assets/7266161/22928731/a290dcf4-f2c0-11e6-9523-87dbcecb8eb3.png)

**Comment by anton19291** [comment]
![lyrics](https://cloud.githubusercontent.com/assets/7266161/22928774/cfccc976-f2c0-11e6-9431-1570ba69a068.png)

**Comment by anton19291** [comment]
Seems to be some kind of caching issue. Also The "Show visited symbol" is still there even after I deactivated it right now. I tried a refresh with shift but that didn´t help. I think this can be closed as it seems to be on my end.

**Comment by bsstoner** [comment]
Thanks for the suggestion. The setting was only intended to affect the organic links, but you have a valid point about also removing from IA's. I'll take it back to the team internally as nothing can be done here in this repo.
