### ISSUE TITLE
Spark: Fix Description Truncation & Articles that won't Triggering

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#786]
### Description

It seems that a couple of the articles for the Spark (Scala) reference are being truncated. It would awesome if we could get this fixed. It would probably be a lot more helpful.

**Screenshot 1**

![screen shot 2017-02-14 at 1 55 18 pm](https://cloud.githubusercontent.com/assets/8960296/22931648/4eb9c0a8-f2bd-11e6-87a0-ee26e0f614f5.png)

**Screenshot 2** (org.apache.spark.ml.feature.MinMaxScalerModel)

![screen shot 2017-02-14 at 1 58 32 pm](https://cloud.githubusercontent.com/assets/8960296/22931745/b5946d5a-f2bd-11e6-9d06-85b3080c7ad5.png)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request
- [ ] 5) Ping @pjhampton

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page:https://duck.co/ia/view/spark_scala_reference

**Comment by mrezende** [comment]
Hi @pjhampton, can I take look at this?

**Comment by pjhampton** [comment]
Hey @mrezende, of course you can! Thanks 😸

**Comment by moollaza** [comment]
@pjhampton @mrezende it looks like all the content is actually there -- for some reason though our JS that chomps the content to fit the max width isn't recognizing that there's overflowing text, so we're not showing the `+` button to expand the height...

/cc @andrey-p any thoughts on whats going on here?

E.g. https://duckduckgo.com/?q=org.apache.spark.accumulable&ia=about

**Comment by mrezende** [comment]
Hi @moollaza , if I change the url to duckduckgo.com/html, they expand the height. If the text has two <p> (paragraphs), they show the + signal to expand the height too. 

https://duckduckgo.com/?q=org.apache.spark.NarrowDependency&ia=about
