### ISSUE TITLE
Spark Suggestion: Add Redirects

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#788]
### Description

Currently, a user has to type in the full API path to get a description back from this IA. For example:

![screen shot 2017-02-14 at 2 08 33 pm](https://cloud.githubusercontent.com/assets/8960296/22932257/2317d56e-f2bf-11e6-8055-19b1a12af417.png)

As a result, this IA is undertriggering like crazy. Which is a shame! As a Spark user myself, I would love to search `ml QuantileDiscretizer` and it redirects to `org.apache.spark.ml.feature.QuantileDiscretizer`

An example of this in action is: https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/angularjs/output.txt#L1 where `R` is the redirect.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request
- [ ] 5) Ping @pjhampton

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/spark_scala_reference

**Comment by adityatandon007** [comment]
@pjhampton can I take a look at this
