### ISSUE TITLE
Spring Suggestion: Add Redirects (Split Casing)

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#789]
## Description

Spring is currently the most queried Java Web Framework work on DuckDuckGo, but this IA is under-triggering. I suspect because of the long class / method names and the fact the triggering doesn't reflect how a user queries. I think it would be good to experiment breaking up the camel / pascal / snake case with a regex and generating the redirects. 

**Triggering**

![triggered](https://cloud.githubusercontent.com/assets/8960296/22939153/b068214c-f2d5-11e6-90c7-8f80f77cd856.png)

**Not Triggering**

![nottriggered](https://cloud.githubusercontent.com/assets/8960296/22939163/b9e12a98-f2d5-11e6-9600-42b1b8a3b354.png)

An example of this in action is: https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/angularjs/output.txt#L1 where R is the redirect.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request
- [ ] 5) ping @pjhampton

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/spring_framework

**Comment by BillyBarbaro** [comment]
May I claim this issue?

**Comment by mandekisd** [comment]
Sure!

Dimitrios Mandekis
Email: dimitrios@ingenioussolutions.org <mailto:dimitrios@ingnss.com> | Website: https://ingenioussolutions.org <http://ingnss.com/> | LinkedIn: Personal Page <http://www.linkedin.com/in/dimitriosmandekis> - Company Page <https://www.linkedin.com/company/ingenious-solutions?trk=top_nav_home> | Mobile: +32 (0) 486 421 754 <tel://0032486421754>
