### ISSUE TITLE
Wikipedia: 

### ISSUE THREAD

**Issue by alsdfjldafsjalsfjk** [duckduckgo/zeroclickinfo-fathead#795]
Please write the age of persons and not only the birth date.

------
IA Page:  http://duck.co/ia/view/wikipedia_fathead 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
Thanks for the feedback on this Fathead @alsdfjldafsjalsfjk! This is out of scope for a Fathead, I'm afraid. Please check out the docs for this repo here: https://docs.duckduckhack.com/resources/fathead-overview.html

In future, it may be better to record your feedback on the SERP. The search team look through each of these individually.
