### ISSUE TITLE
Redirects with Non-Alphanumeric characters not working

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#796]
## Description

When analyzing the redirects of the NPM CLI Fathead I noticed that redirects with non-alphanumeric characters are not triggering. Two examples include:

  - https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/npm_cli/output.txt#L152
  - https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/npm_cli/output.txt#L144

If a person searches for `npm set --global` which is the correct redirect, the IA won't trigger. If the dashes are omitted (`npm set global`), it does.

Is this a bug, or is this expected behavior? 

## People to notify

- @moollaza 
- @MariagraziaAlastra 

---

Instant Answer Page: None

**Comment by adityatandon007** [comment]
@pjhampton I was just causally going through the `output.txt` and suddenly I noticed something strange. The file has multiple entries of `cache add`
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/npm_cli/output.txt#L20

and there are two entries for which redirects doesn't make sense there is a `.`(dot) in the entry 
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/npm_cli/output.txt#L41
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/npm_cli/output.txt#L42

https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/npm_cli/output.txt#L48
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/npm_cli/output.txt#L49

**Comment by pjhampton** [comment]
Hmm, so it turns out that `-` is replaced with a space. This is troublesome. I will pass this onto the internal guys in case they have a fix for this.
