### ISSUE TITLE
NPM CLI Bug: More info always link to the same page

### ISSUE THREAD

**Issue by itai421** [duckduckgo/zeroclickinfo-fathead#798]
In both [npm update](https://duckduckgo.com/?q=npm+update&ia=about) and [npm install](https://duckduckgo.com/?q=npm+install+&ia=about) pressing the title or the `More at NPM Documentation ` link redirects to [https://docs.npmjs.com/cli/access](https://docs.npmjs.com/cli/access)
   

------
IA Page:  http://duck.co/ia/view/npm_cli

**Comment by pjhampton** [comment]
Thanks @itai421 
Are you taking this forward?

**Comment by itai421** [comment]
yes, as we speak :)
