### ISSUE TITLE
PyPi: Improvements regarding taking spaces into account

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-fathead#808]
**PyPi Improvements:**
This IA needs some improvement since its of pypi (python common modules and shows how to install them using pip).

**Issues:**

1. This IA doesn't take **spaces** into account.

2. Showing some inconsistency with more at (bottom of IA)
This IA shows the both links at the bottom for `python beautifulsoup` but does not shows both the links at for `python beautiful soup4` Although the reverse might not have been such a issue (like showing only one for `python beautiful soup` but showing both the links for `python beautiful soup4` because beautifulsoup is **obsolete** and beautiful soup4 is **current**)

**People to notify:**

@pjhampton @moollaza 

**Steps to recreate:** 

**Issue 1:**

For example: It triggers for `python pandas`, `python numpy` but does not trigger for 
`python beautiful soup` though it triggers for `python beautifulsoup`.

Similarly, it does trigger for `python beautiful soup4` but does not trigger for `python beautiful soup 4`

**Screenshots:**  Below are the screenshots to help you understand the issue more clearly.

![screenshot from 2017-02-21 16-54-57](https://cloud.githubusercontent.com/assets/25108385/23163888/7c455aa8-f85a-11e6-9f53-bfb0b36f1cb9.png)

![screenshot from 2017-02-21 17-01-43](https://cloud.githubusercontent.com/assets/25108385/23163902/90561258-f85a-11e6-860a-1aa055ad21ca.png)

![screenshot from 2017-02-21 17-00-57](https://cloud.githubusercontent.com/assets/25108385/23163925/a7e8ebf2-f85a-11e6-8d75-5b59a01330a8.png)

![screenshot from 2017-02-21 17-03-43](https://cloud.githubusercontent.com/assets/25108385/23163933/b3102e8c-f85a-11e6-8c1e-db775d4dfae4.png)

![screenshot from 2017-02-21 17-04-28](https://cloud.githubusercontent.com/assets/25108385/23163939/bbbd0870-f85a-11e6-92b4-1ff55fe31a55.png)

**Issue 2:**

Just type `python beautifulsoup` and `python beautiful soup4` and check the links at bottom

**Screenshots:**

![screenshot from 2017-02-21 17-01-43](https://cloud.githubusercontent.com/assets/25108385/23164954/cf0b0ac6-f85f-11e6-8f5e-a371e04bcc75.png)

![screenshot from 2017-02-21 17-03-43](https://cloud.githubusercontent.com/assets/25108385/23164962/d5d0690a-f85f-11e6-9278-d9232ed71fd1.png)

------
IA Page:  http://duck.co/ia/view/py_pi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ezgraphs

**Comment by pjhampton** [comment]
Thanks for reporting this!
We are hoping to deprecate this fathead in favor for https://github.com/duckduckgo/zeroclickinfo-spice/issues/3101 so we have access to the entire package manager. Further, package managers are best served through a spice.

We can pick this up when the developer drops a PR 😄

**Comment by pjhampton** [comment]
We can close this I think based on  duckduckgo/zeroclickinfo-spice#3101
