### ISSUE TITLE
PyPi: Showing some inconsistency with more at (bottom of IA)

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-fathead#809]
**Issue:**

This IA shows the both links at the bottom for `python beautifulsoup` but does not shows both the links at for `python beautiful soup4` Although the reverse might not have been such a issue (like showing only one for `python beautiful soup` but showing both the links for `python beautiful soup4` because beautifulsoup is **obsolete** and beautiful soup4 is **current**)

**People to notify:**

@pjhampton @moollaza 

**Steps to recreate:**

Just type `python beautifulsoup` and `python beautiful soup4` and check the links at bottom

**Screenshots:**

![screenshot from 2017-02-21 17-01-43](https://cloud.githubusercontent.com/assets/25108385/23164683/66ea745a-f85e-11e6-93cf-b00654e9adb9.png)

![screenshot from 2017-02-21 17-03-43](https://cloud.githubusercontent.com/assets/25108385/23164693/78719cf8-f85e-11e6-9ca8-94fc27f39491.png)

------
IA Page:  http://duck.co/ia/view/py_pi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ezgraphs

**Comment by pjhampton** [comment]
Please combine this issue with https://github.com/duckduckgo/zeroclickinfo-fathead/issues/809 due to it being on hold. Also it will reduce discussion noise in the repo 👍

**Comment by adityatandon007** [comment]
I was thinking that
