### ISSUE TITLE
Flask Suggestion: Add Redirects

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#817]
### Description

The flask fathead is awesome! The problem with it though is it isn't triggering. For example:

`flask.Flask.wsgi_app` Triggers: https://duckduckgo.com/?q=flask.Flask.wsgi_app&t=h_&ia=about
`flask wsgi_app` doesn't trigger: https://duckduckgo.com/?q=flask+wsgi_app&t=h_&ia=qa

We can either extend the parser [[example](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mongoosejs/output.txt#L577)] or add manually redirects in the `cover directory` [[example](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/pep/cover/redirects.txt)]. It's upto the developer.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request
- [ ] 5) Ping @shanmbic or @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/flask

**Comment by shanmbic** [comment]
@pjhampton Cool ! On it now . Will extend the parser to add the redirects :)

**Comment by pjhampton** [comment]
Nice! Thanks @shanmbic 😄

**Comment by Logan1x** [comment]
@shanmbic  are you currently working on this or want to pass on me??
