### ISSUE TITLE
Pip Suggestion: Remove command keyword

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#818]
### Description

This fathead is pretty cool, but it's not triggering. I think this is because people are searching for commands such as:

```
pip freeze
pip search
```

and not:

```
pip freeze command
pip search command
```
In this low-hanging fruit issue, we need to removed the command word from the trigger sequence.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by BillyBarbaro** [comment]
@pjhampton Could you add me as the developer on this one?
