### ISSUE TITLE
Six Suggestion: Generate redirects for methods / functions

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#819]
### Description

There is a really promising Fathead, but it's still early days to determine what to do next. One thing that the unanswered query data is suggesting is that we add redirects. We could add the methods.txt and functions.txt file described here: https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html

This would be simple enough to do by just extending the parser.

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request
- [x] 5) Ping @pjhampton for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python_six_library

**Comment by BillyBarbaro** [comment]
@pjhampton May I take this one?  One quick question, it looks like functions.txt includes the trigger words in methods.txt plus a couple extra.  Is it necessary to create both of these, or would having only functions.txt suffice?

**Comment by pjhampton** [comment]
Hey @BillyBarbaro,

You're right. `functions.txt` is sufficient 😄  thanks!

**Comment by Logan1x** [comment]
@BillyBarbaro can you help me to understand what is this issue about?

**Comment by BillyBarbaro** [comment]
Hi @Logan1x. So I've got the start of a PR for this open [here](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/837).  Feel free to build off of that or start from scratch.

So Fatheads are all based off the entries in the output.txt file (I can expound on this if you're unfamiliar).  So when a user searches for the first entry on any line, they'll get the information included in that line.  For example, if there's an article named next.  When the user searches next, it triggers a match and our result is displayed.

Sometimes users don't search for the title exactly.  They might search something like 'func next' but we still want our article to surface.  So by adding titles to functions.txt (or the other files you can read more about on the linked pages), the backend automagically knows to also match the article titles in the file to these alternate patterns.

Also, here's the link @pjhampton was referring to: [https://docs.duckduckhack.com/fathead-reference/creating-effective-fatheads.html](https://docs.duckduckhack.com/fathead-reference/creating-effective-fatheads.html)

Feel free to let me know if you have any further questions.

**Comment by Logan1x** [comment]
@BillyBarbaro please provide me any social link to connect to you i am really want to understand and contribute to this project.

**Comment by BillyBarbaro** [comment]
Sure.  Feel free to DM me in the Slack.  My username is billybarbaro.
