### ISSUE TITLE
ESLint Suggestion: Add Examples to Description

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#822]
### Description

This is quite a popular IA, but the high Click Through Rate (66.7%) suggests that it's not helpful for those searching the command. I _think_ it might be because it doesn't have the examples listed:

![screen shot 2017-02-23 at 7 38 00 pm](https://cloud.githubusercontent.com/assets/8960296/23275882/09eb0b90-fa00-11e6-82e4-615010898afa.png)

![screen shot 2017-02-23 at 7 38 45 pm](https://cloud.githubusercontent.com/assets/8960296/23275884/0e430846-fa00-11e6-8255-62833ac59e62.png)

I think we should scrape and include the examples to see if we can get the CTR down!

## People to notify

@zodiac403
@moollaza 
@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request
- [ ] 5) Ping @zodiac403 or @pjhampton

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/eslint

**Comment by zodiac403** [comment]
Hi @pjhampton,
you're right. Currently the content is rather thin. I am already working on displaying more details for each article. To keep you updated, I'll try to open a pull request here.

**Comment by pjhampton** [comment]
Hey @zodiac403,
That's awesome! Thank you!

You can see traffic data on the forum - it's not currently there due to a problem with discourse API limits. Hopefully, this will be fixed soon. The CTR is an internal metric. I can keep you updated on its movement if you like.

**Comment by zodiac403** [comment]
PR still open, waiting for a review.
