### ISSUE TITLE
Launchpad: Improvements and Suggestions required regarding triggering

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-fathead#836]
**Issue:**

Searching for **kali download** triggers this launchpad IA and shows the description which is somewhat related to IRC service, which the user might not want to see (in most cases since he had typed the query as **kali download**). In case, if we want to trigger the IA at all, then something related to kali linux should be displayed, or we shouldn't trigger at all, because this reflects bad or false judgement on part of DDG search.

**People to notify:**
@moollaza 

**Steps to recreate:**
Just type **kali download** and see the answer 

**Screenshots:**

![screenshot from 2017-02-26 12-45-57](https://cloud.githubusercontent.com/assets/25108385/23337949/d4b5f2c0-fc23-11e6-8ec7-deecb57cb7fa.png)

IA Page:  http://duck.co/ia/view/launchpad 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
It doesn't seem like this issue has a lot of weight behind it. Closing for now 👍
