### ISSUE TITLE
Node.js Suggestion: Improve Descriptions

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#840]
### Description

This is a really popular Fathead, but it has a steady upwards trend for the Click Through Rate. This indicates that the content of the IA is not answering the users query. After a bit of looking about, I think we can improve this in 2 ways:

1) Improve the descriptions

![screen shot 2017-02-27 at 6 58 15 pm](https://cloud.githubusercontent.com/assets/8960296/23375124/171c33e4-fd1f-11e6-8073-676e5e299334.png)

2) Add `node js` as a trigger word

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request
- [x] 5) Ping @bfmags for a review

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/node_js

**Comment by Lord-Lavios** [comment]
I've given it a try.
