### ISSUE TITLE
Scipy Suggestion: Improved Redirects

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-fathead#841]
### Description

This IA is pretty popular, and it is really well developed. The problem with it is that people are not searching for the full path, such as `scipy fftpack fft2`, they are searching for the likes `scipy fft2`. This is problematic if there is function naming collisions. I don't think there is, so it should be ok to take the last section of the path and create a redirect. 

**Triggering**

![screen shot 2017-02-27 at 8 29 56 pm](https://cloud.githubusercontent.com/assets/8960296/23378781/55dfdf1a-fd2c-11e6-87ef-ee0b3e18f7b4.png)

**Not Triggering**

![screen shot 2017-02-27 at 8 30 48 pm](https://cloud.githubusercontent.com/assets/8960296/23378785/5b4a082c-fd2c-11e6-8ba2-60899eae9420.png)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/scipy

**Comment by ashishbhate** [comment]
I'll take a look at this. I don't think there are collisions either, but if there are I can just skip those redirects.

**Comment by ashishbhate** [comment]
I was wrong, there are lot of collisions. I'm not sure I should be skipping collisions.

E.g. `add_points`  
['scipy', 'spatial', 'ConvexHull', 'add_points']
['scipy', 'spatial', 'Delaunay', 'add_points']
['scipy', 'spatial', 'Voronoi', 'add_points']

`antiderivative`:
['scipy', 'interpolate', 'Akima1DInterpolator', 'antiderivative']
['scipy', 'interpolate', 'BPoly', 'antiderivative']
['scipy', 'interpolate', 'CubicSpline', 'antiderivative']
['scipy', 'interpolate', 'InterpolatedUnivariateSpline', 'antiderivative']
['scipy', 'interpolate', 'LSQUnivariateSpline', 'antiderivative']
['scipy', 'interpolate', 'PPoly', 'antiderivative']
['scipy', 'interpolate', 'PchipInterpolator', 'antiderivative']
['scipy', 'interpolate', 'UnivariateSpline', 'antiderivative']
['scipy', 'interpolate', 'pchip', 'antiderivative']
['scipy', 'interpolate', 'ppform', 'antiderivative']

This is just a small sample; there are a lot more collisions. I dont have the data on the search terms that are not triggering, but if it's a small list we can just manually add them.

**Comment by pjhampton** [comment]
Hmm, thanks for reporting back @ashishbhate. I think for now we should skip any collisions for now.

Maybe we should take note of them though in the `cover/` dir in a file called uncovered.txt - this could give us a starting point to a new issue once we decide on how to go forward. What do you think?

cc. @moollaza

**Comment by ashishbhate** [comment]
Generating a list of collisions is quite easy so I don't think we need to take save them specifically. There are also a lot of them. 

Based on the search data analytics we could generate redirects for the most popular search terms. E.g. if we know that a lot of people search for `scipy fft2` instead of `scipy fftpack fft2` we could just manually add this redirect to a file. The parser, while parsing the scipy docs, could read this file, check that the redirect is valid (i.e. `scipy fftpack fft2` article exists) and include that redirect.
