### ISSUE TITLE
Bower CLI: Missing the entry for bower unregister

### ISSUE THREAD

**Issue by adityatandon007** [duckduckgo/zeroclickinfo-fathead#853]
**Issue**
Searching for `bower unregister` doesn't display anything, although there is a 'unregister' command for bower.

**Screenshot** 

![screenshot from 2017-03-03 03-31-25](https://cloud.githubusercontent.com/assets/25108385/23529187/a470f1d0-ffc2-11e6-84ca-1e2a51643de8.png)

------
IA Page:  http://duck.co/ia/view/bower 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @NamPNQ__

**Comment by adityatandon007** [comment]
This is fixed in #852

**Comment by pjhampton** [comment]
Fixed in #852
