### ISSUE TITLE
Suggestion: New Fathead for Socket.io

### ISSUE THREAD

**Issue by Lord-Lavios** [duckduckgo/zeroclickinfo-fathead#859]
### Description
New fathead for [socket.io](https://github.com/socketio/socket.io/blob/master/docs/README.md#api-reference).

## People to notify
@pjhampton @moollaza 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by pjhampton** [comment]
Hey @Lord-Lavios!

That's awesome. It doesn't seem like there are many queries for socket.io so we won't put any community effort here for now. Saying that we are now starting to shift focus from the programming mission to improving existing IAs. Checkout:

- https://github.com/duckduckgo/zeroclickinfo-spice/issues/3162
- https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3971

Hope you can help out sometime! 😄
