### ISSUE TITLE
MDN JavaScript: HTML in Summary isn't escaped

### ISSUE THREAD

**Issue by GeraldNDA** [duckduckgo/zeroclickinfo-fathead#867]
Example: https://duckduckgo.com/?q=FileList+js
The html for <input type='file'> is rendered. I don't think it should ... 

------
IA Page:  http://duck.co/ia/view/mdnjs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ericedens

**Comment by pjhampton** [comment]
Passing comments to internal team.
