### ISSUE TITLE
OReilly: The More on O'Reilly link is broken

### ISSUE THREAD

**Issue by nikwen** [duckduckgo/zeroclickinfo-fathead#869]
**Example: Search for "linux cat"**

Link points at http://oreilly.com/linux/command-directory/cmd.csp?path=c/cat
Redirects to http://shop.oreilly.com/category/browse-subjects/system-administration/linux-unix.do?path=c/cat

What I see:

![Screenshot](https://cloud.githubusercontent.com/assets/3309657/24713642/8a2c0a8e-1a26-11e7-9bee-01f874bab7b8.png)

------
IA Page:  http://duck.co/ia/view/oreilly 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by AasthaGupta** [comment]
The link has changed to http://archive.oreilly.com/linux/cmd/cmd.csp?path=c/cat

**Comment by pjhampton** [comment]
Thanks @nikwen and @AasthaGupta hopefully we can get this updated and live again. If either of you wants to patch this to speed up the process, feel free 😄

**Comment by AasthaGupta** [comment]
@pjhampton I was looking for oreilly directory in lib/fathead/ but it is not there.

**Comment by moollaza** [comment]
This has been fixed. The Fathead is an old internal one, so there is no open source code
