### ISSUE TITLE
Freshmeat: discontinued for years

### ISSUE THREAD

**Issue by da2x** [duckduckgo/zeroclickinfo-fathead#870]
This plugin should be removed from production.

"Effective 2014-06-18 Freecode is no longer being updated (content may be stale)."
Well, content has been outdated and stale for years already.

------
IA Page:  http://duck.co/ia/view/freshmeat 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
Passing comments to internal team.
