### ISSUE TITLE
Ports Suggestion: Show port number, when service name is searched

### ISSUE THREAD

**Issue by mueller-ma** [duckduckgo/zeroclickinfo-fathead#878]
### Description

When searching for a service name, it would be nice to see the port number

## Steps to recreate

Search for "https port". no IA is seen

## People to notify

---

IA Page:  http://duck.co/ia/view/ports 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

**Comment by pjhampton** [comment]
Hey @mueller-ma 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.
