### ISSUE TITLE
Wikihow: Possible XSS Vulnerability

### ISSUE THREAD

**Issue by javathunderman** [duckduckgo/zeroclickinfo-fathead#898]
Seems that in some Wikihow answers that include HTML source code as part of the article, the IA is actually rendering it rather than just showing the source alone. (See step 4 in IA box below). Bug was first reported on [this](https://www.reddit.com/r/duckduckgo/comments/8mvetm/xss_vulnerability_on_duckduckgo_a_howto_on/) /r/duckduckgo post. 

![image](https://user-images.githubusercontent.com/6887325/40684247-e0812f72-635e-11e8-8cc1-8efb8d4b7b24.png)
https://duckduckgo.com/?q=how+to+create+big+block+text+box

@duckduckgo/community-leaders 

---

Instant Answer Page: https://duck.co/ia/view/wikihow

**Comment by tagawa** [comment]
Thanks for filing this @javathunderman. We've disabled this IA for now until a fix is released.
By the way, the content shown from wikiHow is actually data we've parsed and cached so not live data, which reduces the threat a little but is still obviously something we need to fix.
/cc @bbraithwaite

**Comment by javathunderman** [comment]
Same here, @tagawa. Seeing it on the latest version of the Android app.
________________________________

**Comment by tagawa** [comment]
@kyzn @javathunderman Thanks for spotting that. Not sure what happened but I've just let the developers know.

**Comment by pjhampton** [comment]
Sorry I'm late to the party.

Weird, I thought we had dealt with this early on in the post-processing of the data. However, this was a consistent issue with the FatHead IAs for programming

However, are we _really_ sure this is XSS vulnerable? :thinking: https://www.owasp.org/index.php/Testing_for_Cross_site_scripting

I have ran some tests of my own and got someone else to look at this as well.

What testing has the OP of that post done? How has he submitted a value via a vanilla textarea? Needs more details... disable if you guys feel fit though.

**Comment by moollaza** [comment]
We're investigating a frontend fix for this.

As @tagawa and @pjhampton mentioned, there isn't a real vulnerability here as it's just an input on the page. With DuckDuckHack in maintenance, the Fatheads are not being updated so for now this is more of an issue of the SERP breaking. 

The IA is being taken offline (and some others that are breaking the SERP) and once we manage to fix we'll bring them back.

**Comment by kyzn** [comment]
I agree with @pjhampton, and I feel like this is more of a HTML injection. https://www.owasp.org/index.php/Testing_for_HTML_Injection_(OTG-CLIENT-003)

Thanks for taking care of DuckDuckGo :1st_place_medal: :slightly_smiling_face:

**Comment by moollaza** [comment]
This has been fixed.
