### ISSUE TITLE
Tldr Pages: xargs

### ISSUE THREAD

**Issue by pavelloz** [duckduckgo/zeroclickinfo-fathead#904]
https://duckduckgo.com/?q=tldr+xargs

Doesn't seem to return instant answer.

Source: https://github.com/tldr-pages/tldr/blob/master/pages/common/xargs.md

------
IA Page:  http://duck.co/ia/view/tldr_pages 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by StewAlexanderACC** [comment]
@pavelloz 

The link is here: https://tldr.ostera.io/xargs

or just use ```!tldr xargs```
