### ISSUE TITLE
HGNC Gene Names: More at HGNC link incorrect

### ISSUE THREAD

**Issue by goodness-from-me** [duckduckgo/zeroclickinfo-fathead#906]
"More at HGNC" link is not working.
E.g. type in search "DDDD" and click on "More at HGNC".

**Current result**: link leads to https://www.genenames.org/data/hgnc_data.php?hgnc_id=HGNC:25055

**Expected result**: link leads to https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:25055

------
IA Page:  http://duck.co/ia/view/hgncgene_names 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jrandall

**Comment by itsrachelfish** [comment]
Yep, this is still a problem!
